/* ============================================================================== 
 * Texas Instruments OMAP(TM) Platform Software (c) Copyright 2009, Texas
 * Instruments Incorporated.  All Rights Reserved.  Use of this software is
 * controlled by the terms and conditions found in the license agreement
 * under which this software has been supplied.
 * =========================================================================== 
 */
/**
 * @file ldcnsf_test_main.h
 *
 * This File contains declarations of structures and functions used 
 * in the MSP LDCNSF component's test code; targeted at MONICA/OMAP4. 
 * 
 *
 * @path  $(DUCATIVOB)\alg\ldcnsf\test\src\
 *
 * @rev  1.0
 */
/* ---------------------------------------------------------------------------- 
 *! 
 *! Revision History 
 *! ===================================
 *! 25-July-2009 Sanish Mahadik: Initial Release
 *!
 *!Revisions appear in reverse chronological order; 
 *! that is, newest first.  The date format is dd-Mon-yyyy.  
 * =========================================================================== */

/* ! \mainpage Documentation for MSP NSF \section Introduction This is the
 * documentation for MSP NSF component. It does not include documentation for 
 * the dependencies involved. */

#ifndef _MSP_LDCNSF_TEST_H
#define _MSP_LDCNSF_TEST_H

#ifdef __cplusplus

extern "C" {
#endif

    /* User code goes here */
    /* ------compilation control switches ------------------------- */
   /****************************************************************
    *  INCLUDE FILES                                                 
    ****************************************************************/
    /* ----- system and platform files ---------------------------- */
   /*-------program files ----------------------------------------*/
#include "../../msp_ldcnsf.h"
#include "../../../platform/osal/timm_osal_memory.h"
#include "../../../platform/osal/timm_osal_trace.h"
   /****************************************************************
    *  EXTERNAL REFERENCES NOTE : only use if not found in header file
    ****************************************************************/
   /****************************************************************
    *  PUBLIC DECLARATIONS Defined here, used elsewhere
    ****************************************************************/
   /*--------data declarations -----------------------------------*/

    /* ========================================================================== 
     */
   /**
    * This is a structure description for NsfTestInputType. This structure is used for providing input to the test-framework of 
    * MSP NSF component.
    *
    * @param  input_fname  Input file Name
    *
    * @param  output_fname  Output file Name
    *
    * @param  ulComputeWidth  width of input in pixels
    *
    * @param  ulComputeHeight  height of input in number of lines
    *
    * @param  eInputFormat  YUV format of the input specifying YUV422/YUV420-NV12 format
    * 				 + whether to process Y-component and/or UV-component
    *
    * @param  bSmoothLumaEn  smooth feature mode of luma component
    *
    * @param  bSmoothChromaEn  smooth feature mode of chroma component
    *
    * @param  eFilterParam  filter parameter enable/default/user-specified 
    *
    * @param  eShdParam  shading correction parameter enable/default/user-specified 
    *
    * @param  eEdgeParam  edge-enhancement parameter enable/default/user-specified 
    *
    * @param  eDesatParam  desaturation parameter enable/default/user-specified 
    *
    *
    * @see 
    */
    /* ========================================================================== 
     */

    typedef struct {

        char input_fname[100];
        char output_fname[100];
        MSP_U32 ulInputWidth;
        MSP_U32 ulInputHeight;
        MSP_U32 ulComputeWidth;
        MSP_U32 ulComputeHeight;
        MSP_U32 ulInputStride;
        MSP_U32 ulOutputStride;
        MSP_LDCNSF_OPERATION_MODE eOperateMode;
        MSP_LDCNSF_DATAFORMAT eInputFormat;
        MSP_LDCNSF_DATAFORMAT eOutputFormat;
        MSP_LDCNSF_INIT_COLOR eBayerInitColor;
        MSP_LDCNSF_Y_INTERPOLATE_METHOD eInterpolationLuma;
        MSP_LDCNSF_AFFINE_PARAMS *ptAffineParams;
        MSP_U32 tStartX;
        MSP_U32 tStartY;
        MSP_BOOL bLumaEn;
        MSP_BOOL bChromaEn;
        MSP_LDCNSF_SMOOTH_PARAM eSmoothVal;
        MSP_BOOL bSmoothLumaEn;
        MSP_BOOL bSmoothChromaEn;
        MSP_LDCNSF_PARAM_SET eFilterParam;
        MSP_LDCNSF_PARAM_SET eShdParam;
        MSP_LDCNSF_PARAM_SET eEdgeParam;
        MSP_LDCNSF_PARAM_SET eDesatParam;
    } LdcNsfTestInputType;

    typedef struct {

        RM_HANDLE pRMHandle;
        RM_RESOURCE_HANDLE IssRMhndl;
        RM_RESOURCE_STATUS stIssStatus;

    } TEST_LDCNSF_CLIENT_HANDLETYPE;

    MSP_LDCNSF_START_LDC ldc_start_params = { 0, 0 };
    MSP_LDCNSF_AFFINE_PARAMS affine_default_params = { 4096, 0, 0, 0, 4096, 0 };
    MSP_LDCNSF_AFFINE_PARAMS affine_horizontal_shift_params =
        { 4096, 0, 100, 0, 4096, 0 };
    MSP_LDCNSF_AFFINE_PARAMS affine_vertical_shift_params =
        { 4096, 0, 0, 0, 4096, 100 };
    MSP_LDCNSF_AFFINE_PARAMS affine_rotation_1_params =
        { 0, 4096, 0, 4096, 0, 0 };
    MSP_LDCNSF_AFFINE_PARAMS affine_rotation_2_params =
        { 4096, 0, 0, 0, 4096, 0 };
    MSP_LDCNSF_AFFINE_PARAMS affine_rotation_3_params =
        { 4096, 0, 0, 0, 4096, 0 };
   /*--------function prototypes ---------------------------------*/

   /****************************************************************
    *  PRIVATE DECLARATIONS Defined here, used only here
    ****************************************************************/
   /*--------data declarations -----------------------------------*/

    /* Test Case Params */
    LdcNsfTestInputType LDCNSF_TestStructure[] =           /* !<
                                                            * Test-structure
                                                            * which holds
                                                            * parameters
                                                            * corresponding
                                                            * to the
                                                            * test-cases */
    {

/*---------------- ZEBU tests-------------------------*/
        /* LDC stand-alone tests */
        /* 1 */ {"176x144.nv12", "Test1_176x144_op_LDC.nv12", 176, 144, 176,
                 144, 192, 176, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
                 MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
                 MSP_LDCNSF_YINTERPOLATION_BICUBIC,
                 &affine_horizontal_shift_params, 0, 0, MSP_FALSE, MSP_FALSE,
                 MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
                 MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
                 MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"176x144.uyvy", "Test2_176x144_op_LDC.uyvy", 176, 144, 176, 144, 352,
         352, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_horizontal_shift_params, 0,
         0, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"128x64_alaw8.raw", "Test3_128x64_alaw8_LDC_op.raw", 128, 64, 128, 64,
         128, 128, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_ALAW8,
         MSP_LDCNSF_BAYER_FORMAT_ALAW8, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"128x64_pack8.raw", "Test4_128x64_pack8_LDC_op.raw", 128, 64, 128, 64,
         128, 128, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_PACK8,
         MSP_LDCNSF_BAYER_FORMAT_PACK8, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"128x64_pack12.raw", "Test5_128x64_pack12_LDC_op.raw", 128, 64, 128,
         64, 192, 192, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_PACK12,
         MSP_LDCNSF_BAYER_FORMAT_PACK12, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"128x64_unpack12.raw", "Test6_128x64_unpack12_LDC_op.raw", 128, 64,
         128, 64, 256, 256, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},

        /* NSF stand-alone tests */
        /* 7 */ {"176x144.uyvy", "Test7_144x112_op_NSF_YUV.uyvy", 176, 144, 144,
                 112, 352, 288, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
                 MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
                 MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0,
                 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
                 MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
                 MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"176x144.nv12", "Test8_144x112_op_NSF_YUV.nv12", 176, 144, 144, 112,
         176, 144, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* LDC +NSF tests */
        {"176x144.uyvy", "Test9_144x112_op_LDCNSF_YUV.nv12", 176, 144, 144, 112,
         352, 144, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"176x144.uyvy", "Test10_144x112_op_LDCNSF_YUV.uyvy", 176, 144, 144,
         112, 352, 288, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

/*-------------------------Simulator/SDC tests------------------*/
        /* LDC stand-alone tests */

        /* 11 */
        {"640x480.nv12", "Test11_480x640_op_LDC.nv12", 640, 480, 480, 640, 640,
         480, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_rotation_1_params, 36, 10,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"5056x3280.nv12", "Test12_5056x3280_op_LDC.nv12", 5056, 3280, 5056,
         3280, 5056, 5056, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 6, 46,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"640x480.uyvy", "Test13_640x480_op_LDC.uyvy", 640, 480, 640, 480, 1280,
         1280, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_horizontal_shift_params, 0,
         0, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"5056x3280.uyvy", "Test14_5056x3280_op_LDC.uyvy", 5056, 3280, 5056,
         3280, 10112, 10112, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_vertical_shift_params, 0,
         0, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},

        /* 15 */
        {"4096x3016_pack8.raw", "Test15_4096x3016_pack8_LDC_op.raw", 4096, 3016,
         4096, 3016, 4096, 4096, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_PACK8,
         MSP_LDCNSF_BAYER_FORMAT_PACK8, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"4096x3016_pack8.raw", "Test16_4096x3016_alaw8_LDC_op.raw", 4096, 3016,
         4096, 3016, 4096, 4096, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_ALAW8,
         MSP_LDCNSF_BAYER_FORMAT_ALAW8, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"4096x3016_pack12.raw", "Test17_4096x3016_pack12_LDC_op.raw", 4096,
         3016, 4096, 3016, 6144, 6144, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_PACK12, MSP_LDCNSF_BAYER_FORMAT_PACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 0, 0, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"4096x3016_unpack12.raw", "Test18_4096x3016_unpack12_LDC_op.raw", 4096,
         3016, 4096, 3016, 8192, 8192, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 0, 0, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},

        /* NSF stand-alone tests */

        /* 19 */
        {"640x480.uyvy", "Test19_608x448_op_NSF_YUV.uyvy", 640, 480, 608, 448,
         1280, 1216, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_USER, MSP_LDCNSF_PARAM_USER, MSP_LDCNSF_PARAM_USER,
         MSP_LDCNSF_PARAM_USER},
        {"640x480.uyvy", "Test20_608x448_op_NSF_Y.uyvy", 640, 480, 608, 448,
         1280, 1216, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"640x480.uyvy", "Test21_608x448_op_NSF_UV.uyvy", 640, 480, 608, 448,
         1280, 1216, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.nv12", "Test22_608x448_op_NSF_YUV.nv12", 640, 480, 608, 448,
         640, 608, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 23 */
        {"640x480.nv12", "Test23_608x448_op_NSF_Y.nv12", 640, 480, 608, 448,
         640, 608, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.nv12", "Test24_608x448_op_NSF_UV.nv12", 640, 480, 608, 448,
         640, 608, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"5056x3280.uyvy", "Test25_5024x3248_op_NSF_YUV.uyvy", 5056, 3280, 5024,
         3248, 10112, 10048, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"5056x3280.nv12", "Test26_5024x3248_op_NSF_YUV.nv12", 5056, 3280, 5024,
         3248, 5056, 5024, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* LDC+NSF test-cases */
        /* 27 */
        {"640x480.uyvy", "Test27_608x448_op_LDCNSF_YUV.nv12", 640, 480, 608,
         448, 1280, 608, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.uyvy", "Test28_608x448_op_LDCNSF_Y.nv12", 640, 480, 608, 448,
         1280, 608, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.uyvy", "Test29_608x448_op_LDCNSF_UV.nv12", 640, 480, 608, 448,
         1280, 608, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 30 */
        {"640x480.uyvy", "Test30_608x448_op_LDCNSF_YUV.uyvy", 640, 480, 608,
         448, 1280, 1216, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.uyvy", "Test31_608x448_op_LDCNSF_Y.uyvy", 640, 480, 608, 448,
         1280, 1216, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.uyvy", "Test32_608x448_op_LDCNSF_UV.uyvy", 640, 480, 608, 448,
         1280, 1216, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 33 */
        {"5056x3280.uyvy", "Test33_5024x3248_op_LDCNSF_YUV.nv12", 5056, 3280,
         5024, 3248, 10112, 5024, MODE_LDC_AFFINE_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"5056x3280.uyvy", "Test34_5024x3248_op_LDCNSF_YUV.uyvy", 5056, 3280,
         5024, 3248, 10112, 10048, MODE_LDC_AFFINE_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 35 */
        {"640x480.uyvy", "Test35_608x448_op_LDCNSF_YUV.nv12", 640, 480, 608,
         448, 1280, 608, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_rotation_1_params, 30, 40,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_USER, MSP_LDCNSF_PARAM_USER, MSP_LDCNSF_PARAM_USER,
         MSP_LDCNSF_PARAM_USER},
        {"640x480.uyvy", "Test36_608x448_op_LDCNSF_YUV.nv12", 640, 480, 608,
         448, 1280, 608, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_rotation_1_params, 35, 45,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_USER, MSP_LDCNSF_PARAM_USER, MSP_LDCNSF_PARAM_USER,
         MSP_LDCNSF_PARAM_USER},
        {"176x144.uyvy", "Test37_176x144_op_LDC.uyvy", 176, 144, 176, 144, 352,
         352, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_horizontal_shift_params,
         10, 30, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE,
         MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},

        /* 38 */
        {"176x144.uyvy", "Test38_176x144_op_LDC.uyvy", 176, 144, 176, 144, 352,
         352, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_horizontal_shift_params,
         10, 30, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE,
         MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"176x144.uyvy", "Test39_176x144_op_LDC.uyvy", 176, 144, 176, 144, 352,
         352, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_horizontal_shift_params,
         10, 30, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE,
         MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"176x144.uyvy", "Test40_176x144_LDC_op.uyvy", 176, 144, 176, 144, 352,
         352, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 41 */
        {"636x476.uyvy", "Test41_640x444_op_YUV.nv12", 636, 476, 604, 444, 1280,
         640, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.uyvy", "Test42_608x448_op_NSF_YUV.uyvy", 640, 480, 608, 448,
         1280, 1216, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.uyvy", "Test43_608x448_op_LDCNSF_YUV.uyvy", 640, 480, 608,
         448, 1280, 1216, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"176x144.uyvy", "Test44_176x144_op_LDC.uyvy", 176, 144, 176, 144, 352,
         352, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_horizontal_shift_params,
         10, 30, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE,
         MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},

        /* In-place Operation tests */
        // NSF-standalone /*45*/
        {"640x480.uyvy", "Test45_640x448_op_NSF_YUV.uyvy", 640, 480, 608, 448,
         1280, 1280, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_USER, MSP_LDCNSF_PARAM_USER, MSP_LDCNSF_PARAM_USER,
         MSP_LDCNSF_PARAM_USER},
        {"640x480.nv12", "Test46_640x448_op_NSF_YUV.nv12", 640, 480, 608, 448,
         640, 640, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        // LDC-standalone
        {"640x480.nv12", "Test47_640x480_op_LDC.nv12", 640, 480, 640, 480, 640,
         640, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 36, 10,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"640x480.uyvy", "Test48_640x480_op_LDC.uyvy", 640, 480, 640, 480, 1280,
         1280, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_horizontal_shift_params, 0,
         0, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},

        // LDC+NSF with In-place operation
        {"640x480.uyvy", "Test49_1280x448_op_LDCNSF_YUV.nv12", 640, 480, 608,
         448, 1280, 1280, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.uyvy", "Test50_864x448_op_LDCNSF_YUV.uyvy", 640, 480, 608,
         448, 1728, 1728, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        // LDC+NSF with YUV420 input
        /* 51 */
        {"640x480.nv12", "Test51_608x448_op_LDCNSF_YUV.nv12", 640, 480, 608,
         448, 640, 608, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        // Different resolutions
        /* 320x240 52-54 */
        {"320x240_unpack12.raw", "Test52_320x240_unpack12_CAC_op.raw", 320, 240,
         320, 240, 640, 640, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"320x240.uyvy", "Test53_288x208_op_LDCNSF_YUV.nv12", 320, 240, 288,
         208, 640, 288, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"320x240.uyvy", "Test54_288x208_op_LDCNSF_YUV.uyvy", 320, 240, 288,
         208, 640, 576, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 800x600 55-57 */
        {"800x600_unpack12.raw", "Test55_800x600_unpack12_CAC_op.raw", 800, 600,
         800, 600, 1600, 1600, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 6, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"800x600.uyvy", "Test56_768x568_op_LDCNSF_YUV.nv12", 800, 600, 768,
         568, 1600, 768, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"800x600.uyvy", "Test57_768x568_op_NSF_YUV.uyvy", 800, 600, 768, 568,
         1600, 1536, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_3, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 1280x1024 58-60 */
        {"1280x1024_unpack12.raw", "Test58_1280x1024_unpack12_CAC_op.raw", 1280,
         1024, 1280, 1024, 2560, 2560, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 20, 34, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"1280x1024.uyvy", "Test59_1248x992_op_LDCNSF_YUV.nv12", 1280, 1024,
         1248, 992, 2560, 1248, MODE_LDC_AFFINE_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1280x1024.uyvy", "Test60_1280x1024_op_LDC.uyvy", 1280, 1024, 1280,
         1024, 2560, 2560, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 6, 8,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_3, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 720x480 61-63 */
        {"720x480_unpack12.raw", "Test61_720x480_unpack12_CAC_op.raw", 720, 480,
         720, 480, 1440, 1440, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 0, 0, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"720x480.uyvy", "Test62_688x448_op_LDCNSF_YUV.nv12", 720, 480, 688,
         448, 1440, 688, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"720x480.uyvy", "Test63_720x480_op_LDC.uyvy", 720, 480, 720, 480, 1440,
         1440, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 18, 28,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_3, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 1280x720 64-66 */
        {"1280x720_unpack12.raw", "Test64_1280x720_unpack12_CAC_op.raw", 1280,
         720, 1280, 720, 2560, 2560, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 20, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"1280x720.uyvy", "Test65_1248x688_op_LDCNSF_YUV.nv12", 1280, 720, 1248,
         688, 2560, 1248, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 10, 20,
         MSP_TRUE, MSP_FALSE, MSP_LDCNSF_SMOOTH_0, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1280x720_pack8.raw", "Test66_1280x720_pack8_CAC_op.raw", 1280, 720,
         1280, 720, 1280, 1280, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_PACK8,
         MSP_LDCNSF_BAYER_FORMAT_PACK8, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},

        /* 1920x1080 67-69 */
        {"1920x1080_unpack12.raw", "Test67_1920x1080_unpack12_CAC_op.raw", 1920,
         1080, 1920, 1080, 3840, 3840, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 20, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"1920x1080.uyvy", "Test68_1888x1048_op_LDCNSF_YUV.nv12", 1920, 1080,
         1888, 1048, 3840, 1888, MODE_LDC_AFFINE_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 20, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_SMOOTH_2, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT},
        {"1920x1080_alaw8.raw", "Test69_1920x1080_alaw8_CAC_op.raw", 1920, 1080,
         1920, 1080, 1920, 1920, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_ALAW8,
         MSP_LDCNSF_BAYER_FORMAT_ALAW8, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},

        /* 2048x1080 70-72 */
        {"2048x1080_unpack12.raw", "Test70_2048x1080_unpack12_CAC_op.raw", 2048,
         1080, 2048, 1080, 4096, 4096, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 20, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"2048x1080.uyvy", "Test71_2016x1048_op_LDCNSF_YUV.nv12", 2048, 1080,
         2016, 1048, 4096, 2016, MODE_LDC_AFFINE_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"2048x1080_pack12.raw", "Test72_2048x1080_pack12_CAC_op.raw", 2048,
         1080, 2048, 1080, 3072, 3072, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_PACK12, MSP_LDCNSF_BAYER_FORMAT_PACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 20, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},

        /* 1280x800 73-75 */
        {"1280x800_unpack12.raw", "Test73_1280x800_unpack12_CAC_op.raw", 1280,
         800, 1280, 800, 2560, 2560, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 20, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"1280x800.uyvy", "Test74_1248x768_op_LDCNSF_YUV.nv12", 1280, 800, 1248,
         768, 2560, 1248, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 10, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1280x800.nv12", "Test75_1248x768_op_NSF_YUV.nv12", 1280, 800, 1248,
         768, 1280, 1248, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_3, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},

        /* 1376x768 76-78 */
        {"1376x768_unpack12.raw", "Test76_1376x768_unpack12_CAC_op.raw", 1376,
         768, 1376, 768, 2752, 2752, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 20, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"1376x768.uyvy", "Test77_1344x736_op_LDCNSF_YUV.uyvy", 1376, 768, 1344,
         736, 2752, 2688, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 10, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1376x768.uyvy", "Test78_1344x736_op_NSF_YUV.uyvy", 1376, 768, 1344,
         736, 2752, 2688, MODE_NSF_ONLY, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_3, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 320x200 79-81 */
        {"320x200_unpack12.raw", "Test79_320x200_unpack12_CAC_op.raw", 320, 200,
         320, 200, 640, 640, MODE_CAC_AFFINE, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_INITCOLOR_RED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 10, 20,
         MSP_FALSE, MSP_FALSE, MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE},
        {"320x200.nv12", "Test80_288x168_op_LDCNSF_YUV.nv12", 320, 200, 288,
         168, 320, 288, MODE_LDC_AFFINE_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BILINEAR, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"320x200.uyvy", "Test81_320x200_op_LDC.uyvy", 320, 200, 320, 200, 640,
         640, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_3, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 2560x2048 82-84 */
        {"2560x2048_unpack12.raw", "Test82_2560x2048_unpack12_CAC_op.raw", 2560,
         2048, 2560, 2048, 5120, 5120, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 10, 20, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"2560x2048.nv12", "Test83_2528x2016_op_LDCNSF_YUV.nv12", 2560, 2048,
         2528, 2016, 2560, 2528, MODE_LDC_AFFINE_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"2560x2048.nv12", "Test84_2560x2048_op_LDC.nv12", 2560, 2048, 2560,
         2048, 2560, 2560, MODE_LDC_AFFINE, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 20, 6,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_3, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},

        /* 2560x1600 85-87 */
        {"2560x1600_unpack12.raw", "Test85_2560x1600_unpack12_CAC_op.raw", 2560,
         1600, 2560, 1600, 5120, 5120, MODE_CAC_AFFINE,
         MSP_LDCNSF_BAYER_FORMAT_UNPACK12, MSP_LDCNSF_BAYER_FORMAT_UNPACK12,
         MSP_LDCNSF_INITCOLOR_RED, MSP_LDCNSF_YINTERPOLATION_BILINEAR,
         &affine_default_params, 20, 40, MSP_FALSE, MSP_FALSE,
         MSP_LDCNSF_SMOOTH_1, MSP_FALSE, MSP_FALSE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DISABLE,
         MSP_LDCNSF_PARAM_DISABLE},
        {"2560x1600.uyvy", "Test86_2528x1568_op_LDCNSF_YUV.nv12", 2560, 1600,
         2528, 1568, 5120, 2528, MODE_LDC_AFFINE_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC,
         &affine_default_params, 10, 50, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_SMOOTH_0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DISABLE, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DISABLE},

        /* Fast NSF2 test-case */
        // {"176x144.uyvy", "Test150_144x112_op_LDCNSF_Fast_YUV.nv12", 176,
        // 144, 144, 112, 352, 176, MODE_FAST_NSF,
        // MSP_LDCNSF_YUV_FORMAT_YCBCR422 , MSP_LDCNSF_YUV_FORMAT_YCBCR420 ,
        // MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC , 
        // &affine_default_params,0,0,MSP_TRUE, MSP_TRUE,
        // MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, 
        // MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
        // MSP_LDCNSF_PARAM_DEFAULT},
        {"320x200.uyvy", "Test87_288x168_op_LDCNSF_Fast_YUV.nv12", 320, 200,
         288, 168, 640, 320, MODE_FAST_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"320x240.uyvy", "Test88_288x208_op_LDCNSF_Fast_YUV.nv12", 320, 240,
         288, 208, 640, 320, MODE_FAST_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        // {"636x476.uyvy", "Test150_604x444_op_LDCNSF_Fast_YUV.nv12", 636,
        // 476, 604, 444, 1272, 636, MODE_FAST_NSF,
        // MSP_LDCNSF_YUV_FORMAT_YCBCR422 , MSP_LDCNSF_YUV_FORMAT_YCBCR420 ,
        // MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC , 
        // &affine_default_params,0,0,MSP_TRUE, MSP_TRUE,
        // MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, 
        // MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
        // MSP_LDCNSF_PARAM_DEFAULT},
        {"640x480.uyvy", "Test89_608x448_op_LDCNSF_Fast_YUV.nv12", 640, 480,
         608, 448, 1280, 640, MODE_FAST_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"720x480.uyvy", "Test90_688x448_op_LDCNSF_Fast_YUV.nv12", 720, 480,
         688, 448, 1440, 720, MODE_FAST_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"800x600.uyvy", "Test91_768x568_op_LDCNSF_Fast_YUV.nv12", 800, 600,
         768, 568, 1600, 800, MODE_FAST_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1280x720.uyvy", "Test92_1248x688_op_LDCNSF_Fast_YUV.nv12", 1280, 720,
         1248, 688, 2560, 1280, MODE_FAST_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1280x800.uyvy", "Test93_1248x768_op_LDCNSF_Fast_YUV.nv12", 1280, 800,
         1248, 768, 2560, 1280, MODE_FAST_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1280x1024.uyvy", "Test94_1248x992_op_LDCNSF_Fast_YUV.nv12", 1280,
         1024, 1248, 992, 2560, 1280, MODE_FAST_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1376x768.uyvy", "Test95_1344x736_op_LDCNSF_Fast_YUV.nv12", 1376, 768,
         1344, 736, 2752, 1376, MODE_FAST_NSF, MSP_LDCNSF_YUV_FORMAT_YCBCR422,
         MSP_LDCNSF_YUV_FORMAT_YCBCR420, MSP_LDCNSF_INITCOLOR_DISABLED,
         MSP_LDCNSF_YINTERPOLATION_BICUBIC, &affine_default_params, 0, 0,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1, MSP_TRUE, MSP_TRUE,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"1920x1080.uyvy", "Test96_1920x1048_op_LDCNSF_Fast_YUV.nv12", 1920,
         1048, 1888, 1048, 3840, 1920, MODE_FAST_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"2048x1080.uyvy", "Test97_2016x1048_op_LDCNSF_Fast_YUV.nv12", 2048,
         1048, 2016, 1048, 4096, 2048, MODE_FAST_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"2560x1600.uyvy", "Test98_2528x1568_op_LDCNSF_Fast_YUV.nv12", 2560,
         1600, 2528, 1568, 5120, 2560, MODE_FAST_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"4000x3000.uyvy", "Test99_3968x2968_op_LDCNSF_Fast_YUV.nv12", 4000,
         3000, 3968, 2968, 8000, 4000, MODE_FAST_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
        {"5056x3280.uyvy", "Test100_5024x3248_op_LDCNSF_Fast_YUV.nv12", 5056,
         3280, 5024, 3248, 10112, 5056, MODE_FAST_NSF,
         MSP_LDCNSF_YUV_FORMAT_YCBCR422, MSP_LDCNSF_YUV_FORMAT_YCBCR420,
         MSP_LDCNSF_INITCOLOR_DISABLED, MSP_LDCNSF_YINTERPOLATION_BICUBIC,
         &affine_default_params, 0, 0, MSP_TRUE, MSP_TRUE, MSP_LDCNSF_SMOOTH_1,
         MSP_TRUE, MSP_TRUE, MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT,
         MSP_LDCNSF_PARAM_DEFAULT, MSP_LDCNSF_PARAM_DEFAULT},
    };
   /*--------function prototypes ---------------------------------*/

   /*--------macros ----------------------------------------------*/
    /* ! \def INPUT_PATH relative path of the input test-vector w.r.t.
     * base-image location */
#define INPUT_PATH      "..\\..\\..\\..\\..\\alg\\ldcnsf\\test\\test_vectors\\input\\"
    // #define INPUT_PATH ".\\"

    /* ! \def OUTPUT_PATH relative path of the output test-vector w.r.t.
     * base-image location */
#define OUTPUT_PATH "..\\..\\..\\..\\..\\alg\\ldcnsf\\test\\test_vectors\\output\\"

    // #define OUTPUT_PATH ".\\"

    /* ! \def MAX_NSF_TEST_NUM Maximum number of test-cases */

#define MAX_LDCNSF_TEST_NUM 100
#define LDCNSF_STRESS_TESTING 1000

#define MSP_LDCNSF_EXIT_IF(_Cond,_ErrorCode) { \
   if ((_Cond)) { \
      /* status = _ErrorCode;*/ \
      TIMM_OSAL_TraceFunction("Error :: %s : %s : %d :: Exiting because : %s\n", \
	      __FILE__, __FUNCTION__, __LINE__, #_Cond); \
      goto EXIT; \
   } \
}

    static void Update_TestParams_LDCNSF(MSP_LDCNSF_CREATE_PARAMS * pApp_params,
                                         Uint8 testnum);
    static void LDCNSF_Allocate_TestBuffers(Uint8 testnum,
                                            MSP_BUFHEADER_TYPE * inbuf,
                                            MSP_BUFHEADER_TYPE * outbuf,
                                            MSP_LDCNSF_CREATE_PARAMS * pParam);
    static MSP_ERROR_TYPE MSP_LDCNSF_Callback(MSP_PTR hMSP, MSP_PTR pAppData,
                                              MSP_EVENT_TYPE tEvent,
                                              MSP_OPAQUE nEventData1,
                                              MSP_OPAQUE nEventData2);

#ifdef DBG_SERVER_SCRIPTING
    void ldcnsf_test_main(int testnum);
#else
    void ldcnsf_test_main();
#endif

#ifdef __cplusplus
}
#endif

#endif
