#ifndef _CSLR_TI816XPRCM_H_
#define _CSLR_TI816XPRCM_H_


typedef struct  {
    volatile Uint8  RSVD0[256];
    /**< PRM_DEVICE */
    volatile Uint8  RSVD1[256];
    /**< CM_DEVICE */
    volatile Uint8  RSVD2[256];
    /**< OCP_SOCKET_PRM */
    volatile Uint32 CM_SYSCLK1_CLKSEL;
    volatile Uint32 CM_SYSCLK2_CLKSEL;
    volatile Uint32 CM_SYSCLK3_CLKSEL;
    volatile Uint32 CM_SYSCLK4_CLKSEL;
    volatile Uint32 CM_SYSCLK5_CLKSEL;
    volatile Uint32 CM_SYSCLK6_CLKSEL;
    volatile Uint32 CM_SYSCLK7_CLKSEL;
    volatile Uint8 RSVD3[8];
    volatile Uint32 CM_SYSCLK10_CLKSEL;
    volatile Uint8 RSVD4[4];
    volatile Uint32 CM_SYSCLK11_CLKSEL;
    volatile Uint32 CM_SYSCLK12_CLKSEL;
    volatile Uint32 CM_SYSCLK13_CLKSEL;
    volatile Uint32 CM_SYSCLK15_CLKSEL;
    volatile Uint8 RSVD5[196];
    /**< CM_DPLL */
    volatile Uint32 CM_GEM_CLKSTCTRL;
    volatile Uint32 CM_HDDSS_CLKSTCTRL;
    volatile Uint32 CM_HDMI_CLKSTCTRL;
    volatile Uint8 RSVD6[20];
    volatile Uint32 CM_ACTIVE_GEM_CLKCTRL;
    volatile Uint32 CM_ACTIVE_HDDSS_CLKCTRL;
    volatile Uint32 CM_ACTIVE_HDMI_CLKCTRL;
    volatile Uint8 RSVD7[212];
    /**< CM_ACTIVE */
    volatile Uint8  RSVD8[256];
    /**< CM_DEFAULT */
    volatile Uint8  RSVD9[256];
    /**< CM_IVAHD0 */
    volatile Uint8  RSVD10[256];
    /**< CM_IVAHD1 */
    volatile Uint8  RSVD11[256];
    /**< CM_IVAHD2 */
    volatile Uint8  RSVD12[256];
    /**< CM_SGX */
    volatile Uint8  RSVD13[256];
    /**< PRM_ACTIVE */
    volatile Uint8  RSVD14[256];
    /**< PRM_DEFAULT */
    volatile Uint8  RSVD15[256];
    /**< PRM_IVAHD0 */
    volatile Uint8  RSVD16[256];
    /**< PRM_IVAHD1 */
    volatile Uint8  RSVD17[256];
    /**< PRM_IVAHD2 */
    volatile Uint8  RSVD18[256];
    /**< PRM_SGX */
    volatile Uint8  RSVD19[1024];
    /**< PRM_SGX */
    volatile Uint8  RSVD20[360];
    /**< CM_ALWON */
    volatile Uint32 CM_ALWON_I2C_1_CLKCTRL;
} CSL_Prcm_Regs;

typedef volatile CSL_Prcm_Regs           *CSL_PrcmRegs;

#define VPS_PRCM_CM_SYSCLK10_CLKSEL_CLKSEL_MASK         (0x7u)
#define VPS_PRCM_CM_SYSCLK10_CLKSEL_CLKSEL_SHIFT        (0u)

#define VPS_PRCM_CM_SYSCLK11_CLKSEL_CLKSEL_MASK         (0x1u)
#define VPS_PRCM_CM_SYSCLK11_CLKSEL_CLKSEL_SHIFT        (0u)

#define VPS_PRCM_CM_SYSCLK13_CLKSEL_CLKSEL_MASK         (0x7u)
#define VPS_PRCM_CM_SYSCLK13_CLKSEL_CLKSEL_SHIFT        (0u)

#define VPS_PRCM_CM_SYSCLK15_CLKSEL_CLKSEL_MASK         (0x7u)
#define VPS_PRCM_CM_SYSCLK15_CLKSEL_CLKSEL_SHIFT        (0u)

/* CM_HDDSS_CLKSTCTRL */
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKTRCTRL_MASK     (0x3u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKTRCTRL_SHIFT    (0u)

#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HDMI_GCLK_MASK  (0x100u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HDMI_GCLK_SHIFT (8u)

#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HDCOMP_GCLK_MASK  (0x200u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HDCOMP_GCLK_SHIFT (9u)

#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_SD_GCLK_MASK  (0x400u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_SD_GCLK_SHIFT (10u)

#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_RFMOD_GCLK_MASK  (0x800u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_RFMOD_GCLK_SHIFT (11u)

#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HD_DSS_L3_GCLK_MASK  (0x1000u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HD_DSS_L3_GCLK_SHIFT (12u)

#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HD_DSS_L4_GCLK_MASK  (0x2000u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HD_DSS_L4_GCLK_SHIFT (13u)

#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_PROC_GCLK_MASK  (0x4000u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_PROC_GCLK_SHIFT (14u)

#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HD_DSS_L3_EN_GCLK_MASK  (0x8000u)
#define VPS_PRCM_CM_HDVPSS_CLKSTCTRL_CLKACTIVITY_HD_DSS_L3_EN_GCLK_SHIFT (15u)

/* CM_HDMI_CLKSTCTRL */
#define VPS_PRCM_CM_HDMI_CLKSTCTRL_CLKTRCTRL_MASK  (0x3u)
#define VPS_PRCM_CM_HDMI_CLKSTCTRL_CLKTRCTRL_SHIFT (0u)

#define VPS_PRCM_CM_HDMI_CLKSTCTRL_CLKACTIVITY_HDMI_OCP_GCLK_MASK  (0x100u)
#define VPS_PRCM_CM_HDMI_CLKSTCTRL_CLKACTIVITY_HDMI_OCP_GCLK_SHIFT (8u)

#define VPS_PRCM_CM_HDMI_CLKSTCTRL_CLKACTIVITY_HDMI_CEC_GCLK_MASK  (0x200u)
#define VPS_PRCM_CM_HDMI_CLKSTCTRL_CLKACTIVITY_HDMI_CEC_GCLK_SHIFT (9u)

/* CM_ACTIVE_HDDSS_CLKCTRL */
#define VPS_PRCM_CM_ACTIVE_HDDSS_CLKCTRL_MODULEMODE_MASK  (0x3u)
#define VPS_PRCM_CM_ACTIVE_HDDSS_CLKCTRL_MODULEMODE_SHIFT (0u)

#define VPS_PRCM_CM_ACTIVE_HDDSS_CLKCTRL_IDLEST_MASK  (0x30000u)
#define VPS_PRCM_CM_ACTIVE_HDDSS_CLKCTRL_IDLEST_SHIFT (16u)

#define VPS_PRCM_CM_ACTIVE_HDDSS_CLKCTRL_STBYST_MASK  (0x40000u)
#define VPS_PRCM_CM_ACTIVE_HDDSS_CLKCTRL_STBYST_SHIFT (18u)

/* CM_ACTIVE_HDMI_CLKCTRL */
#define VPS_PRCM_CM_ACTIVE_HDMI_CLKCTRL_MODULEMODE_MASK  (0x3u)
#define VPS_PRCM_CM_ACTIVE_HDMI_CLKCTRL_MODULEMODE_SHIFT (0u)

#define VPS_PRCM_CM_ACTIVE_HDMI_CLKCTRL_IDLEST_MASK  (0x30000u)
#define VPS_PRCM_CM_ACTIVE_HDMI_CLKCTRL_IDLEST_SHIFT (16u)

/* CM_ALWON_I2C_1_CLKCTRL */

#define VPS_PRCM_CM_ALWON_I2C_1_CLKCTRL_IDLEST_MASK     (0x00030000u)
#define VPS_PRCM_CM_ALWON_I2C_1_CLKCTRL_IDLEST_SHIFT    (16u)

#define VPS_PRCM_CM_ALWON_I2C_1_CLKCTRL_MODULEMODE_MASK     (0x00000003u)
#define VPS_PRCM_CM_ALWON_I2C_1_CLKCTRL_MODULEMODE_SHIFT    (0u)

#endif /* End of _CSLR_TI816XPRCM_H_ */

