/*******************************************************************************
 *                                                                             *
 * Copyright (c) 2009 Texas Instruments Incorporated - http://www.ti.com/      *
 *                        ALL RIGHTS RESERVED                                  *
 *                                                                             *
 ******************************************************************************/

/*********************************************************************
* file: cslr_vps_grpx.h
*
* Brief: This file contains the Register Description for vps_grpx
*
*********************************************************************/
#ifndef _CSLR_VPS_GRPX_H_
#define _CSLR_VPS_GRPX_H_




/******************************************************************************\
* Field Definition Macros
\******************************************************************************/
/* frame_display_attribute */
#define CSL_VPS_GRPX_FRAME_DISPLAY_ATTRIBUTE_FRAME_HEIGHT_MASK     (0x0000FFFFu)
#define CSL_VPS_GRPX_FRAME_DISPLAY_ATTRIBUTE_FRAME_HEIGHT_SHIFT    (0x00000000u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_ATTRIBUTE_FRAME_HEIGHT_RSTVAL   (0x00000001u)

#define CSL_VPS_GRPX_FRAME_DISPLAY_ATTRIBUTE_FRAME_HEIGHT_MAX      (0x000007FFu)

#define CSL_VPS_GRPX_FRAME_DISPLAY_ATTRIBUTE_FRAME_WIDTH_MASK      (0xFFFF0000u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_ATTRIBUTE_FRAME_WIDTH_SHIFT     (0x00000010u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_ATTRIBUTE_FRAME_WIDTH_RSTVAL    (0x00000001u)

#define CSL_VPS_GRPX_FRAME_DISPLAY_ATTRIBUTE_FRAME_WIDTH_MAX       (0x000007FFu)
/* Frame error information */
#define CSL_VPS_GRPX_FRAME_DISPLAY_VPI_DATA_FLUSH_STATUS_MASK      (0x00000008u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_VPI_DATA_FLUSH_STATUS_SHIFT     (0x00000003u)

#define CSL_VPS_GRPX_FRAME_DISPLAY_FRAME_CFG_ERROR_INT_MASK        (0x00000010u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_FRAME_CFG_ERROR_INT_SHIFT       (0x00000004u)


#define CSL_VPS_GRPX_FRAME_DISPLAY_EOL_MISSING_INT_MASK            (0x00000020u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_EOL_MISSING_INT_SHIFT           (0x00000005u)

#define CSL_VPS_GRPX_FRAME_DISPLAY_EOF_MISSING_INT_MASK            (0x00000040u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_EOF_MISSING_INT_SHIFT           (0x00000006u)

#define CSL_VPS_GRPX_FRAME_DISPLAY_FAULTY_POS_INT_MASK             (0x00000080u)
#define CSL_VPS_GRPX_FRMAE_DISPLAY_FAULTY_POS_INT_SHIFT            (0x00000007u)

#define CSL_VPS_GRPX_FRAME_DISPLAY_FAULTY_REGION_INT_MASK          (0x00000F00u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_FAULTY_REGION_INT_SHIFT         (0x00000008u)

#define CSL_VPS_GRPX_FRAME_DISPLAY_VERTICAL_POSITION_MASK          (0x0000FFFFu)
#define CSL_VPS_GRPX_FRAME_DISPLAY_VERTICAL_POSITION_SHIFT         (0x00000000u)

#define CSL_VPS_GRPX_FRAME_DISPLAY_HORIZONTAL_POSITION_MASK        (0xFFFF0000u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_HORIZONTAL_POSITION_SHIFT       (0x00000010u)

/* new added GRPX features*/
#define CSL_VPS_GRPX_FRAME_DISPLAY_SRC_FMT_INTERLACED_MASK         (0x40000000u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_SRC_FMT_INTERLACED_SHIFT        (0x0000001Eu)

#define CSL_VPS_GRPX_FRAME_DISPLAY_SOFT_RESET_MASK                 (0x80000000u)
#define CSL_VPS_GRPX_FRAME_DISPLAY_SOFT_RESET_SHIFT                (0x0000001Fu)

/* region_display_attribute */
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_REGION_WIDTH_MASK    (0x0000FFFFu)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_REGION_WIDTH_SHIFT   (0x00000000u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_REGION_WIDTH_RSTVAL  (0x00000080u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_REGION_WIDTH_MAX     (0x00000780u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_REGION_HEIGHT_MASK   (0xFFFF0000u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_REGION_HEIGHT_SHIFT  (0x00000010u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_REGION_HEIGHT_RSTVA  (0x00000080u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_REGION_HEIGHT_MAX    (0x000007FFu)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_POS_X_MASK      (0x0000FFFFu)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_POS_X_SHIFT     (0x00000000u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_POS_Y_MASK      (0xFFFF0000u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_POS_Y_SHIFT     (0x00000010u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_PRIOR_MASK      (0x0000000Fu)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_PRIOR_SHIFT     (0x00000000u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_FIRST_REG_MASK (0x00000080u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_FIRST_REG_SHIFT (0x00000007u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_LAST_REG_MASK  (0x00000100u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_LAST_REG_SHIFT (0x00000008u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_SCALER_ENABLE_MASK   (0x00000200u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_SCALER_ENABLE_SHIFT  (0x00000009u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_SCALER_ENABLE_RSTVAL (0x00000000u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_AF_CFG_MASK     (0x00000400u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_AF_CFG_SHIFT    (0x0000000Au)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_STENCILING_EN_MASK   (0x00000800u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_STENCILING_EN_SHIFT  (0x0000000Bu)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_STENCILING_EN_RSTVAL (0x00000000u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_BOUND_BOX_EN_MASK    (0x00008000u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_BOUND_BOX_EN_SHIFT   (0x0000000Fu)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_BOUND_BOX_EN_RSTVAL  (0x00000000u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_BB_ALPHA_MASK        (0x00FF0000u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_BB_ALPHA_SHIFT       (0x00000010u)

#define CLS_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_BLEND_VALUE_MASK (0xFF000000u)
#define CLS_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_BLEND_VALUE_SHIFT (0x00000018u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_BLEND_TYPE_MASK (0x00000003u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_BLEND_TYPE_SHIFT (0x00000000u)

#define CSL_VPS_GRPX_REGION_DSIPLAY_ATTRIBUTE_DISP_TRANS_EN_MASK   (0x00000020u)
#define CSL_VPS_GRPX_REGION_DSIPLAY_ATTRIBUTE_DISP_TRANS_EN_SHIFT  (0x00000005u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_TRANS_TYPE_MASK (0x000000C0u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_TRANS_TYPE_SHIFT (0x00000006u)

#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_TRANS_RGB_MASK  (0xFFFFFF00u)
#define CSL_VPS_GRPX_REGION_DISPLAY_ATTRIBUTE_DISP_TRANS_RGB_SHIFT (0x00000008u)

/* region_scaler_attribute for both horizontal and vertical tap 0 - 4 */

#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE_COEFH_P0_MASK         (0x000003FFu)
#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE_COEFH_P0_SHIFT        (0x00000000u)

#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE_COEFH_P1_MASK         (0x03FF0000u)
#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE_COEFH_P1_SHIFT        (0x00000010u)


/* region_scaler_attribute 6*/
#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE6_COUNTVALHORZ_MASK    (0x00007FFFu)
#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE6_COUNTVALHORZ_SHIFT   (0x00000000u)

#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE6_FINEOFFSETHORZ_MASK  (0x7FFF0000u)
#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE6_FINEOFFSETHORZ_SHIFT (0x00000010u)

#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUT6_HOR_PHASE_MASK        (0x07000000u)
#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUT6_HOR_PHASE_SHIFT       (0x00000018u)

/* region_scaler_attribute 11*/
#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE11_COUNTVALVERT_MASK   (0x00007FFFu)
#define CSL_VPS_GRPX_REGION_SCALER_ATTRIBUTE11_COUNTVALVERT_SHIFT  (0x00000000u)

#endif
