/*
 *  Copyright 2013 by Texas Instruments Incorporated.
 *
 */

/*!
 * File generated by platform wizard. DO NOT MODIFY. 
 *
 */

package ti.sdo.ipc.examples.platforms.evmTI813X.host {
    module Platform;
}

/*
 *  @(#) ti.sdo.ipc.examples.platforms.evmTI813X.host; 1,0,0,; 5-10-2013 12:33:20; /db/vtree/library/trees/ipc/ipc-i15/src/ xlibrary

 */

