#!/bin/sh
if [ "$1" = remove ] || [ "$1" = upgrade ]; then
        SCHEMA_LOCATION=/etc/gconf/schemas
        for SCHEMA in gnome-keyring.schemas; do
                if [ -e $SCHEMA_LOCATION/$SCHEMA ]; then
                        HOME=/root GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
                                gconftool-2 \
                                        --makefile-uninstall-rule $SCHEMA_LOCATION/$SCHEMA > /dev/null
                fi
        done
fi
