/** ==================================================================
 *  @file   always_on_prm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   ALWAYS_ON_PRM
 *
 *  @Filename:    always_on_prm_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __ALWAYS_ON_PRM_CRED_H
#define __ALWAYS_ON_PRM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance ALWAYS_ON_PRM of component ALWAYS_ON_PRM mapped in MONICA at address 0x4A306600
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component ALWAYS_ON_PRM
     *
     */

    /* 
     *  List of bundle arrays for component ALWAYS_ON_PRM
     *
     */

    /* 
     *  List of bundles for component ALWAYS_ON_PRM
     *
     */

    /* 
     * List of registers for component ALWAYS_ON_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT
 *
 * @BRIEF        This register contains dedicated MDMINTC context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT            0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_MPU_WKDEP
 *
 * @BRIEF        This register controls wakeup dependency based on SR_MPU 
 *               service requests. 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_MPU_WKDEP               0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT
 *
 * @BRIEF        This register contains dedicated SR_MPU context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT             0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP
 *
 * @BRIEF        This register controls wakeup dependency based on SR_IVA 
 *               service requests. 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP               0x30ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT
 *
 * @BRIEF        This register contains dedicated SR_IVA context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT             0x34ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP
 *
 * @BRIEF        This register controls wakeup dependency based on SR_CORE 
 *               service requests. 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP              0x38ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT
 *
 * @BRIEF        This register contains dedicated SR_CORE context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT            0x3Cul

    /* 
     * List of register bitfields for component ALWAYS_ON_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of Always_on_CORE_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT__LOSTCONTEXT_DFF__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_MPU_WKDEP__WKUPDEP_SR_MPU_MPU   
 *
 * @BRIEF        Wakeup dependency from SR_MPU module (SWakeup signal) 
 *               towards MPU + L3_1 + L4_CFG domains - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_MPU_WKDEP__WKUPDEP_SR_MPU_MPU BITFIELD(0, 0)
#define ALWAYS_ON_PRM__PM_ALWON_SR_MPU_WKDEP__WKUPDEP_SR_MPU_MPU__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of Always_on_CORE_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT__LOSTCONTEXT_DFF__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_DUCATI   
 *
 * @BRIEF        Wakeup dependency from SR_IVA module (SWakeup signal) 
 *               towards DUCATI + L3_2 + L3_1 + L4_CFG domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_DUCATI BITFIELD(1, 1)
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_DUCATI__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_MPU   
 *
 * @BRIEF        Wakeup dependency from SR_IVA module (SWakeup signal) 
 *               towards MPU + L3_1 + L4_CFG domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_MPU BITFIELD(0, 0)
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_MPU__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of Always_on_CORE_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT__LOSTCONTEXT_DFF__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_DUCATI   
 *
 * @BRIEF        Wakeup dependency from SR_CORE module (SWakeup signal) 
 *               towards DUCATI + L3_2 + L3_1 + L4_CFG domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_DUCATI BITFIELD(1, 1)
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_DUCATI__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_MPU   
 *
 * @BRIEF        Wakeup dependency from SR_CORE module (SWakeup signal) 
 *               towards MPU + L3_1 + L4_CFG domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_MPU BITFIELD(0, 0)
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_MPU__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of Always_on_CORE_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT__LOSTCONTEXT_DFF__POS 0

    /* 
     * List of register bitfields values for component ALWAYS_ON_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_MDMINTC_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_MPU_WKDEP__WKUPDEP_SR_MPU_MPU__ENABLED
 *
 * @BRIEF        Dependency is enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_MPU_WKDEP__WKUPDEP_SR_MPU_MPU__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_MPU_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_DUCATI__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_DUCATI__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_DUCATI__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_DUCATI__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_MPU__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_MPU__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_MPU__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_IVA_WKDEP__WKUPDEP_SR_IVA_MPU__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_IVA_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_DUCATI__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_DUCATI__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_DUCATI__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_DUCATI__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_MPU__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_MPU__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_MPU__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__PM_ALWON_SR_CORE_WKDEP__WKUPDEP_SR_CORE_MPU__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ALWAYS_ON_PRM__RM_ALWON_SR_CORE_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __ALWAYS_ON_PRM_CRED_H 
                                                            */
