/** ==================================================================
 *  @file   cam_cm2_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   CAM_CM2
 *
 *  @Filename:    cam_cm2_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __CAM_CM2_CRED_H
#define __CAM_CM2_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance CAM_CM2 of component CAM_CM2 mapped in MONICA at address 0x4A009000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component CAM_CM2
     *
     */

    /* 
     *  List of bundle arrays for component CAM_CM2
     *
     */

    /* 
     *  List of bundles for component CAM_CM2
     *
     */

    /* 
     * List of registers for component CAM_CM2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL
 *
 * @BRIEF        This register enables the domain power state transition. It 
 *               controls the HW supervised domain power state transition 
 *               between ON-ACTIVE and ON-INACTIVE states. It also hold one 
 *               status bit per clock input of the domain. 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL                          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP
 *
 * @BRIEF        This register controls the static domain depedencies from 
 *               CAM domain towards 'target' domains. It is relevant only for 
 *               domain having system initiator(s). 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP                          0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_DYNAMICDEP
 *
 * @BRIEF        This register controls the dynamic domain depedencies from 
 *               CAM domain towards 'target' domains. It is relevant only for 
 *               domain having OCP master port(s). 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_DYNAMICDEP                         0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL
 *
 * @BRIEF        This register manages the ISS clocks. 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL                        0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL
 *
 * @BRIEF        This register manages the FDIF clocks. 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL                       0x28ul

    /* 
     * List of register bitfields for component CAM_CM2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_FDIF_GFCLK   
 *
 * @BRIEF        This field indicates the state of the FDIF_GFCLK clock input 
 *               of the domain. 
 *               [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_FDIF_GFCLK BITFIELD(10, 10)
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_FDIF_GFCLK__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_CAM_PHY_CTRL_GCLK   
 *
 * @BRIEF        This field indicates the state of the CAM_PHY_CTRL_GCLK 
 *               clock input of the domain. 
 *               [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_CAM_PHY_CTRL_GCLK BITFIELD(9, 9)
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_CAM_PHY_CTRL_GCLK__POS 9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_ISS_GCLK   
 *
 * @BRIEF        This field indicates the state of the ISS_GCLK clock input 
 *               of the domain. 
 *               [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_ISS_GCLK BITFIELD(8, 8)
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_ISS_GCLK__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL   
 *
 * @BRIEF        Controls the clock state transition of the CAM clock domain. 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL          BITFIELD(1, 0)
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__L3_2_STATDEP   
 *
 * @BRIEF        Static dependency towards L3_2 clock domain - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__L3_2_STATDEP       BITFIELD(6, 6)
#define CAM_CM2__CM_CAM_STATICDEP__L3_2_STATDEP__POS  6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__L3_1_STATDEP   
 *
 * @BRIEF        Static dependency towards L3_1 clock domain - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__L3_1_STATDEP       BITFIELD(5, 5)
#define CAM_CM2__CM_CAM_STATICDEP__L3_1_STATDEP__POS  5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__MEMIF_STATDEP   
 *
 * @BRIEF        Static dependency towards MEMIF clock domain - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__MEMIF_STATDEP      BITFIELD(4, 4)
#define CAM_CM2__CM_CAM_STATICDEP__MEMIF_STATDEP__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__IVAHD_STATDEP   
 *
 * @BRIEF        Static dependency towards IVAHD clock domain - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__IVAHD_STATDEP      BITFIELD(2, 2)
#define CAM_CM2__CM_CAM_STATICDEP__IVAHD_STATDEP__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_DYNAMICDEP__L3_2_DYNDEP   
 *
 * @BRIEF        Dynamic dependency towards L3_2 clock domain - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_DYNAMICDEP__L3_2_DYNDEP       BITFIELD(6, 6)
#define CAM_CM2__CM_CAM_DYNAMICDEP__L3_2_DYNDEP__POS  6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__STBYST   
 *
 * @BRIEF        Module standby status. [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__STBYST           BITFIELD(18, 18)
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__STBYST__POS      18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST   
 *
 * @BRIEF        Module idle status. [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST           BITFIELD(17, 16)
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__POS      16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__OPTFCLKEN_CTRLCLK   
 *
 * @BRIEF        Optional functional clock control for CAM_PHY_CTRL_GCLK 
 *               96Mhz clock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__OPTFCLKEN_CTRLCLK BITFIELD(8, 8)
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__OPTFCLKEN_CTRLCLK__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE   
 *
 * @BRIEF        Control the way mandatory clocks are managed. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE       BITFIELD(1, 0)
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK   
 *
 * @BRIEF        Select the ration of FDIF_FCLK to FUNC_128M_CLK - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK     BITFIELD(25, 24)
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__POS 24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__STBYST   
 *
 * @BRIEF        Module standby status. [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__STBYST          BITFIELD(18, 18)
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__STBYST__POS     18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST   
 *
 * @BRIEF        Module idle status. [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST          BITFIELD(17, 16)
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__POS     16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE   
 *
 * @BRIEF        Control the way mandatory clocks are managed. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE      BITFIELD(1, 0)
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__POS 0

    /* 
     * List of register bitfields values for component CAM_CM2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_FDIF_GFCLK__INACT
 *
 * @BRIEF        Corresponding clock is definitely gated - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_FDIF_GFCLK__INACT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_FDIF_GFCLK__ACT
 *
 * @BRIEF        Corresponding clock is running or gating/ungating transition 
 *               is on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_FDIF_GFCLK__ACT 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_CAM_PHY_CTRL_GCLK__INACT
 *
 * @BRIEF        Corresponding clock is definitely gated - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_CAM_PHY_CTRL_GCLK__INACT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_CAM_PHY_CTRL_GCLK__ACT
 *
 * @BRIEF        Corresponding clock is running or gating/ungating transition 
 *               is on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_CAM_PHY_CTRL_GCLK__ACT 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_ISS_GCLK__INACT
 *
 * @BRIEF        Corresponding clock is definitely gated - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_ISS_GCLK__INACT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_ISS_GCLK__ACT
 *
 * @BRIEF        Corresponding clock is running or gating/ungating transition 
 *               is on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKACTIVITY_ISS_GCLK__ACT 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__NO_SLEEP
 *
 * @BRIEF        NO_SLEEP: Sleep transition cannot be initiated. Wakeup 
 *               transition may however occur. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__NO_SLEEP 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__SW_SLEEP
 *
 * @BRIEF        SW_SLEEP: Start a software forced sleep transition on the 
 *               domain. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__SW_SLEEP 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__SW_WKUP
 *
 * @BRIEF        SW_WKUP: Start a software forced wake-up transition on the 
 *               domain. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__SW_WKUP 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__HW_AUTO
 *
 * @BRIEF        HW_AUTO: Automatic transition is enabled. Sleep and wakeup 
 *               transition are based upon hardware conditions. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_CLKSTCTRL__CLKTRCTRL__HW_AUTO 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__L3_2_STATDEP__ENABLED
 *
 * @BRIEF        Dependency is enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__L3_2_STATDEP__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__L3_1_STATDEP__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__L3_1_STATDEP__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__L3_1_STATDEP__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__L3_1_STATDEP__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__MEMIF_STATDEP__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__MEMIF_STATDEP__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__MEMIF_STATDEP__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__MEMIF_STATDEP__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__IVAHD_STATDEP__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__IVAHD_STATDEP__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_STATICDEP__IVAHD_STATDEP__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_STATICDEP__IVAHD_STATDEP__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_DYNAMICDEP__L3_2_DYNDEP__DISABLED
 *
 * @BRIEF        Dependency is disabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_DYNAMICDEP__L3_2_DYNDEP__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__STBYST__FUNC
 *
 * @BRIEF        Module is functional (not in standby) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__STBYST__FUNC     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__STBYST__STANDBY
 *
 * @BRIEF        Module is in standby - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__STBYST__STANDBY  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__FUNC
 *
 * @BRIEF        Module is fully functional, including OCP - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__FUNC     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__TRANS
 *
 * @BRIEF        Module is performing transition: wakeup, or sleep, or sleep 
 *               abortion - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__TRANS    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__IDLE
 *
 * @BRIEF        Module is in Idle mode (only OCP part). It is functional if 
 *               using separate functional clock - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__IDLE     0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__DISABLE
 *
 * @BRIEF        Module is disabled and cannot be accessed - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__IDLEST__DISABLE  0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__OPTFCLKEN_CTRLCLK__FCLK_DIS
 *
 * @BRIEF        Optional functional clock is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__OPTFCLKEN_CTRLCLK__FCLK_DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__OPTFCLKEN_CTRLCLK__FCLK_EN
 *
 * @BRIEF        Optional functional clock is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__OPTFCLKEN_CTRLCLK__FCLK_EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__DISABLED
 *
 * @BRIEF        Module is disable by SW. Any OCP access to module results in 
 *               an error, except if resulting from a module wakeup 
 *               (asynchronous wakeup). - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__RESERVED_1
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__RESERVED_1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__ENABLE
 *
 * @BRIEF        Module is explicitly enabled. Interface clock (if not used 
 *               for functions) may be gated according to the clock domain 
 *               state. Functional clocks are guarantied to stay present. As 
 *               long as in this configuration, power domain sleep transition 
 *               cannot happen. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__ENABLE 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_ISS_CLKCTRL__MODULEMODE__RESERVED 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__DIV1
 *
 * @BRIEF        FDIF_FCLK is divide by 1 of FUNC_128_CLK - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__DIV1 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__DIV2
 *
 * @BRIEF        FDIF_FCLK is divide by 2 of FUNC_128_CLK - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__DIV2 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__DIV4
 *
 * @BRIEF        FDIF_FCLK is divide by 4 of FUNC_128_CLK - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__DIV4 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__RESERVED
 *
 * @BRIEF        Reserved - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__CLKSEL_FCLK__RESERVED 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__STBYST__FUNC
 *
 * @BRIEF        Module is functional (not in standby) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__STBYST__FUNC    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__STBYST__STANDBY
 *
 * @BRIEF        Module is in standby - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__STBYST__STANDBY 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__FUNC
 *
 * @BRIEF        Module is fully functional, including OCP - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__FUNC    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__TRANS
 *
 * @BRIEF        Module is performing transition: wakeup, or sleep, or sleep 
 *               abortion - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__TRANS   0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__IDLE
 *
 * @BRIEF        Module is in Idle mode (only OCP part). It is functional if 
 *               using separate functional clock - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__IDLE    0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__DISABLE
 *
 * @BRIEF        Module is disabled and cannot be accessed - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__IDLEST__DISABLE 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__DISABLED
 *
 * @BRIEF        Module is disable by SW. Any OCP access to module results in 
 *               an error, except if resulting from a module wakeup 
 *               (asynchronous wakeup). - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__RESERVED_1
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__RESERVED_1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__ENABLE
 *
 * @BRIEF        Module is explicitly enabled. Interface clock (if not used 
 *               for functions) may be gated according to the clock domain 
 *               state. Functional clocks are guarantied to stay present. As 
 *               long as in this configuration, power domain sleep transition 
 *               cannot happen. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__ENABLE 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_CM2__CM_CAM_FDIF_CLKCTRL__MODULEMODE__RESERVED 0x3ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __CAM_CM2_CRED_H 
                                                            */
