/** ==================================================================
 *  @file   cam_prm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   CAM_PRM
 *
 *  @Filename:    cam_prm_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __CAM_PRM_CRED_H
#define __CAM_PRM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance CAM_PRM of component CAM_PRM mapped in MONICA at address 0x4A307000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component CAM_PRM
     *
     */

    /* 
     *  List of bundle arrays for component CAM_PRM
     *
     */

    /* 
     *  List of bundles for component CAM_PRM
     *
     */

    /* 
     * List of registers for component CAM_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL
 *
 * @BRIEF        This register controls the CAM power state to reach upon a 
 *               domain sleep transition 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL                          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST
 *
 * @BRIEF        This register provides a status on the current CAM power 
 *               domain state. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST                            0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_ISS_CONTEXT
 *
 * @BRIEF        This register contains dedicated ISS context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_ISS_CONTEXT                        0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_FDIF_CONTEXT
 *
 * @BRIEF        This register contains dedicated FDIF context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_FDIF_CONTEXT                       0x2Cul

    /* 
     * List of register bitfields for component CAM_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__CAM_MEM_ONSTATE   
 *
 * @BRIEF        CAM_MEM memory state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__CAM_MEM_ONSTATE    BITFIELD(17, 16)
#define CAM_PRM__PM_CAM_PWRSTCTRL__CAM_MEM_ONSTATE__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__LOWPOWERSTATECHANGE   
 *
 * @BRIEF        Power state change request when domain has already performed 
 *               a sleep transition. Allows going into deeper low power state 
 *               without waking up the power domain. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__LOWPOWERSTATECHANGE BITFIELD(4, 4)
#define CAM_PRM__PM_CAM_PWRSTCTRL__LOWPOWERSTATECHANGE__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE   
 *
 * @BRIEF        Power state control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE         BITFIELD(1, 0)
#define CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__INTRANSITION   
 *
 * @BRIEF        Domain transition status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__INTRANSITION         BITFIELD(20, 20)
#define CAM_PRM__PM_CAM_PWRSTST__INTRANSITION__POS    20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST   
 *
 * @BRIEF        CAM_MEM memory state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST      BITFIELD(5, 4)
#define CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__LOGICSTATEST   
 *
 * @BRIEF        Logic state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__LOGICSTATEST         BITFIELD(2, 2)
#define CAM_PRM__PM_CAM_PWRSTST__LOGICSTATEST__POS    2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST   
 *
 * @BRIEF        Current power state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST         BITFIELD(1, 0)
#define CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTMEM_CAM_MEM   
 *
 * @BRIEF        Specify if memory-based context in CAM_MEM memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTMEM_CAM_MEM  BITFIELD(8, 8)
#define CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTMEM_CAM_MEM__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of CAM_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTCONTEXT_DFF  BITFIELD(0, 0)
#define CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTCONTEXT_DFF__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTMEM_CAM_MEM   
 *
 * @BRIEF        Specify if memory-based context in CAM_MEM memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTMEM_CAM_MEM BITFIELD(8, 8)
#define CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTMEM_CAM_MEM__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of CAM_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTCONTEXT_DFF__POS 0

    /* 
     * List of register bitfields values for component CAM_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__CAM_MEM_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__CAM_MEM_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__LOWPOWERSTATECHANGE__DIS
 *
 * @BRIEF        Do not request a low power state change. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__LOWPOWERSTATECHANGE__DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__LOWPOWERSTATECHANGE__EN
 *
 * @BRIEF        Request a low power state change. This bit is automatically 
 *               cleared when the power state is effectively changed or when 
 *               power state is ON. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__LOWPOWERSTATECHANGE__EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__OFF
 *
 * @BRIEF        OFF state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__RESERVED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__INACT
 *
 * @BRIEF        INACTIVE state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__INACT  0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__ON
 *
 * @BRIEF        ON State - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTCTRL__POWERSTATE__ON     0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__INTRANSITION__NO
 *
 * @BRIEF        No on-going transition on power domain - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__INTRANSITION__NO     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__INTRANSITION__ONGOING
 *
 * @BRIEF        Power domain transition is in progress. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__INTRANSITION__ONGOING 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__RESERVED1
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__RESERVED1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__CAM_MEM_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__LOGICSTATEST__OFF
 *
 * @BRIEF        Logic in domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__LOGICSTATEST__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__LOGICSTATEST__ON
 *
 * @BRIEF        Logic in domain is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__LOGICSTATEST__ON     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__OFF
 *
 * @BRIEF        Power domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__RESERVED
 *
 * @BRIEF        Power domain is in RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__RESERVED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__INACTIVE
 *
 * @BRIEF        Power domain is ON-INACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__INACTIVE 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__ON
 *
 * @BRIEF        Power domain is ON-ACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__PM_CAM_PWRSTST__POWERSTATEST__ON     0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTMEM_CAM_MEM__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTMEM_CAM_MEM__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTMEM_CAM_MEM__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTMEM_CAM_MEM__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_ISS_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTMEM_CAM_MEM__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTMEM_CAM_MEM__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTMEM_CAM_MEM__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTMEM_CAM_MEM__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CAM_PRM__RM_CAM_FDIF_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __CAM_PRM_CRED_H 
                                                            */
