/** ==================================================================
 *  @file   ckgen_prm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   CKGEN_PRM
 *
 *  @Filename:    ckgen_prm_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __CKGEN_PRM_CRED_H
#define __CKGEN_PRM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance CKGEN_PRM of component CKGEN_PRM mapped in MONICA at address 0x4A306100
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component CKGEN_PRM
     *
     */

    /* 
     *  List of bundle arrays for component CKGEN_PRM
     *
     */

    /* 
     *  List of bundles for component CKGEN_PRM
     *
     */

    /* 
     * List of registers for component CKGEN_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL
 *
 * @BRIEF        Select the SYS CLK for ABE and DSS subsystems. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL                   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_L4_WKUP_CLKSEL
 *
 * @BRIEF        Control  the functional clock source of L4_WKUP, PRM and 
 *               Smart Reflex functional clock. 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_L4_WKUP_CLKSEL                       0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL
 *
 * @BRIEF        Control the source of the reference clock for DPLL_ABE 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL                   0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL
 *
 * @BRIEF        Software sets the SYS_CLK configuration corresponding to the 
 *               frequency of SYS_CLK. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL                           0x10ul

    /* 
     * List of register bitfields for component CKGEN_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL__CLKSEL   
 *
 * @BRIEF        Selects the divider value - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL__CLKSEL      BITFIELD(0, 0)
#define CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL__CLKSEL__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_L4_WKUP_CLKSEL__CLKSEL   
 *
 * @BRIEF        Select the clock source for L4_WKUP clock - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_L4_WKUP_CLKSEL__CLKSEL          BITFIELD(0, 0)
#define CKGEN_PRM__CM_L4_WKUP_CLKSEL__CLKSEL__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL__CLKSEL   
 *
 * @BRIEF        Select the source for the DPLL_ABE reference clock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL__CLKSEL      BITFIELD(0, 0)
#define CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL__CLKSEL__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL   
 *
 * @BRIEF        System clock input selection. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL          BITFIELD(2, 0)
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__POS     0

    /* 
     * List of register bitfields values for component CKGEN_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL__CLKSEL__SYSCLK_DIV_1
 *
 * @BRIEF        Select SYS_CLK divided by 1 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL__CLKSEL__SYSCLK_DIV_1 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL__CLKSEL__SYSCLK_DIV_2
 *
 * @BRIEF        Select SYS_CLK divided by 2 
 *               Must be used for SYS_CLK>26MHz - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_ABE_DSS_SYS_CLKSEL__CLKSEL__SYSCLK_DIV_2 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_L4_WKUP_CLKSEL__CLKSEL__SEL_SYS_CLK
 *
 * @BRIEF        Selects SYS_CLK - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_L4_WKUP_CLKSEL__CLKSEL__SEL_SYS_CLK 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_L4_WKUP_CLKSEL__CLKSEL__SEL_ABE_X1_LP_CLK
 *
 * @BRIEF        Selects ABE_X1_LP_CLK - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_L4_WKUP_CLKSEL__CLKSEL__SEL_ABE_X1_LP_CLK 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL__CLKSEL__SEL_SYS_CLK
 *
 * @BRIEF        Selects SYS_CLK - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL__CLKSEL__SEL_SYS_CLK 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL__CLKSEL__SEL_SYS_32K
 *
 * @BRIEF        Selects SYS_32K - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_ABE_PLL_REF_CLKSEL__CLKSEL__SEL_SYS_32K 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__UNSET
 *
 * @BRIEF        Uninitialized - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__UNSET   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__12_MHZ
 *
 * @BRIEF        Input clock is 12 MHz - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__12_MHZ  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__13_MHZ
 *
 * @BRIEF        Input clock is 13 MHz - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__13_MHZ  0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__16_8_MHZ
 *
 * @BRIEF        Input clock is 16.8 MHz - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__16_8_MHZ 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__19_2_MHZ
 *
 * @BRIEF        Input clock is 19.2 MHz - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__19_2_MHZ 0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__26_MHZ
 *
 * @BRIEF        Input clock is 26 MHz - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__26_MHZ  0x5ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__27_MHZ
 *
 * @BRIEF        Input clock is 27 MHz - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__27_MHZ  0x6ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__38_4_MHZ
 *
 * @BRIEF        Input clock is 38.4 MHz - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CKGEN_PRM__CM_SYS_CLKSEL__SYS_CLKSEL__38_4_MHZ 0x7ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __CKGEN_PRM_CRED_H 
                                                            */
