/** ==================================================================
 *  @file   csi2_receiver_regs2_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   CSI2_RECEIVER_REGS2
 *
 *  @Filename:    csi2_receiver_regs2_cred.h
 *
 *  @Description: CSI2 RECEIVER module 
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __CSI2_RECEIVER_REGS2_CRED_H
#define __CSI2_RECEIVER_REGS2_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance CSI2_RECEIVER_A__CSI2_RECEIVER_REGS2 of component CSI2_RECEIVER_REGS2 mapped in MONICA at address 0x550411C0
     * Instance CSI2_RECEIVER_B__CSI2_RECEIVER_REGS2 of component CSI2_RECEIVER_REGS2 mapped in MONICA at address 0x550415C0
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component CSI2_RECEIVER_REGS2
     *
     */

    /* 
     *  List of bundle arrays for component CSI2_RECEIVER_REGS2
     *
     */
                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__TRANSCODE
 *
 * @BRIEF        Bundle description is not available
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__TRANSCODE                     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__TRANSCODE__ELSIZE
 *
 * @BRIEF        TRANSCODE bundle array element size in Bytes
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__TRANSCODE__ELSIZE             0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__TRANSCODE__NELEMS
 *
 * @BRIEF        TRANSCODE bundle array number of elements
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__TRANSCODE__NELEMS             8

    /* 
     *  List of bundles for component CSI2_RECEIVER_REGS2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH__OFFSET
 *
 * @BRIEF        Register CSI2_CTX_TRANSCODEH offset in bundle TRANSCODE 
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH__OFFSET   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV__OFFSET
 *
 * @BRIEF        Register CSI2_CTX_TRANSCODEV offset in bundle TRANSCODE 
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV__OFFSET   0x4ul

    /* 
     * List of registers for component CSI2_RECEIVER_REGS2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH
 *
 * @BRIEF        Transcode configuration register: defines horizontal frame 
 *               cropping 
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH           0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV
 *
 * @BRIEF        Transcode configuration register: defines vertical frame 
 *               cropping 
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV           0x4ul

    /* 
     * List of register bitfields for component CSI2_RECEIVER_REGS2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH__HCOUNT   
 *
 * @BRIEF        Pixels to output per line when the values is between 1 and 
 *               8191. 
 *               Pixels HSKIP-WIDTH pixels are output when HCOUNT=0.  
 *               WIDTH corresponds to the image width provided by the sensor. 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH__HCOUNT BITFIELD(28, 16)
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH__HCOUNT__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH__HSKIP   
 *
 * @BRIEF        Pixel to skip horizontally. 
 *               Valid values: 0-8191 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH__HSKIP BITFIELD(12, 0)
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEH__HSKIP__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV__VCOUNT   
 *
 * @BRIEF        Lines to output per frame when the values is between 1 and 
 *               8191. 
 *               Pixels VSKIP-HEIGHT pixels are output when VCOUNT=0.  
 *               HEIGHT corresponds to the image height provided by the 
 *               sensor. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV__VCOUNT BITFIELD(28, 16)
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV__VCOUNT__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV__VSKIP   
 *
 * @BRIEF        Pixel to skip vertically 
 *               Valid values: 0-8191 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV__VSKIP BITFIELD(12, 0)
#define CSI2_RECEIVER_REGS2__CSI2_CTX_TRANSCODEV__VSKIP__POS 0

    /* 
     * List of register bitfields values for component CSI2_RECEIVER_REGS2
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __CSI2_RECEIVER_REGS2_CRED_H 
                                                            */
