/** ==================================================================
 *  @file   cstpiu_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   CSTPIU
 *
 *  @Filename:    cstpiu_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __CSTPIU_CRED_H
#define __CSTPIU_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance I_CSTPIU of component CSTPIU mapped in MONICA at address 0x54163000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component CSTPIU
     *
     */

    /* 
     *  List of bundle arrays for component CSTPIU
     *
     */

    /* 
     *  List of bundles for component CSTPIU
     *
     */

    /* 
     * List of registers for component CSTPIU
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPPORTSIZE
 *
 * @BRIEF        Supported port sizes 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPPORTSIZE                         0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CURPORTSIZE
 *
 * @BRIEF        Current port size 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CURPORTSIZE                         0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG
 *
 * @BRIEF        Supported trigger modes 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG                             0x100ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TRIGCNT
 *
 * @BRIEF        Trigger counter value 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TRIGCNT                             0x104ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TRIGMUL
 *
 * @BRIEF        Trigger multiplier 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TRIGMUL                             0x108ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTEST
 *
 * @BRIEF        Supported test pattern/modes 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTEST                             0x200ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CURTEST
 *
 * @BRIEF        Current test pattern/mode 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CURTEST                             0x204ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TESTREP
 *
 * @BRIEF        Test pattern repeat counter 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TESTREP                             0x208ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FORMSTAT
 *
 * @BRIEF        Formatter and flush status 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FORMSTAT                            0x300ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR
 *
 * @BRIEF        Formatter and flush control 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR                                0x304ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FORMSYNC
 *
 * @BRIEF        Formatter synchronization counter 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FORMSYNC                            0x308ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_EXTCTLIN
 *
 * @BRIEF        EXTCTL IN Port 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_EXTCTLIN                            0x400ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_EXTCTLOUT
 *
 * @BRIEF        EXTCTL OUT Port 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_EXTCTLOUT                           0x404ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITTRFLINACK
 *
 * @BRIEF        Integration Register 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITTRFLINACK                         0xEE4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITTRFLIN
 *
 * @BRIEF        Integration Register 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITTRFLIN                            0xEE8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBDATA0
 *
 * @BRIEF        Integration Register 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBDATA0                          0xEECul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR2
 *
 * @BRIEF        Integration Register 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR2                           0xEF0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR1
 *
 * @BRIEF        Integration Register 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR1                           0xEF4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR0
 *
 * @BRIEF        Integration Register 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR0                           0xEF8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITCTRL
 *
 * @BRIEF        Integration Mode Control Register 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITCTRL                              0xF00ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CLAIMSET
 *
 * @BRIEF        Claim Tag Set 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CLAIMSET                            0xFA0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CLAIMCLR
 *
 * @BRIEF        Claim Tag Clear 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CLAIMCLR                            0xFA4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_LOCKACCESS
 *
 * @BRIEF        Lock Access 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_LOCKACCESS                          0xFB0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_LOCKSTATUS
 *
 * @BRIEF        Lock Status 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_LOCKSTATUS                          0xFB4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_AUTHSTATUS
 *
 * @BRIEF        Authentification status 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_AUTHSTATUS                          0xFB8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_DEVID
 *
 * @BRIEF        Device ID 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_DEVID                               0xFC8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_DEVTYPE
 *
 * @BRIEF        Device type identifier 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_DEVTYPE                             0xFCCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID4
 *
 * @BRIEF        Peripheral ID4 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID4                           0xFD0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID0
 *
 * @BRIEF        Peripheral ID0 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID0                           0xFE0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID1
 *
 * @BRIEF        Peripheral ID1 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID1                           0xFE4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID2
 *
 * @BRIEF        Peripheral ID2 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID2                           0xFE8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID3
 *
 * @BRIEF        Peripheral ID3 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID3                           0xFECul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID0
 *
 * @BRIEF        Component ID0 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID0                           0xFF0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID1
 *
 * @BRIEF        Component ID1 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID1                           0xFF4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID2
 *
 * @BRIEF        Component ID2 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID2                           0xFF8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID3
 *
 * @BRIEF        Component ID3 
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID3                           0xFFCul

    /* 
     * List of register bitfields for component CSTPIU
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPPORTSIZE__CSTPIU_SUPPORTSIZE_VAL   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPPORTSIZE__CSTPIU_SUPPORTSIZE_VAL BITFIELD(31, 0)
#define CSTPIU__CSTPIU_SUPPORTSIZE__CSTPIU_SUPPORTSIZE_VAL__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CURPORTSIZE__CSTPIU_CURPORTSIZE_VAL   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CURPORTSIZE__CSTPIU_CURPORTSIZE_VAL BITFIELD(31, 0)
#define CSTPIU__CSTPIU_CURPORTSIZE__CSTPIU_CURPORTSIZE_VAL__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG__TRGRUN   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG__TRGRUN                BITFIELD(17, 17)
#define CSTPIU__CSTPIU_SUPTRIG__TRGRUN__POS           17

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG__TRIGGERED   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG__TRIGGERED             BITFIELD(16, 16)
#define CSTPIU__CSTPIU_SUPTRIG__TRIGGERED__POS        16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG__TCOUNT8   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG__TCOUNT8               BITFIELD(8, 8)
#define CSTPIU__CSTPIU_SUPTRIG__TCOUNT8__POS          8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG__MULT64K   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG__MULT64K               BITFIELD(4, 4)
#define CSTPIU__CSTPIU_SUPTRIG__MULT64K__POS          4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG__MULT256   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG__MULT256               BITFIELD(3, 3)
#define CSTPIU__CSTPIU_SUPTRIG__MULT256__POS          3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG__MULT16   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG__MULT16                BITFIELD(2, 2)
#define CSTPIU__CSTPIU_SUPTRIG__MULT16__POS           2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG__MULT4   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG__MULT4                 BITFIELD(1, 1)
#define CSTPIU__CSTPIU_SUPTRIG__MULT4__POS            1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTRIG__MULT2   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTRIG__MULT2                 BITFIELD(0, 0)
#define CSTPIU__CSTPIU_SUPTRIG__MULT2__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TRIGCNT__TRIGCOUNT   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TRIGCNT__TRIGCOUNT             BITFIELD(7, 0)
#define CSTPIU__CSTPIU_TRIGCNT__TRIGCOUNT__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TRIGMUL__MULT64K   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TRIGMUL__MULT64K               BITFIELD(4, 4)
#define CSTPIU__CSTPIU_TRIGMUL__MULT64K__POS          4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TRIGMUL__MULT256   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TRIGMUL__MULT256               BITFIELD(3, 3)
#define CSTPIU__CSTPIU_TRIGMUL__MULT256__POS          3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TRIGMUL__MULT16   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TRIGMUL__MULT16                BITFIELD(2, 2)
#define CSTPIU__CSTPIU_TRIGMUL__MULT16__POS           2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TRIGMUL__MULT4   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TRIGMUL__MULT4                 BITFIELD(1, 1)
#define CSTPIU__CSTPIU_TRIGMUL__MULT4__POS            1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TRIGMUL__MULT2   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TRIGMUL__MULT2                 BITFIELD(0, 0)
#define CSTPIU__CSTPIU_TRIGMUL__MULT2__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTEST__PCONTEN   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTEST__PCONTEN               BITFIELD(17, 17)
#define CSTPIU__CSTPIU_SUPTEST__PCONTEN__POS          17

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTEST__PTIMEEN   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTEST__PTIMEEN               BITFIELD(16, 16)
#define CSTPIU__CSTPIU_SUPTEST__PTIMEEN__POS          16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTEST__PATF0   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTEST__PATF0                 BITFIELD(3, 3)
#define CSTPIU__CSTPIU_SUPTEST__PATF0__POS            3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTEST__PATA5   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTEST__PATA5                 BITFIELD(2, 2)
#define CSTPIU__CSTPIU_SUPTEST__PATA5__POS            2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTEST__PATW1   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTEST__PATW1                 BITFIELD(1, 1)
#define CSTPIU__CSTPIU_SUPTEST__PATW1__POS            1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_SUPTEST__PATW0   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_SUPTEST__PATW0                 BITFIELD(0, 0)
#define CSTPIU__CSTPIU_SUPTEST__PATW0__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CURTEST__MODE_TEST   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CURTEST__MODE_TEST             BITFIELD(17, 16)
#define CSTPIU__CSTPIU_CURTEST__MODE_TEST__POS        16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CURTEST__PATTERN_TEST   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CURTEST__PATTERN_TEST          BITFIELD(3, 0)
#define CSTPIU__CSTPIU_CURTEST__PATTERN_TEST__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_TESTREP__PATTCOUNT   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_TESTREP__PATTCOUNT             BITFIELD(7, 0)
#define CSTPIU__CSTPIU_TESTREP__PATTCOUNT__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FORMSTAT__TCPRESENT   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FORMSTAT__TCPRESENT            BITFIELD(2, 2)
#define CSTPIU__CSTPIU_FORMSTAT__TCPRESENT__POS       2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FORMSTAT__FTSTOPPED   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FORMSTAT__FTSTOPPED            BITFIELD(1, 1)
#define CSTPIU__CSTPIU_FORMSTAT__FTSTOPPED__POS       1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FORMSTAT__FLINPROG   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FORMSTAT__FLINPROG             BITFIELD(0, 0)
#define CSTPIU__CSTPIU_FORMSTAT__FLINPROG__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__STOPTRIG   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__STOPTRIG                 BITFIELD(13, 13)
#define CSTPIU__CSTPIU_FFCR__STOPTRIG__POS            13

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__STOPFL   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__STOPFL                   BITFIELD(12, 12)
#define CSTPIU__CSTPIU_FFCR__STOPFL__POS              12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__TRIGFL   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__TRIGFL                   BITFIELD(10, 10)
#define CSTPIU__CSTPIU_FFCR__TRIGFL__POS              10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__TRIGEVT   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__TRIGEVT                  BITFIELD(9, 9)
#define CSTPIU__CSTPIU_FFCR__TRIGEVT__POS             9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__TRIGIN   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__TRIGIN                   BITFIELD(8, 8)
#define CSTPIU__CSTPIU_FFCR__TRIGIN__POS              8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__FONMAN   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__FONMAN                   BITFIELD(6, 6)
#define CSTPIU__CSTPIU_FFCR__FONMAN__POS              6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__FONTRIG   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__FONTRIG                  BITFIELD(5, 5)
#define CSTPIU__CSTPIU_FFCR__FONTRIG__POS             5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__FONFLIN   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__FONFLIN                  BITFIELD(4, 4)
#define CSTPIU__CSTPIU_FFCR__FONFLIN__POS             4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__ENFCONT   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__ENFCONT                  BITFIELD(1, 1)
#define CSTPIU__CSTPIU_FFCR__ENFCONT__POS             1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FFCR__ENFTC   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FFCR__ENFTC                    BITFIELD(0, 0)
#define CSTPIU__CSTPIU_FFCR__ENFTC__POS               0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_FORMSYNC__CYCCOUNT   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_FORMSYNC__CYCCOUNT             BITFIELD(11, 0)
#define CSTPIU__CSTPIU_FORMSYNC__CYCCOUNT__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_EXTCTLIN__EXTCTL_IN   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_EXTCTLIN__EXTCTL_IN            BITFIELD(7, 0)
#define CSTPIU__CSTPIU_EXTCTLIN__EXTCTL_IN__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_EXTCTLOUT__EXTCTL_OUT   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_EXTCTLOUT__EXTCTL_OUT          BITFIELD(7, 0)
#define CSTPIU__CSTPIU_EXTCTLOUT__EXTCTL_OUT__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITTRFLINACK__FLUSHINACK   
 *
 * @BRIEF        Bitfield description is not available - (WO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITTRFLINACK__FLUSHINACK        BITFIELD(1, 1)
#define CSTPIU__CSTPIU_ITTRFLINACK__FLUSHINACK__POS   1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITTRFLINACK__TRIGINACK   
 *
 * @BRIEF        Bitfield description is not available - (WO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITTRFLINACK__TRIGINACK         BITFIELD(0, 0)
#define CSTPIU__CSTPIU_ITTRFLINACK__TRIGINACK__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITTRFLIN__FLUSHIN   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITTRFLIN__FLUSHIN              BITFIELD(1, 1)
#define CSTPIU__CSTPIU_ITTRFLIN__FLUSHIN__POS         1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITTRFLIN__TRIGIN   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITTRFLIN__TRIGIN               BITFIELD(0, 0)
#define CSTPIU__CSTPIU_ITTRFLIN__TRIGIN__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBDATA0__ATDATA31   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA31           BITFIELD(4, 4)
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA31__POS      4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBDATA0__ATDATA23   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA23           BITFIELD(3, 3)
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA23__POS      3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBDATA0__ATDATA15   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA15           BITFIELD(2, 2)
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA15__POS      2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBDATA0__ATDATA7   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA7            BITFIELD(1, 1)
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA7__POS       1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBDATA0__ATDATA0   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA0            BITFIELD(0, 0)
#define CSTPIU__CSTPIU_ITATBDATA0__ATDATA0__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR2__AFVALID   
 *
 * @BRIEF        Bitfield description is not available - (WO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR2__AFVALID             BITFIELD(1, 1)
#define CSTPIU__CSTPIU_ITATBCTR2__AFVALID__POS        1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR2__ATREADY   
 *
 * @BRIEF        Bitfield description is not available - (WO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR2__ATREADY             BITFIELD(0, 0)
#define CSTPIU__CSTPIU_ITATBCTR2__ATREADY__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR1__ATID   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR1__ATID                BITFIELD(6, 0)
#define CSTPIU__CSTPIU_ITATBCTR1__ATID__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR0__ATBYTES   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR0__ATBYTES             BITFIELD(9, 8)
#define CSTPIU__CSTPIU_ITATBCTR0__ATBYTES__POS        8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR0__AFREADYS   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR0__AFREADYS            BITFIELD(1, 1)
#define CSTPIU__CSTPIU_ITATBCTR0__AFREADYS__POS       1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITATBCTR0__ATVALIDS   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITATBCTR0__ATVALIDS            BITFIELD(0, 0)
#define CSTPIU__CSTPIU_ITATBCTR0__ATVALIDS__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_ITCTRL__ITCTRL   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_ITCTRL__ITCTRL                 BITFIELD(0, 0)
#define CSTPIU__CSTPIU_ITCTRL__ITCTRL__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CLAIMSET__CLAIMTAGSET   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CLAIMSET__CLAIMTAGSET          BITFIELD(3, 0)
#define CSTPIU__CSTPIU_CLAIMSET__CLAIMTAGSET__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_CLAIMCLR__CLAIMTAGCLEAR   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_CLAIMCLR__CLAIMTAGCLEAR        BITFIELD(3, 0)
#define CSTPIU__CSTPIU_CLAIMCLR__CLAIMTAGCLEAR__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_LOCKACCESS__WRITEACCESSCODE   
 *
 * @BRIEF        Bitfield description is not available - (WO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_LOCKACCESS__WRITEACCESSCODE    BITFIELD(31, 0)
#define CSTPIU__CSTPIU_LOCKACCESS__WRITEACCESSCODE__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_LOCKSTATUS__EIGHT_BIT   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_LOCKSTATUS__EIGHT_BIT          BITFIELD(2, 2)
#define CSTPIU__CSTPIU_LOCKSTATUS__EIGHT_BIT__POS     2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_LOCKSTATUS__STATUS   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_LOCKSTATUS__STATUS             BITFIELD(1, 1)
#define CSTPIU__CSTPIU_LOCKSTATUS__STATUS__POS        1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_LOCKSTATUS__IMP   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_LOCKSTATUS__IMP                BITFIELD(0, 0)
#define CSTPIU__CSTPIU_LOCKSTATUS__IMP__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_AUTHSTATUS__SECURE_NONINVASIVE_DEBUG   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_AUTHSTATUS__SECURE_NONINVASIVE_DEBUG BITFIELD(7, 6)
#define CSTPIU__CSTPIU_AUTHSTATUS__SECURE_NONINVASIVE_DEBUG__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_AUTHSTATUS__SECURE_INVASIVE_DEBUG   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_AUTHSTATUS__SECURE_INVASIVE_DEBUG BITFIELD(5, 4)
#define CSTPIU__CSTPIU_AUTHSTATUS__SECURE_INVASIVE_DEBUG__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_AUTHSTATUS__NONSECURE_NONINVASIVE_DEBUG   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_AUTHSTATUS__NONSECURE_NONINVASIVE_DEBUG BITFIELD(3, 2)
#define CSTPIU__CSTPIU_AUTHSTATUS__NONSECURE_NONINVASIVE_DEBUG__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_AUTHSTATUS__NONSECURE_INVASIVE_DEBUG   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_AUTHSTATUS__NONSECURE_INVASIVE_DEBUG BITFIELD(1, 0)
#define CSTPIU__CSTPIU_AUTHSTATUS__NONSECURE_INVASIVE_DEBUG__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_DEVID__DEVICEID   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_DEVID__DEVICEID                BITFIELD(31, 0)
#define CSTPIU__CSTPIU_DEVID__DEVICEID__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_DEVTYPE__SUB_TYPE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_DEVTYPE__SUB_TYPE              BITFIELD(7, 4)
#define CSTPIU__CSTPIU_DEVTYPE__SUB_TYPE__POS         4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_DEVTYPE__MAIN_TYPE_CLASS   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_DEVTYPE__MAIN_TYPE_CLASS       BITFIELD(3, 0)
#define CSTPIU__CSTPIU_DEVTYPE__MAIN_TYPE_CLASS__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID4__FOURKB_COUNT   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID4__FOURKB_COUNT        BITFIELD(7, 4)
#define CSTPIU__CSTPIU_PERIPHID4__FOURKB_COUNT__POS   4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID4__JEP106_CONTINUATION_CODE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID4__JEP106_CONTINUATION_CODE BITFIELD(3, 0)
#define CSTPIU__CSTPIU_PERIPHID4__JEP106_CONTINUATION_CODE__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID0__PART_NUMBER_0   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID0__PART_NUMBER_0       BITFIELD(7, 0)
#define CSTPIU__CSTPIU_PERIPHID0__PART_NUMBER_0__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID1__JEP106_IDENTITY_CODE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID1__JEP106_IDENTITY_CODE BITFIELD(7, 4)
#define CSTPIU__CSTPIU_PERIPHID1__JEP106_IDENTITY_CODE__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID1__PART_NUMBER_1   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID1__PART_NUMBER_1       BITFIELD(3, 0)
#define CSTPIU__CSTPIU_PERIPHID1__PART_NUMBER_1__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID2__REVISION   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID2__REVISION            BITFIELD(7, 4)
#define CSTPIU__CSTPIU_PERIPHID2__REVISION__POS       4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID2__JEP106_ENABLE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID2__JEP106_ENABLE       BITFIELD(3, 3)
#define CSTPIU__CSTPIU_PERIPHID2__JEP106_ENABLE__POS  3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID2__JEP106_IDENTITY   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID2__JEP106_IDENTITY     BITFIELD(2, 0)
#define CSTPIU__CSTPIU_PERIPHID2__JEP106_IDENTITY__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID3__REVAND   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID3__REVAND              BITFIELD(7, 4)
#define CSTPIU__CSTPIU_PERIPHID3__REVAND__POS         4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_PERIPHID3__CUSTOMER_MODIFIED   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_PERIPHID3__CUSTOMER_MODIFIED   BITFIELD(3, 0)
#define CSTPIU__CSTPIU_PERIPHID3__CUSTOMER_MODIFIED__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID0__PREAMBLE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID0__PREAMBLE            BITFIELD(7, 0)
#define CSTPIU__CSTPIU_COMPONID0__PREAMBLE__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID1__COMPONENT_CLASS   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID1__COMPONENT_CLASS     BITFIELD(7, 4)
#define CSTPIU__CSTPIU_COMPONID1__COMPONENT_CLASS__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID1__PREAMBLE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID1__PREAMBLE            BITFIELD(3, 0)
#define CSTPIU__CSTPIU_COMPONID1__PREAMBLE__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID2__PREAMBLE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID2__PREAMBLE            BITFIELD(7, 0)
#define CSTPIU__CSTPIU_COMPONID2__PREAMBLE__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   CSTPIU__CSTPIU_COMPONID3__PREAMBLE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define CSTPIU__CSTPIU_COMPONID3__PREAMBLE            BITFIELD(7, 0)
#define CSTPIU__CSTPIU_COMPONID3__PREAMBLE__POS       0

    /* 
     * List of register bitfields values for component CSTPIU
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __CSTPIU_CRED_H 
                                                            */
