/** ==================================================================
 *  @file   dss_prm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   DSS_PRM
 *
 *  @Filename:    dss_prm_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __DSS_PRM_CRED_H
#define __DSS_PRM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance DSS_PRM of component DSS_PRM mapped in MONICA at address 0x4A307100
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component DSS_PRM
     *
     */

    /* 
     *  List of bundle arrays for component DSS_PRM
     *
     */

    /* 
     *  List of bundles for component DSS_PRM
     *
     */

    /* 
     * List of registers for component DSS_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL
 *
 * @BRIEF        This register controls the DSS power state to reach upon a 
 *               domain sleep transition 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL                          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST
 *
 * @BRIEF        This register provides a status on the current DSS power 
 *               domain state. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST                            0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP
 *
 * @BRIEF        This register controls wakeup dependency based on DSS 
 *               service requests. 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP                          0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT
 *
 * @BRIEF        This register contains dedicated DSS context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT                        0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DEISS_CONTEXT
 *
 * @BRIEF        This register contains dedicated DEISS context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DEISS_CONTEXT                      0x2Cul

    /* 
     * List of register bitfields for component DSS_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_ONSTATE   
 *
 * @BRIEF        DSS_MEM state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_ONSTATE    BITFIELD(17, 16)
#define DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_ONSTATE__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_RETSTATE   
 *
 * @BRIEF        DSS_MEM state when domain is RETENTION. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_RETSTATE   BITFIELD(8, 8)
#define DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_RETSTATE__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__LOWPOWERSTATECHANGE   
 *
 * @BRIEF        Power state change request when domain has already performed 
 *               a sleep transition. Allows going into deeper low power state 
 *               without waking up the power domain. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__LOWPOWERSTATECHANGE BITFIELD(4, 4)
#define DSS_PRM__PM_DSS_PWRSTCTRL__LOWPOWERSTATECHANGE__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__LOGICRETSTATE   
 *
 * @BRIEF        Logic state when power domain is RETENTION - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__LOGICRETSTATE      BITFIELD(2, 2)
#define DSS_PRM__PM_DSS_PWRSTCTRL__LOGICRETSTATE__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE   
 *
 * @BRIEF        Power state control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE         BITFIELD(1, 0)
#define DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__INTRANSITION   
 *
 * @BRIEF        Domain transition status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__INTRANSITION         BITFIELD(20, 20)
#define DSS_PRM__PM_DSS_PWRSTST__INTRANSITION__POS    20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST   
 *
 * @BRIEF        DSS_MEM state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST      BITFIELD(5, 4)
#define DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__LOGICSTATEST   
 *
 * @BRIEF        Logic state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__LOGICSTATEST         BITFIELD(2, 2)
#define DSS_PRM__PM_DSS_PWRSTST__LOGICSTATEST__POS    2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST   
 *
 * @BRIEF        Current power state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST         BITFIELD(1, 0)
#define DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIDMA_SDMA   
 *
 * @BRIEF        Wakeup dependency from HDMI module (SWakeup_HDMI_dma signal) 
 *               towards SDMA + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIDMA_SDMA BITFIELD(19, 19)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIDMA_SDMA__POS 19

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_TESLA   
 *
 * @BRIEF        Wakeup dependency from HDMI module (SWakeup_HDMI_irq signal) 
 *               towards TESLA + L3_1 + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_TESLA BITFIELD(14, 14)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_TESLA__POS 14

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_DUCATI   
 *
 * @BRIEF        Wakeup dependency from HDMI module (SWakeup_HDMI_irq signal) 
 *               towards DUCATI + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_DUCATI BITFIELD(13, 13)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_DUCATI__POS 13

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_MPU   
 *
 * @BRIEF        Wakeup dependency from HDMI module (SWakeup_HDMI_irq signal) 
 *               towards MPU + L3_1 + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_MPU BITFIELD(12, 12)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_MPU__POS 12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_SDMA   
 *
 * @BRIEF        Wakeup dependency from DSI2 module (SWakeup_DSI2 signal) 
 *               towards SDMA + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_SDMA  BITFIELD(11, 11)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_SDMA__POS 11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_TESLA   
 *
 * @BRIEF        Wakeup dependency from DSI2 module (SWakeup_DSI2 signal) 
 *               towards TESLA + L3_1 + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_TESLA BITFIELD(10, 10)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_TESLA__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_DUCATI   
 *
 * @BRIEF        Wakeup dependency from DSI2 module (SWakeup_DSI2 signal) 
 *               towards DUCATI + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_DUCATI BITFIELD(9, 9)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_DUCATI__POS 9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_MPU   
 *
 * @BRIEF        Wakeup dependency from DSI2 module (SWakeup_DSI2 signal) 
 *               towards MPU + L3_1 + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_MPU   BITFIELD(8, 8)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_MPU__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_SDMA   
 *
 * @BRIEF        Wakeup dependency from DSI1 module (SWakeup_DSI1 signal) 
 *               towards SDMA + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_SDMA  BITFIELD(7, 7)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_SDMA__POS 7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_TESLA   
 *
 * @BRIEF        Wakeup dependency from DSI1 module (SWakeup_DSI1 signal) 
 *               towards TESLA + L3_1 + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_TESLA BITFIELD(6, 6)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_TESLA__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_DUCATI   
 *
 * @BRIEF        Wakeup dependency from DSI1 module (SWakeup_DSI1 signal) 
 *               towards DUCATI + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_DUCATI BITFIELD(5, 5)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_DUCATI__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_MPU   
 *
 * @BRIEF        Wakeup dependency from DSI1 module (SWakeup_DSI1 signal) 
 *               towards MPU + L3_1 + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_MPU   BITFIELD(4, 4)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_MPU__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_SDMA   
 *
 * @BRIEF        Wakeup dependency from DISPC module (SWakeup_DISPC signal) 
 *               towards SDMA + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_SDMA BITFIELD(3, 3)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_SDMA__POS 3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_TESLA   
 *
 * @BRIEF        Wakeup dependency from DISPC module (SWakeup_DISPC signal) 
 *               towards TESLA + L3_1 + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_TESLA BITFIELD(2, 2)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_TESLA__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_DUCATI   
 *
 * @BRIEF        Wakeup dependency from DISPC module (SWakeup_DISPC signal) 
 *               towards DUCATI + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_DUCATI BITFIELD(1, 1)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_DUCATI__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_MPU   
 *
 * @BRIEF        Wakeup dependency from DISPC module (SWakeup_DISPC signal) 
 *               towards MPU + L3_1 + L3_2 domains - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_MPU  BITFIELD(0, 0)
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_MPU__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTMEM_DSS_MEM   
 *
 * @BRIEF        Specify if memory-based context in DSS_MEM memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTMEM_DSS_MEM  BITFIELD(8, 8)
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTMEM_DSS_MEM__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_RFF   
 *
 * @BRIEF        Specify if RFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of DSS_RET_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_RFF  BITFIELD(1, 1)
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_RFF__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of DSS_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_DFF  BITFIELD(0, 0)
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_DFF__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTMEM_DSS_MEM   
 *
 * @BRIEF        Specify if memory-based context in DSS_MEM memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTMEM_DSS_MEM BITFIELD(8, 8)
#define DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTMEM_DSS_MEM__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of DSS_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTCONTEXT_DFF__POS 0

    /* 
     * List of register bitfields values for component DSS_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_RETSTATE__MEM_OFF
 *
 * @BRIEF        Memory bank is off when the domain is in the RETENTION 
 *               state. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__DSS_MEM_RETSTATE__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__LOWPOWERSTATECHANGE__DIS
 *
 * @BRIEF        Do not request a low power state change. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__LOWPOWERSTATECHANGE__DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__LOWPOWERSTATECHANGE__EN
 *
 * @BRIEF        Request a low power state change. This bit is automatically 
 *               cleared when the power state is effectively changed or when 
 *               power state is ON. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__LOWPOWERSTATECHANGE__EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__LOGICRETSTATE__LOGIC_OFF
 *
 * @BRIEF        Whole logic is off when the domain is in RETENTION state. - 
 *               (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__LOGICRETSTATE__LOGIC_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__OFF
 *
 * @BRIEF        OFF state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__RET
 *
 * @BRIEF        RETENTION state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__RET    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__INACT
 *
 * @BRIEF        INACTIVE state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__INACT  0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__ON
 *
 * @BRIEF        ON State - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTCTRL__POWERSTATE__ON     0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__INTRANSITION__NO
 *
 * @BRIEF        No on-going transition on power domain - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__INTRANSITION__NO     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__INTRANSITION__ONGOING
 *
 * @BRIEF        Power domain transition is in progress. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__INTRANSITION__ONGOING 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__RESERVED1
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__RESERVED1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__DSS_MEM_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__LOGICSTATEST__OFF
 *
 * @BRIEF        Logic in domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__LOGICSTATEST__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__LOGICSTATEST__ON
 *
 * @BRIEF        Logic in domain is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__LOGICSTATEST__ON     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__OFF
 *
 * @BRIEF        Power domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__RET
 *
 * @BRIEF        Power domain is in RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__RET    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__INACTIVE
 *
 * @BRIEF        Power domain is ON-INACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__INACTIVE 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__ON
 *
 * @BRIEF        Power domain is ON-ACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_PWRSTST__POWERSTATEST__ON     0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIDMA_SDMA__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIDMA_SDMA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIDMA_SDMA__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIDMA_SDMA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_TESLA__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_TESLA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_TESLA__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_TESLA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_DUCATI__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_DUCATI__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_DUCATI__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_DUCATI__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_MPU__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_MPU__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_MPU__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_HDMIIRQ_MPU__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_SDMA__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_SDMA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_SDMA__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_SDMA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_TESLA__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_TESLA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_TESLA__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_TESLA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_DUCATI__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_DUCATI__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_DUCATI__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_DUCATI__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_MPU__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_MPU__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_MPU__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI2_MPU__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_SDMA__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_SDMA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_SDMA__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_SDMA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_TESLA__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_TESLA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_TESLA__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_TESLA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_DUCATI__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_DUCATI__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_DUCATI__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_DUCATI__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_MPU__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_MPU__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_MPU__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DSI1_MPU__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_SDMA__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_SDMA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_SDMA__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_SDMA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_TESLA__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_TESLA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_TESLA__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_TESLA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_DUCATI__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_DUCATI__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_DUCATI__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_DUCATI__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_MPU__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_MPU__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_MPU__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__PM_DSS_DSS_WKDEP__WKUPDEP_DISPC_MPU__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTMEM_DSS_MEM__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTMEM_DSS_MEM__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTMEM_DSS_MEM__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTMEM_DSS_MEM__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_RFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_RFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_RFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_RFF__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DSS_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTMEM_DSS_MEM__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTMEM_DSS_MEM__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTMEM_DSS_MEM__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTMEM_DSS_MEM__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_PRM__RM_DSS_DEISS_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __DSS_PRM_CRED_H 
                                                            */
