/** ==================================================================
 *  @file   dss_cm2_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   DSS_CM2
 *
 *  @Filename:    dss_cm2_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __DSS_CM2_CRED_H
#define __DSS_CM2_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance DSS_CM2 of component DSS_CM2 mapped in MONICA at address 0x4A009100
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component DSS_CM2
     *
     */

    /* 
     *  List of bundle arrays for component DSS_CM2
     *
     */

    /* 
     *  List of bundles for component DSS_CM2
     *
     */

    /* 
     * List of registers for component DSS_CM2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL
 *
 * @BRIEF        This register enables the DSS domain power state transition. 
 *               It controls the HW supervised domain power state transition 
 *               between ON-ACTIVE and ON-INACTIVE states. It also hold one 
 *               status bit per clock input of the domain. 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL                          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP
 *
 * @BRIEF        This register controls the static domain depedencies from 
 *               DSS domain towards 'target' domains. It is relevant only for 
 *               domain having system initiator(s). 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP                          0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DYNAMICDEP
 *
 * @BRIEF        This register controls the dynamic domain depedencies from 
 *               DSS domain towards 'target' domains. It is relevant only for 
 *               domain having OCP master port(s). 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DYNAMICDEP                         0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL
 *
 * @BRIEF        This register manages the DSS clocks. 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL                        0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL
 *
 * @BRIEF        This register manages the DEISS clocks. 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL                      0x28ul

    /* 
     * List of register bitfields for component DSS_CM2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_HDMI_PHY_48MHZ_GFCLK   
 *
 * @BRIEF        This field indicates the state of the HDMI_PHY_48MHz_GFCLK 
 *               clock in the domain. 
 *               [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_HDMI_PHY_48MHZ_GFCLK BITFIELD(11, 11)
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_HDMI_PHY_48MHZ_GFCLK__POS 11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_ALWON_SYS_CLK   
 *
 * @BRIEF        This field indicates the state of the DSS_ALWON_SYS_CLK 
 *               clock in the domain. 
 *               [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_ALWON_SYS_CLK BITFIELD(10, 10)
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_ALWON_SYS_CLK__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_FCLK   
 *
 * @BRIEF        This field indicates the state of the DSS_FCLK clock in the 
 *               domain. 
 *               [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_FCLK BITFIELD(9, 9)
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_FCLK__POS 9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_L3_DSS_GICLK   
 *
 * @BRIEF        This field indicates the state of the L3_DSS_GICLK (and 
 *               L4_DSS_GICLK) clock in the domain. 
 *               [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_L3_DSS_GICLK BITFIELD(8, 8)
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_L3_DSS_GICLK__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL   
 *
 * @BRIEF        Controls the clock state transition of the DSS clock domain. 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL          BITFIELD(1, 0)
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__L3_2_STATDEP   
 *
 * @BRIEF        Static dependency towards L3_2 clock domain - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__L3_2_STATDEP       BITFIELD(6, 6)
#define DSS_CM2__CM_DSS_STATICDEP__L3_2_STATDEP__POS  6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__L3_1_STATDEP   
 *
 * @BRIEF        Static dependency towards L3_1 clock domain - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__L3_1_STATDEP       BITFIELD(5, 5)
#define DSS_CM2__CM_DSS_STATICDEP__L3_1_STATDEP__POS  5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__MEMIF_STATDEP   
 *
 * @BRIEF        Static dependency towards MEMIF clock domain - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__MEMIF_STATDEP      BITFIELD(4, 4)
#define DSS_CM2__CM_DSS_STATICDEP__MEMIF_STATDEP__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__IVAHD_STATDEP   
 *
 * @BRIEF        Static dependency towards IVAHD clock domain - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__IVAHD_STATDEP      BITFIELD(2, 2)
#define DSS_CM2__CM_DSS_STATICDEP__IVAHD_STATDEP__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DYNAMICDEP__L3_1_DYNDEP   
 *
 * @BRIEF        Dynamic dependency towards L3_1 domain - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DYNAMICDEP__L3_1_DYNDEP       BITFIELD(5, 5)
#define DSS_CM2__CM_DSS_DYNAMICDEP__L3_1_DYNDEP__POS  5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__STBYST   
 *
 * @BRIEF        Module standby status.  [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__STBYST           BITFIELD(18, 18)
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__STBYST__POS      18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST   
 *
 * @BRIEF        Module idle status.  [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST           BITFIELD(17, 16)
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__POS      16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_TV_CLK   
 *
 * @BRIEF        Optional functional clock control. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_TV_CLK BITFIELD(11, 11)
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_TV_CLK__POS 11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_SYS_CLK   
 *
 * @BRIEF        Optional functional clock control. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_SYS_CLK BITFIELD(10, 10)
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_SYS_CLK__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_48MHZ_CLK   
 *
 * @BRIEF        Optional functional clock control. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_48MHZ_CLK BITFIELD(9, 9)
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_48MHZ_CLK__POS 9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_DSSCLK   
 *
 * @BRIEF        Optional functional clock control. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_DSSCLK BITFIELD(8, 8)
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_DSSCLK__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE   
 *
 * @BRIEF        Control the way mandatory clocks are managed. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE       BITFIELD(1, 0)
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__STBYST   
 *
 * @BRIEF        Module standby status.  [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__STBYST         BITFIELD(18, 18)
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__STBYST__POS    18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST   
 *
 * @BRIEF        Module idle status.  [warm reset insensitive] - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST         BITFIELD(17, 16)
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__MODULEMODE   
 *
 * @BRIEF        Control the way mandatory clocks are managed. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__MODULEMODE     BITFIELD(1, 0)
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__MODULEMODE__POS 0

    /* 
     * List of register bitfields values for component DSS_CM2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_HDMI_PHY_48MHZ_GFCLK__INACT
 *
 * @BRIEF        Corresponding clock is definitely gated - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_HDMI_PHY_48MHZ_GFCLK__INACT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_HDMI_PHY_48MHZ_GFCLK__ACT
 *
 * @BRIEF        Corresponding clock is running or gating/ungating transition 
 *               is on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_HDMI_PHY_48MHZ_GFCLK__ACT 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_ALWON_SYS_CLK__INACT
 *
 * @BRIEF        Corresponding clock is definitely gated - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_ALWON_SYS_CLK__INACT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_ALWON_SYS_CLK__ACT
 *
 * @BRIEF        Corresponding clock is running or gating/ungating transition 
 *               is on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_ALWON_SYS_CLK__ACT 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_FCLK__INACT
 *
 * @BRIEF        Corresponding clock is definitely gated - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_FCLK__INACT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_FCLK__ACT
 *
 * @BRIEF        Corresponding clock is running or gating/ungating transition 
 *               is on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_DSS_FCLK__ACT 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_L3_DSS_GICLK__INACT
 *
 * @BRIEF        Corresponding clock is definitely gated - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_L3_DSS_GICLK__INACT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_L3_DSS_GICLK__ACT
 *
 * @BRIEF        Corresponding clock is running or gating/ungating transition 
 *               is on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKACTIVITY_L3_DSS_GICLK__ACT 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__NO_SLEEP
 *
 * @BRIEF        NO_SLEEP: Sleep transition cannot be initiated. Wakeup 
 *               transition may however occur. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__NO_SLEEP 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__SW_SLEEP
 *
 * @BRIEF        SW_SLEEP: Start a software forced sleep transition on the 
 *               domain. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__SW_SLEEP 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__SW_WKUP
 *
 * @BRIEF        SW_WKUP: Start a software forced wake-up transition on the 
 *               domain. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__SW_WKUP 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__HW_AUTO
 *
 * @BRIEF        HW_AUTO: Automatic transition is enabled. Sleep and wakeup 
 *               transition are based upon hardware conditions. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_CLKSTCTRL__CLKTRCTRL__HW_AUTO 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__L3_2_STATDEP__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__L3_2_STATDEP__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__L3_2_STATDEP__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__L3_2_STATDEP__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__L3_1_STATDEP__ENABLED
 *
 * @BRIEF        Dependency is enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__L3_1_STATDEP__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__MEMIF_STATDEP__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__MEMIF_STATDEP__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__MEMIF_STATDEP__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__MEMIF_STATDEP__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__IVAHD_STATDEP__DISABLED
 *
 * @BRIEF        Dependency is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__IVAHD_STATDEP__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_STATICDEP__IVAHD_STATDEP__ENABLED
 *
 * @BRIEF        Dependency is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_STATICDEP__IVAHD_STATDEP__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DYNAMICDEP__L3_1_DYNDEP__DISABLED
 *
 * @BRIEF        Dependency is disabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DYNAMICDEP__L3_1_DYNDEP__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__STBYST__FUNC
 *
 * @BRIEF        Module is functional (not in standby) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__STBYST__FUNC     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__STBYST__STANDBY
 *
 * @BRIEF        Module is in standby - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__STBYST__STANDBY  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__FUNC
 *
 * @BRIEF        Module is fully functional, including OCP - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__FUNC     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__TRANS
 *
 * @BRIEF        Module is performing transition: wakeup, or sleep, or sleep 
 *               abortion - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__TRANS    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__IDLE
 *
 * @BRIEF        Module is in Idle mode (only OCP part). It is functional if 
 *               using separate functional clock - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__IDLE     0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__DISABLE
 *
 * @BRIEF        Module is disabled and cannot be accessed - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__IDLEST__DISABLE  0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_TV_CLK__FCLK_DIS
 *
 * @BRIEF        Optional functional clock is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_TV_CLK__FCLK_DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_TV_CLK__FCLK_EN
 *
 * @BRIEF        Optional functional clock is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_TV_CLK__FCLK_EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_SYS_CLK__FCLK_DIS
 *
 * @BRIEF        Optional functional clock is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_SYS_CLK__FCLK_DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_SYS_CLK__FCLK_EN
 *
 * @BRIEF        Optional functional clock is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_SYS_CLK__FCLK_EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_48MHZ_CLK__FCLK_DIS
 *
 * @BRIEF        Optional functional clock is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_48MHZ_CLK__FCLK_DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_48MHZ_CLK__FCLK_EN
 *
 * @BRIEF        Optional functional clock is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_48MHZ_CLK__FCLK_EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_DSSCLK__FCLK_DIS
 *
 * @BRIEF        Optional functional clock is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_DSSCLK__FCLK_DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_DSSCLK__FCLK_EN
 *
 * @BRIEF        Optional functional clock is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__OPTFCLKEN_DSSCLK__FCLK_EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__DISABLED
 *
 * @BRIEF        Module is disable by SW. Any OCP access to module results in 
 *               an error, except if resulting from a module wakeup 
 *               (asynchronous wakeup). - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__RESERVED_1
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__RESERVED_1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__ENABLE
 *
 * @BRIEF        Module is explicitly enabled. Interface clock (if not used 
 *               for functions) may be gated according to the clock domain 
 *               state. Functional clocks are guarantied to stay present. As 
 *               long as in this configuration, power domain sleep transition 
 *               cannot happen. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__ENABLE 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DSS_CLKCTRL__MODULEMODE__RESERVED 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__STBYST__FUNC
 *
 * @BRIEF        Module is functional (not in standby) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__STBYST__FUNC   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__STBYST__STANDBY
 *
 * @BRIEF        Module is in standby - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__STBYST__STANDBY 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__FUNC
 *
 * @BRIEF        Module is fully functional, including OCP - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__FUNC   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__TRANS
 *
 * @BRIEF        Module is performing transition: wakeup, or sleep, or sleep 
 *               abortion - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__TRANS  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__IDLE
 *
 * @BRIEF        Module is in Idle mode (only OCP part). It is functional if 
 *               using separate functional clock - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__IDLE   0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__DISABLE
 *
 * @BRIEF        Module is disabled and cannot be accessed - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__IDLEST__DISABLE 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   DSS_CM2__CM_DSS_DEISS_CLKCTRL__MODULEMODE__DISABLED
 *
 * @BRIEF        Module is disabled (not present). - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define DSS_CM2__CM_DSS_DEISS_CLKCTRL__MODULEMODE__DISABLED 0x0ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __DSS_CM2_CRED_H 
                                                            */
