/** ==================================================================
 *  @file   ecd3_ipgw_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   ECD3_IPGW
 *
 *  @Filename:    ecd3_ipgw_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __ECD3_IPGW_CRED_H
#define __ECD3_IPGW_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance ECD3_CFG__IPGW of component ECD3_IPGW mapped in MONICA at address 0x5A059C00
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component ECD3_IPGW
     *
     */

    /* 
     *  List of bundle arrays for component ECD3_IPGW
     *
     */

    /* 
     *  List of bundles for component ECD3_IPGW
     *
     */

    /* 
     * List of registers for component ECD3_IPGW
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_SYSCONFIG
 *
 * @BRIEF        Clock management configuration 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_SYSCONFIG                          0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQ_EOI
 *
 * @BRIEF        End Of Interrupt number specification 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQ_EOI                            0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_0
 *
 * @BRIEF        Per-event raw interrupt status vector, line #0.  
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_0                    0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_1
 *
 * @BRIEF        Per-event raw interrupt status vector, line #1.  
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_1                    0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_2
 *
 * @BRIEF        Per-event raw interrupt status vector, line #2.  
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_2                    0x1Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_3
 *
 * @BRIEF        Per-event raw interrupt status vector, line #3.  
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_3                    0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_4
 *
 * @BRIEF        Per-event raw interrupt status vector, line #0.  
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_4                    0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_5
 *
 * @BRIEF        Per-event raw interrupt status vector, line #0.  
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_5                    0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_6
 *
 * @BRIEF        Per-event raw interrupt status vector, line #0.  
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_6                    0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_0
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #0. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_0                        0x30ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_1
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #1. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_1                        0x34ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_2
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #2. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_2                        0x38ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_3
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #3. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_3                        0x3Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_4
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #0. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_4                        0x40ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_5
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #0. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_5                        0x44ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_6
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #3. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_6                        0x48ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_0
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_0                    0x4Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_1
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #1.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_1                    0x50ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_2
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #2.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_2                    0x54ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_3
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_3                    0x58ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_4
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_4                    0x5Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_5
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_5                    0x60ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_6
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_6                    0x64ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_0
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_0                    0x68ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_1
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #1.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_1                    0x6Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_2
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #2.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_2                    0x70ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_3
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #2.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_3                    0x74ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_4
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_4                    0x78ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_5
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_5                    0x7Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_6
 *
 * @BRIEF        Per-event interrupt enable bit vector, line #2.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_6                    0x80ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_ACLREN
 *
 * @BRIEF        Auto Clear enable 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN                   0xC0ul

    /* 
     * List of register bitfields for component ECD3_IPGW
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_SYSCONFIG__IDLEMODE   
 *
 * @BRIEF        Configuration of the local target state management mode. 
 *               By definition, target can handle read/write transaction as 
 *               long as it is out of IDLE state. 
 *               0: Force-idle mode: local target's idle state follows 
 *               (acknowledges) the system's idle requests unconditionally, 
 *               i.e. regardless of the IP module's internal requirements. 
 *               Backup mode, for debug only.  
 *               1: No-idle mode: local target never enters idle state. 
 *               Backup mode, for debug only.  
 *               2: Smart-idle mode: local target's idle state eventually 
 *               follows (acknowledges) the system's idle requests, depending 
 *               on the IP module's internal requirements. 
 *               IP module shall not generate (IRQ- or DMA-request-related) 
 *               wakeup events.  
 *               3: Smart-idle wakeup-capable mode: local target's idle state 
 *               eventually follows (acknowledges) the system's idle 
 *               requests, depending on the IP module's internal 
 *               requirements. 
 *               IP module may generate (IRQ- or DMA-request-related) wakeup 
 *               events when in idle state. 
 *               Mode is only relevant if the appropriate IP module "swakeup" 
 *               output(s) is (are) implemented. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_SYSCONFIG__IDLEMODE           BITFIELD(3, 2)
#define ECD3_IPGW__ECD3_SYSCONFIG__IDLEMODE__POS      2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_SYSCONFIG__FREEEMU   
 *
 * @BRIEF        Sensitivity to emulation (debug) suspend input signal. 
 *               0: IP module is sensitive to emulation suspend  
 *               1: IP module is not sensitive to emulation suspend - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_SYSCONFIG__FREEEMU            BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_SYSCONFIG__FREEEMU__POS       1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_SYSCONFIG__SOFTRESET   
 *
 * @BRIEF        Software reset 
 *               Read0: Reset done, no pending action 
 *               Read1: Reset (software or other) on going 
 *               Write0: No action 
 *               Write1: Initiate software reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_SYSCONFIG__SOFTRESET          BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_SYSCONFIG__SOFTRESET__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQ_EOI__LINE_NUMBER   
 *
 * @BRIEF        Software End Of Interrupt (EOI) control. Write number of 
 *               interrupt output. 
 *               Write 0x0:  EOI for interrupt output line #0  
 *               Write 0x1:  EOI for interrupt output line #1  
 *               Write 0x2:  EOI for interrupt output line #2 
 *               Write 0x3:  EOI for interrupt output line #3 
 *               Write 0x4:  EOI for interrupt output line #4 
 *               Write 0x5:  EOI for interrupt output line #5 
 *               Write 0x6:  EOI for interrupt output line #6 
 *               Read 0x0:  Reads always 0 (no EOI memory) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQ_EOI__LINE_NUMBER          BITFIELD(2, 0)
#define ECD3_IPGW__ECD3_IRQ_EOI__LINE_NUMBER__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_0__EVENT0   
 *
 * @BRIEF        settable raw status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_0__EVENT0       BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_0__EVENT0__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_1__EVENT0   
 *
 * @BRIEF        settable raw status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_1__EVENT0       BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_1__EVENT0__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_2__EVENT0   
 *
 * @BRIEF        settable raw status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_2__EVENT0       BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_2__EVENT0__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_3__EVENT1   
 *
 * @BRIEF        settable raw status for event #1 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_3__EVENT1       BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_3__EVENT1__POS  1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_3__EVENT0   
 *
 * @BRIEF        settable raw status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_3__EVENT0       BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_3__EVENT0__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_4__EVENT0   
 *
 * @BRIEF        settable raw status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_4__EVENT0       BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_4__EVENT0__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_5__EVENT0   
 *
 * @BRIEF        settable raw status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_5__EVENT0       BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_5__EVENT0__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_6__EVENT1   
 *
 * @BRIEF        settable raw status for event #1 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_6__EVENT1       BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_6__EVENT1__POS  1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IPQSTATUS_RAW_6__EVENT0   
 *
 * @BRIEF        settable raw status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_6__EVENT0       BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IPQSTATUS_RAW_6__EVENT0__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_0__EVENT0   
 *
 * @BRIEF        clearable, enabled status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_0__EVENT0           BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQSTATUS_0__EVENT0__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_1__EVENT0   
 *
 * @BRIEF        clearable, enabled status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_1__EVENT0           BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQSTATUS_1__EVENT0__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_2__EVENT0   
 *
 * @BRIEF        clearable, enabled status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_2__EVENT0           BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQSTATUS_2__EVENT0__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_3__EVENT1   
 *
 * @BRIEF        clearable, enabled status for event #1 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_3__EVENT1           BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IRQSTATUS_3__EVENT1__POS      1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_3__EVENT0   
 *
 * @BRIEF        clearable, enabled status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_3__EVENT0           BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQSTATUS_3__EVENT0__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_4__EVENT0   
 *
 * @BRIEF        clearable, enabled status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_4__EVENT0           BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQSTATUS_4__EVENT0__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_5__EVENT0   
 *
 * @BRIEF        clearable, enabled status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_5__EVENT0           BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQSTATUS_5__EVENT0__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_6__EVENT1   
 *
 * @BRIEF        clearable, enabled status for event #1 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_6__EVENT1           BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IRQSTATUS_6__EVENT1__POS      1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_6__EVENT0   
 *
 * @BRIEF        clearable, enabled status for event #0 
 *               Write 0:  No action  
 *               Read 0:  No (enabled) event pending  
 *               Read 1:  Event pending  
 *               Write 1:  Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_6__EVENT0           BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQSTATUS_6__EVENT0__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_0__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_0__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_0__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_1__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_1__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_1__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_2__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_2__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_2__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_3__ENABLE1   
 *
 * @BRIEF        enable for event #1 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_3__ENABLE1      BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_3__ENABLE1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_3__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_3__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_3__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_4__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_4__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_4__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_5__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_5__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_5__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_6__ENABLE1   
 *
 * @BRIEF        enable for event #1 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_6__ENABLE1      BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_6__ENABLE1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_SET_6__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_SET_6__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_SET_6__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_0__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_0__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_0__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_1__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_1__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_1__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_2__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_2__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_2__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_3__ENABLE1   
 *
 * @BRIEF        enable for event #1 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_3__ENABLE1      BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_3__ENABLE1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_3__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_3__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_3__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_4__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_4__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_4__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_5__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_5__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_5__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_6__ENABLE1   
 *
 * @BRIEF        enable for event #1 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_6__ENABLE1      BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_6__ENABLE1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQENABLE_CLR_6__ENABLE0   
 *
 * @BRIEF        enable for event #0 
 *               Write 0:  No action  
 *               Read 0:  Interrupt disabled (masked)  
 *               Read 1:  Interrupt enabled  
 *               Write 1:  Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_6__ENABLE0      BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQENABLE_CLR_6__ENABLE0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN6   
 *
 * @BRIEF        for line6 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN6     BITFIELD(6, 6)
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN6__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN5   
 *
 * @BRIEF        for line5 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN5     BITFIELD(5, 5)
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN5__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN4   
 *
 * @BRIEF        for line4 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN4     BITFIELD(4, 4)
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN4__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN3   
 *
 * @BRIEF        for line3 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN3     BITFIELD(3, 3)
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN3__POS 3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN2   
 *
 * @BRIEF        for line2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN2     BITFIELD(2, 2)
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN2__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN1   
 *
 * @BRIEF        for line1 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN1     BITFIELD(1, 1)
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN0   
 *
 * @BRIEF        for line0 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN0     BITFIELD(0, 0)
#define ECD3_IPGW__ECD3_IRQSTATUS_ACLREN__ACLREN0__POS 0

    /* 
     * List of register bitfields values for component ECD3_IPGW
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __ECD3_IPGW_CRED_H 
                                                            */
