/** ==================================================================
 *  @file   ecd3_bfsw_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   ECD3_BFSW
 *
 *  @Filename:    ecd3_bfsw_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __ECD3_BFSW_CRED_H
#define __ECD3_BFSW_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance ECD3_CFG__BFSW of component ECD3_BFSW mapped in MONICA at address 0x5A059A00
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component ECD3_BFSW
     *
     */

    /* 
     *  List of bundle arrays for component ECD3_BFSW
     *
     */

    /* 
     *  List of bundles for component ECD3_BFSW
     *
     */

    /* 
     * List of registers for component ECD3_BFSW
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__VIEWMODE
 *
 * @BRIEF        View Mode Register. 
 *               It selects full-view mode or ping-pong view mode. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__VIEWMODE                                0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__MSTID1
 *
 * @BRIEF        Master ID 1 Register 
 *               Select master between HWA and DMA bus. 
 *               This register is used in both full view and ping-pong view 
 *               mode. 
 *               This register is for buffers which has two physical 
 *               memories. 
 *               This register is affected by direct_switch_pi input port. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__MSTID1                                  0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__MSTID2
 *
 * @BRIEF        Master ID 1 Register 
 *               Select master between HWA and DMA bus. 
 *               This register is for buffers which has only one physical 
 *               memory. 
 *               This register is NOT affected by direct_switch_pi input 
 *               port. 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__MSTID2                                  0x8ul

    /* 
     * List of register bitfields for component ECD3_BFSW
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__VIEWMODE__VIEW_ERSDBUF   
 *
 * @BRIEF        View mode selection for ersdbuf. 
 *               When '0', full view mode is selected. 
 *               When '1', ping-pong view mode is selected. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__VIEWMODE__VIEW_ERSDBUF             BITFIELD(1, 1)
#define ECD3_BFSW__VIEWMODE__VIEW_ERSDBUF__POS        1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__VIEWMODE__VIEW_ECDABUF   
 *
 * @BRIEF        View mode selection for ecdabuf. 
 *               When '0', full view mode is selected. 
 *               When '1', ping-pong view mode is selected. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__VIEWMODE__VIEW_ECDABUF             BITFIELD(0, 0)
#define ECD3_BFSW__VIEWMODE__VIEW_ECDABUF__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__MSTID1__MST_ERSDBUF_B   
 *
 * @BRIEF        Master selection for ersdbuf B. 
 *               This bit is used in only ping-pong view mode. 
 *               when '0', buffer B is assigned to DMA 
 *               when '1', buffer B is assigned to HWA. 
 *               This bit has no effect in full view mode. 
 *               If direct_switch_pi is high, the value of this bit is 
 *               inverted. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__MSTID1__MST_ERSDBUF_B              BITFIELD(3, 3)
#define ECD3_BFSW__MSTID1__MST_ERSDBUF_B__POS         3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__MSTID1__MST_ERSDBUF_A   
 *
 * @BRIEF        Master selection for ersdbuf A. 
 *               This bit is used in both full view and ping-pong view mode. 
 *               In full viw mode, 
 *               when '0', both buffer A and B are assigned to DMA 
 *               when '1', both buffer A and B are assigned to HWA. 
 *               In ping-pong view mode, 
 *               when '0', buffer A is assigned to DMA 
 *               when '1', buffer A is assigned to HWA. 
 *               (Buffer B is not affected in ping-pong view mode.) 
 *               If direct_switch_pi is high, the value of this bit is 
 *               inverted. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__MSTID1__MST_ERSDBUF_A              BITFIELD(2, 2)
#define ECD3_BFSW__MSTID1__MST_ERSDBUF_A__POS         2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__MSTID1__MST_ECDABUF_B   
 *
 * @BRIEF        Master selection for ecdabuf B. 
 *               This bit is used in only ping-pong view mode. 
 *               when '0', buffer B is assigned to DMA 
 *               when '1', buffer B is assigned to HWA. 
 *               This bit has no effect in full view mode. 
 *               If direct_switch_pi is high, the value of this bit is 
 *               inverted. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__MSTID1__MST_ECDABUF_B              BITFIELD(1, 1)
#define ECD3_BFSW__MSTID1__MST_ECDABUF_B__POS         1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__MSTID1__MST_ECDABUF_A   
 *
 * @BRIEF        Master selection for ecdabuf A. 
 *               This bit is used in both full view and ping-pong view mode. 
 *               In full viw mode, 
 *               when '0', both buffer A and B are assigned to DMA 
 *               when '1', both buffer A and B are assigned to HWA. 
 *               In ping-pong view mode, 
 *               when '0', buffer A is assigned to DMA 
 *               when '1', buffer A is assigned to HWA. 
 *               (Buffer B is not affected in ping-pong view mode.) 
 *               If direct_switch_pi is high, the value of this bit is 
 *               inverted. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__MSTID1__MST_ECDABUF_A              BITFIELD(0, 0)
#define ECD3_BFSW__MSTID1__MST_ECDABUF_A__POS         0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ECD3_BFSW__MSTID2__MST_ECDWBUF   
 *
 * @BRIEF        Master selection for ecdwbuf. 
 *               when '0', the buffer is assigned to DMA 
 *               when '1', the buffer is assigned to HWA. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define ECD3_BFSW__MSTID2__MST_ECDWBUF                BITFIELD(0, 0)
#define ECD3_BFSW__MSTID2__MST_ECDWBUF__POS           0

    /* 
     * List of register bitfields values for component ECD3_BFSW
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __ECD3_BFSW_CRED_H 
                                                            */
