/** ==================================================================
 *  @file   emu_prm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   EMU_PRM
 *
 *  @Filename:    emu_prm_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __EMU_PRM_CRED_H
#define __EMU_PRM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance EMU_PRM of component EMU_PRM mapped in MONICA at address 0x4A307900
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component EMU_PRM
     *
     */

    /* 
     *  List of bundle arrays for component EMU_PRM
     *
     */

    /* 
     *  List of bundles for component EMU_PRM
     *
     */

    /* 
     * List of registers for component EMU_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTCTRL
 *
 * @BRIEF        This register controls the EMU power state to reach upon a 
 *               domain sleep transition 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTCTRL                          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST
 *
 * @BRIEF        This register provides a status on the  EMU domain current 
 *               power state. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST                            0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__RM_EMU_DEBUGSS_CONTEXT
 *
 * @BRIEF        This register contains dedicated DEBUGSS context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT                    0x24ul

    /* 
     * List of register bitfields for component EMU_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTCTRL__EMU_BANK_ONSTATE   
 *
 * @BRIEF        EMU memory state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTCTRL__EMU_BANK_ONSTATE   BITFIELD(17, 16)
#define EMU_PRM__PM_EMU_PWRSTCTRL__EMU_BANK_ONSTATE__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTCTRL__POWERSTATE   
 *
 * @BRIEF        Power state control - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTCTRL__POWERSTATE         BITFIELD(1, 0)
#define EMU_PRM__PM_EMU_PWRSTCTRL__POWERSTATE__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__INTRANSITION   
 *
 * @BRIEF        Domain transition status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__INTRANSITION         BITFIELD(20, 20)
#define EMU_PRM__PM_EMU_PWRSTST__INTRANSITION__POS    20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST   
 *
 * @BRIEF        EMU memory bank state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST     BITFIELD(5, 4)
#define EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__LOGICSTATEST   
 *
 * @BRIEF        Logic state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__LOGICSTATEST         BITFIELD(2, 2)
#define EMU_PRM__PM_EMU_PWRSTST__LOGICSTATEST__POS    2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__POWERSTATEST   
 *
 * @BRIEF        Current power state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__POWERSTATEST         BITFIELD(1, 0)
#define EMU_PRM__PM_EMU_PWRSTST__POWERSTATEST__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTMEM_EMU_BANK   
 *
 * @BRIEF        Specify if memory-based context in EMU_BANK memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTMEM_EMU_BANK BITFIELD(8, 8)
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTMEM_EMU_BANK__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of EMU_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTCONTEXT_DFF__POS 0

    /* 
     * List of register bitfields values for component EMU_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTCTRL__EMU_BANK_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTCTRL__EMU_BANK_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTCTRL__POWERSTATE__OFF
 *
 * @BRIEF        OFF state - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTCTRL__POWERSTATE__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__INTRANSITION__NO
 *
 * @BRIEF        No on-going transition on power domain - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__INTRANSITION__NO     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__INTRANSITION__ONGOING
 *
 * @BRIEF        Power domain transition is in progress. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__INTRANSITION__ONGOING 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__RESERVED1
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__RESERVED1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__RESERVED2
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__RESERVED2 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON 
 *               It is supplied by WKUP LDO - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__EMU_BANK_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__LOGICSTATEST__OFF
 *
 * @BRIEF        Logic in domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__LOGICSTATEST__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__LOGICSTATEST__ON
 *
 * @BRIEF        Logic in domain is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__LOGICSTATEST__ON     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__POWERSTATEST__OFF
 *
 * @BRIEF        Power domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__POWERSTATEST__OFF    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__PM_EMU_PWRSTST__POWERSTATEST__ON
 *
 * @BRIEF        Power domain is ON-ACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__PM_EMU_PWRSTST__POWERSTATEST__ON     0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTMEM_EMU_BANK__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTMEM_EMU_BANK__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTMEM_EMU_BANK__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTMEM_EMU_BANK__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define EMU_PRM__RM_EMU_DEBUGSS_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __EMU_PRM_CRED_H 
                                                            */
