/** ==================================================================
 *  @file   gpio_v2_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   GPIO_V2
 *
 *  @Filename:    gpio_v2_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __GPIO_V2_CRED_H
#define __GPIO_V2_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance GPIO2 of component GPIO_V2 mapped in MONICA at address 0x48055000
     * Instance GPIO1 of component GPIO_V2 mapped in MONICA at address 0x4A310000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component GPIO_V2
     *
     */

    /* 
     *  List of bundle arrays for component GPIO_V2
     *
     */

    /* 
     *  List of bundles for component GPIO_V2
     *
     */

    /* 
     * List of registers for component GPIO_V2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_REVISION
 *
 * @BRIEF        IP Revision Identifier (X.Y.R) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_REVISION                             0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG
 *
 * @BRIEF        SYSTEM CONFIGURATION REGISTER 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG                            0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_EOI
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_EOI                                  0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_RAW_0
 *
 * @BRIEF        Per-event raw interrupt status vector 
 *               (corresponding to first line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_RAW_0                      0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_RAW_1
 *
 * @BRIEF        Per-event raw interrupt status vector 
 *               (corresponding to second line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_RAW_1                      0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_0
 *
 * @BRIEF        Per-event interrupt status vector (enabled) 
 *               (corresponding to first line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_0                          0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_1
 *
 * @BRIEF        Per-event enabled interrupt status vector 
 *               (corresponding to second line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_1                          0x30ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_SET_0
 *
 * @BRIEF        Per-event interrupt enable set vector 
 *               (corresponding to first line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_SET_0                      0x34ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_SET_1
 *
 * @BRIEF        Per-event enable set interrupt vector 
 *               (corresponding to second line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_SET_1                      0x38ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_CLR_0
 *
 * @BRIEF        Per-event interrupt enable clear vector 
 *               (corresponding to first line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_CLR_0                      0x3Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_CLR_1
 *
 * @BRIEF        Per-event enable clear interrupt vector 
 *               (corresponding to second line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_CLR_1                      0x40ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQWAKEN_0
 *
 * @BRIEF        Per-event wakeup enable set vector 
 *               (corresponding to first line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQWAKEN_0                           0x44ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQWAKEN_1
 *
 * @BRIEF        Per-event wakeup enable set vector 
 *               (corresponding to second line of interrupt) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQWAKEN_1                           0x48ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSSTATUS
 *
 * @BRIEF        System Status register. 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSSTATUS                            0x114ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS1
 *
 * @BRIEF        Interrupt Status Register (legacy) for first line of 
 *               interrupt. 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS1                           0x118ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQENABLE1
 *
 * @BRIEF        Interrupt Enable Register (legacy) for first line of 
 *               interrupt. 
 *               0 Disabled 
 *               1 Enabled 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQENABLE1                           0x11Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_WAKEUPENABLE
 *
 * @BRIEF        Wakeup Enable Register (legacy) for first line of interrupt. 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_WAKEUPENABLE                         0x120ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS2
 *
 * @BRIEF        Interrupt Status Register (legacy) for second line of 
 *               interrupt. 
 *               0 No interrupt set 
 *               1 Interrupt set 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS2                           0x128ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQENABLE2
 *
 * @BRIEF        Interrupt Enable Register (legacy) for second line of 
 *               interrupt. 
 *               0 Disabled 
 *               1 Enabled 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQENABLE2                           0x12Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL
 *
 * @BRIEF        GPIO Control register. 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL                                 0x130ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_OE
 *
 * @BRIEF        Output Enable Register 
 *               0  Output Enabled 
 *               1  Output disabled 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_OE                                   0x134ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DATAIN
 *
 * @BRIEF        Data Input Register (with sampled input data). 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DATAIN                               0x138ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DATAOUT
 *
 * @BRIEF        Data Output Register (data to set on output pins). 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DATAOUT                              0x13Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_LEVELDETECT0
 *
 * @BRIEF        Detect Low Level Register 
 *               0  Low level detection disabled 
 *               1  Low level detection enabled 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_LEVELDETECT0                         0x140ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_LEVELDETECT1
 *
 * @BRIEF        Detect High Level Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_LEVELDETECT1                         0x144ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_RISINGDETECT
 *
 * @BRIEF        Detect Rising Edge Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_RISINGDETECT                         0x148ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_FALLINGDETECT
 *
 * @BRIEF        Detect Falling Edge Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_FALLINGDETECT                        0x14Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DEBOUNCENABLE
 *
 * @BRIEF        Debouncing Enable Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DEBOUNCENABLE                        0x150ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DEBOUNCINGTIME
 *
 * @BRIEF        Debouncing Value Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DEBOUNCINGTIME                       0x154ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARIRQENABLE1
 *
 * @BRIEF        Clear Interrupt Enable Register - Legacy Mode 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARIRQENABLE1                      0x160ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETIRQENABLE1
 *
 * @BRIEF        Set Interrupt Enable Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETIRQENABLE1                        0x164ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARIRQENABLE2
 *
 * @BRIEF        Clear Interrupt Enable Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARIRQENABLE2                      0x170ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETIRQENABLE2
 *
 * @BRIEF        Set Interrupt Enable Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETIRQENABLE2                        0x174ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARWKUPENA
 *
 * @BRIEF        Clear Wake-up Enable Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARWKUPENA                         0x180ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETWKUENA
 *
 * @BRIEF        Set Wake-up Enable Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETWKUENA                            0x184ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARDATAOUT
 *
 * @BRIEF        Clear Data Output Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARDATAOUT                         0x190ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETDATAOUT
 *
 * @BRIEF        Set Data Output Register 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETDATAOUT                           0x194ul

    /* 
     * List of register bitfields for component GPIO_V2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_REVISION__SCHEME   
 *
 * @BRIEF        Used to distinguish between old Scheme and current.  
 *               Spare bit to encode future schemes. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_REVISION__SCHEME                BITFIELD(31, 30)
#define GPIO_V2__GPIO_REVISION__SCHEME__POS           30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_REVISION__FUNC   
 *
 * @BRIEF        Function: Indicates a software compatible module family - 
 *               (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_REVISION__FUNC                  BITFIELD(27, 16)
#define GPIO_V2__GPIO_REVISION__FUNC__POS             16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_REVISION__RTL   
 *
 * @BRIEF        RTL version 
 *               This field changes on bug fix, and resets to - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_REVISION__RTL                   BITFIELD(15, 11)
#define GPIO_V2__GPIO_REVISION__RTL__POS              11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_REVISION__MAJOR   
 *
 * @BRIEF        Major Revision 
 *               This field changes when there is a major feature change. 
 *               This field does not change due to bug fix, or minor feature 
 *               change. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_REVISION__MAJOR                 BITFIELD(10, 8)
#define GPIO_V2__GPIO_REVISION__MAJOR__POS            8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_REVISION__CUSTOM   
 *
 * @BRIEF        Indicates a special version for a particular device.  
 *               Consequence of use may avoid use of standard Chip Support 
 *               Library (CSL) / Drivers.   
 *               0 if non-custom. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_REVISION__CUSTOM                BITFIELD(7, 6)
#define GPIO_V2__GPIO_REVISION__CUSTOM__POS           6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_REVISION__MINOR   
 *
 * @BRIEF        Minor Revision 
 *               This field changes when features are scaled up or down. 
 *               This field does not change due to bug fix, or major feature 
 *               change. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_REVISION__MINOR                 BITFIELD(5, 0)
#define GPIO_V2__GPIO_REVISION__MINOR__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__IDLEMODE   
 *
 * @BRIEF        00 Force Idle. An idle request is acknowledged 
 *               unconditionally. 
 *               01 No Idle. An idle request is never acknowledged. 
 *               10 Smart Idle. The acknowledgement to an idle request is 
 *               given based on the internal activity (see 4.1.2). 
 *               11 Smart Idle Wakeup. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__IDLEMODE             BITFIELD(4, 3)
#define GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__POS        3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__ENAWAKEUP   
 *
 * @BRIEF        Wakeup control. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__ENAWAKEUP            BITFIELD(2, 2)
#define GPIO_V2__GPIO_SYSCONFIG__ENAWAKEUP__POS       2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__SOFTRESET   
 *
 * @BRIEF        Software Reset. Set this bit to 1 to trigger a module reset. 
 *               The bit is automatically reset by the hardware. During 
 *               reads, it always returns 0. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__SOFTRESET            BITFIELD(1, 1)
#define GPIO_V2__GPIO_SYSCONFIG__SOFTRESET__POS       1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__AUTOIDLE   
 *
 * @BRIEF        OCP clock gating control. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__AUTOIDLE             BITFIELD(0, 0)
#define GPIO_V2__GPIO_SYSCONFIG__AUTOIDLE__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_EOI__LINE_NUMBER   
 *
 * @BRIEF        Software End Of Interrupt (EOI) control. - (WO) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_EOI__LINE_NUMBER                BITFIELD(0, 0)
#define GPIO_V2__GPIO_EOI__LINE_NUMBER__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_RAW_0__INTLINE   
 *
 * @BRIEF        Status Raw for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_RAW_0__INTLINE        BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS_RAW_0__INTLINE__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_RAW_1__INTLINE   
 *
 * @BRIEF        Status Raw for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_RAW_1__INTLINE        BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS_RAW_1__INTLINE__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_0__INTLINE   
 *
 * @BRIEF        Status for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_0__INTLINE            BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS_0__INTLINE__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_1__INTLINE   
 *
 * @BRIEF        Status for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_1__INTLINE            BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS_1__INTLINE__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_SET_0__INTLINE   
 *
 * @BRIEF        Status Set for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_SET_0__INTLINE        BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS_SET_0__INTLINE__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_SET_1__INTLINE   
 *
 * @BRIEF        Status Set for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_SET_1__INTLINE        BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS_SET_1__INTLINE__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_CLR_0__INTLINE   
 *
 * @BRIEF        Status Clear for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_CLR_0__INTLINE        BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS_CLR_0__INTLINE__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS_CLR_1__INTLINE   
 *
 * @BRIEF        Status Clear for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS_CLR_1__INTLINE        BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS_CLR_1__INTLINE__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQWAKEN_0__INTLINE   
 *
 * @BRIEF        Wakeup Set for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQWAKEN_0__INTLINE             BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQWAKEN_0__INTLINE__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQWAKEN_1__INTLINE   
 *
 * @BRIEF        Wakeup Set for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQWAKEN_1__INTLINE             BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQWAKEN_1__INTLINE__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSSTATUS__RESETDONE   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSSTATUS__RESETDONE            BITFIELD(0, 0)
#define GPIO_V2__GPIO_SYSSTATUS__RESETDONE__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS1__INTLINE   
 *
 * @BRIEF        Status for Interrupt Line 
 *               0  No interrupt set 
 *               1 Interrupt set - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS1__INTLINE             BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS1__INTLINE__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQENABLE1__INTLINE   
 *
 * @BRIEF        Status for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQENABLE1__INTLINE             BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQENABLE1__INTLINE__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_WAKEUPENABLE__INTLINE   
 *
 * @BRIEF        Wakeup Enable for Interrupt Line 
 *               0 Wakeup generation is disabled 
 *               1 Wakeup generation is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_WAKEUPENABLE__INTLINE           BITFIELD(31, 0)
#define GPIO_V2__GPIO_WAKEUPENABLE__INTLINE__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS2__INTLINE   
 *
 * @BRIEF        Status for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS2__INTLINE             BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQSTATUS2__INTLINE__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQENABLE2__INTLINE   
 *
 * @BRIEF        Enable for Interrupt Line - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQENABLE2__INTLINE             BITFIELD(31, 0)
#define GPIO_V2__GPIO_IRQENABLE2__INTLINE__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL__GATINGRATIO   
 *
 * @BRIEF        Clock gating ratio for event detection - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL__GATINGRATIO               BITFIELD(2, 1)
#define GPIO_V2__GPIO_CTRL__GATINGRATIO__POS          1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL__DISABLEMODULE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL__DISABLEMODULE             BITFIELD(0, 0)
#define GPIO_V2__GPIO_CTRL__DISABLEMODULE__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_OE__OUTPUTEN   
 *
 * @BRIEF        Output Enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_OE__OUTPUTEN                    BITFIELD(31, 0)
#define GPIO_V2__GPIO_OE__OUTPUTEN__POS               0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DATAIN__DATAIN   
 *
 * @BRIEF        Sampled input data - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DATAIN__DATAIN                  BITFIELD(31, 0)
#define GPIO_V2__GPIO_DATAIN__DATAIN__POS             0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DATAOUT__DATAOUT   
 *
 * @BRIEF        Data to set on output pins - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DATAOUT__DATAOUT                BITFIELD(31, 0)
#define GPIO_V2__GPIO_DATAOUT__DATAOUT__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_LEVELDETECT0__LEVELDETECT0   
 *
 * @BRIEF        Low Level detection - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_LEVELDETECT0__LEVELDETECT0      BITFIELD(31, 0)
#define GPIO_V2__GPIO_LEVELDETECT0__LEVELDETECT0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_LEVELDETECT1__LEVELDETECT1   
 *
 * @BRIEF        0 High level detection disabled 
 *               1 High level detection enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_LEVELDETECT1__LEVELDETECT1      BITFIELD(31, 0)
#define GPIO_V2__GPIO_LEVELDETECT1__LEVELDETECT1__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_RISINGDETECT__RISINGDETECT   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_RISINGDETECT__RISINGDETECT      BITFIELD(31, 0)
#define GPIO_V2__GPIO_RISINGDETECT__RISINGDETECT__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_FALLINGDETECT__FALLINGDETECT   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_FALLINGDETECT__FALLINGDETECT    BITFIELD(31, 0)
#define GPIO_V2__GPIO_FALLINGDETECT__FALLINGDETECT__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DEBOUNCENABLE__DEBOUNCEENABLE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DEBOUNCENABLE__DEBOUNCEENABLE   BITFIELD(31, 0)
#define GPIO_V2__GPIO_DEBOUNCENABLE__DEBOUNCEENABLE__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DEBOUNCINGTIME__DEBOUNCETIME   
 *
 * @BRIEF        8-bits values specifying the debouncing time in 31us steps - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DEBOUNCINGTIME__DEBOUNCETIME    BITFIELD(7, 0)
#define GPIO_V2__GPIO_DEBOUNCINGTIME__DEBOUNCETIME__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARIRQENABLE1__INTLINE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARIRQENABLE1__INTLINE        BITFIELD(31, 0)
#define GPIO_V2__GPIO_CLEARIRQENABLE1__INTLINE__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETIRQENABLE1__INTLINE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETIRQENABLE1__INTLINE          BITFIELD(31, 0)
#define GPIO_V2__GPIO_SETIRQENABLE1__INTLINE__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARIRQENABLE2__INTLINE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARIRQENABLE2__INTLINE        BITFIELD(31, 0)
#define GPIO_V2__GPIO_CLEARIRQENABLE2__INTLINE__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETIRQENABLE2__INTLINE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETIRQENABLE2__INTLINE          BITFIELD(31, 0)
#define GPIO_V2__GPIO_SETIRQENABLE2__INTLINE__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARWKUPENA__INTLINE   
 *
 * @BRIEF        0 No effect 
 *               1 Clear the corresponding bit in the Wakeup Enable Register 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARWKUPENA__INTLINE           BITFIELD(31, 0)
#define GPIO_V2__GPIO_CLEARWKUPENA__INTLINE__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETWKUENA__INTLINE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETWKUENA__INTLINE              BITFIELD(31, 0)
#define GPIO_V2__GPIO_SETWKUENA__INTLINE__POS         0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARDATAOUT__INTLINE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARDATAOUT__INTLINE           BITFIELD(31, 0)
#define GPIO_V2__GPIO_CLEARDATAOUT__INTLINE__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETDATAOUT__INTLINE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETDATAOUT__INTLINE             BITFIELD(31, 0)
#define GPIO_V2__GPIO_SETDATAOUT__INTLINE__POS        0

    /* 
     * List of register bitfields values for component GPIO_V2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__FORCEIDLE
 *
 * @BRIEF        An idle request is acknowledged unconditionally. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__FORCEIDLE  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__NOIDLE
 *
 * @BRIEF        An idle request is never acknowledged. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__NOIDLE     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__SMARTIDLE
 *
 * @BRIEF        The acknowledgement to an idle request is given based on the 
 *               internal activity (see 4.1.2). - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__SMARTIDLE  0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__SMARTIDLEWAKEUP
 *
 * @BRIEF        Smart Idle Wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__IDLEMODE__SMARTIDLEWAKEUP 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__ENAWAKEUP__DISABLE
 *
 * @BRIEF        Wakeup generation is disabled. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__ENAWAKEUP__DISABLE   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__ENAWAKEUP__ENABLE
 *
 * @BRIEF        Wakeup capability is enabled upon expected transition on 
 *               input GPIO pin - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__ENAWAKEUP__ENABLE    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__SOFTRESET__NORMAL
 *
 * @BRIEF        Normal Mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__SOFTRESET__NORMAL    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__SOFTRESET__RESET
 *
 * @BRIEF        The module is reset. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__SOFTRESET__RESET     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__AUTOIDLE__FREERUN
 *
 * @BRIEF        Internal Interface OCP clock is free-running - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__AUTOIDLE__FREERUN    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSCONFIG__AUTOIDLE__AUTOMATIC
 *
 * @BRIEF        Automatic internal OCP clock gating, based on the OCP 
 *               interface activity - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSCONFIG__AUTOIDLE__AUTOMATIC  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_EOI__LINE_NUMBER__EOI_0
 *
 * @BRIEF        EOI for interrupt line number 0. Read returns 0. - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_EOI__LINE_NUMBER__EOI_0         0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_EOI__LINE_NUMBER__EOI_1
 *
 * @BRIEF        EOI for interrupt line number 1. Read returns 0. - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_EOI__LINE_NUMBER__EOI_1         0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSSTATUS__RESETDONE__INPROGRESS
 *
 * @BRIEF        Internal Reset is on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSSTATUS__RESETDONE__INPROGRESS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SYSSTATUS__RESETDONE__COMPLETE
 *
 * @BRIEF        Reset completed - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SYSSTATUS__RESETDONE__COMPLETE  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS1__INTLINE__NOTSET
 *
 * @BRIEF        No interrupt set - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS1__INTLINE__NOTSET     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS1__INTLINE__SET
 *
 * @BRIEF        Interrupt set - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS1__INTLINE__SET        0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQENABLE1__INTLINE__DISABLED
 *
 * @BRIEF        Interrupt Disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQENABLE1__INTLINE__DISABLED   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQENABLE1__INTLINE__ENABLED
 *
 * @BRIEF        Interrupt enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQENABLE1__INTLINE__ENABLED    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_WAKEUPENABLE__INTLINE__DISABLED
 *
 * @BRIEF        Wakeup generation is disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_WAKEUPENABLE__INTLINE__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_WAKEUPENABLE__INTLINE__ENABLED
 *
 * @BRIEF        Wakeup generation is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_WAKEUPENABLE__INTLINE__ENABLED  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS2__INTLINE__NOTSET
 *
 * @BRIEF        No interrupt set - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS2__INTLINE__NOTSET     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQSTATUS2__INTLINE__SET
 *
 * @BRIEF        Interrupt set - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQSTATUS2__INTLINE__SET        0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQENABLE2__INTLINE__DISABLED
 *
 * @BRIEF        Interrupt disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQENABLE2__INTLINE__DISABLED   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_IRQENABLE2__INTLINE__ENABLED
 *
 * @BRIEF        Interrupt enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_IRQENABLE2__INTLINE__ENABLED    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL__GATINGRATIO__N_1
 *
 * @BRIEF        N = 1 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL__GATINGRATIO__N_1          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL__GATINGRATIO__N_2
 *
 * @BRIEF        N = 2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL__GATINGRATIO__N_2          0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL__GATINGRATIO__N_4
 *
 * @BRIEF        N = 4 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL__GATINGRATIO__N_4          0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL__GATINGRATIO__N_8
 *
 * @BRIEF        N = 8 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL__GATINGRATIO__N_8          0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL__DISABLEMODULE__ENABLED
 *
 * @BRIEF        Module is enabled, clocks are not gated. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL__DISABLEMODULE__ENABLED    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CTRL__DISABLEMODULE__DISABLED
 *
 * @BRIEF        Module is disabled, internal clocks are gated - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CTRL__DISABLEMODULE__DISABLED   0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_OE__OUTPUTEN__ENABLED
 *
 * @BRIEF        Output Enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_OE__OUTPUTEN__ENABLED           0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_OE__OUTPUTEN__DISABLED
 *
 * @BRIEF        Output Disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_OE__OUTPUTEN__DISABLED          0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_LEVELDETECT0__LEVELDETECT0__DISABLED
 *
 * @BRIEF        Low level detection disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_LEVELDETECT0__LEVELDETECT0__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_LEVELDETECT0__LEVELDETECT0__ENABLED
 *
 * @BRIEF        Low level detection enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_LEVELDETECT0__LEVELDETECT0__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_LEVELDETECT1__LEVELDETECT1__DISABLED
 *
 * @BRIEF        High level detection disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_LEVELDETECT1__LEVELDETECT1__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_LEVELDETECT1__LEVELDETECT1__ENABLED
 *
 * @BRIEF        High level detection enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_LEVELDETECT1__LEVELDETECT1__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_RISINGDETECT__RISINGDETECT__DISABLED
 *
 * @BRIEF        Rising edge detection disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_RISINGDETECT__RISINGDETECT__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_RISINGDETECT__RISINGDETECT__ENABLED
 *
 * @BRIEF        Rising edge detection enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_RISINGDETECT__RISINGDETECT__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_FALLINGDETECT__FALLINGDETECT__DISABLED
 *
 * @BRIEF        Falling edge detection disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_FALLINGDETECT__FALLINGDETECT__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_FALLINGDETECT__FALLINGDETECT__ENABLED
 *
 * @BRIEF        Falling edge detection enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_FALLINGDETECT__FALLINGDETECT__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DEBOUNCENABLE__DEBOUNCEENABLE__NODEBOUNCE
 *
 * @BRIEF        No debouncing - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DEBOUNCENABLE__DEBOUNCEENABLE__NODEBOUNCE 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_DEBOUNCENABLE__DEBOUNCEENABLE__DEBOUNCE
 *
 * @BRIEF        Debouncing Activated - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_DEBOUNCENABLE__DEBOUNCEENABLE__DEBOUNCE 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARIRQENABLE1__INTLINE__NOEFFECT
 *
 * @BRIEF        No effect - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARIRQENABLE1__INTLINE__NOEFFECT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARIRQENABLE1__INTLINE__CLEAR
 *
 * @BRIEF        Clear the corresponding bit in the relevant Interrupt Enable 
 *               Register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARIRQENABLE1__INTLINE__CLEAR 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETIRQENABLE1__INTLINE__NOEFFECT
 *
 * @BRIEF        No effect - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETIRQENABLE1__INTLINE__NOEFFECT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETIRQENABLE1__INTLINE__SET
 *
 * @BRIEF        Set the corresponding bit in the relevant Interrupt Enable 
 *               Register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETIRQENABLE1__INTLINE__SET     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARIRQENABLE2__INTLINE__NOEFFECT
 *
 * @BRIEF        No effect. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARIRQENABLE2__INTLINE__NOEFFECT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARIRQENABLE2__INTLINE__CLEAR
 *
 * @BRIEF        Clear the corresponding bit in the relevant Interrupt Enable 
 *               Register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARIRQENABLE2__INTLINE__CLEAR 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETIRQENABLE2__INTLINE__NOEFFECT
 *
 * @BRIEF        No effect - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETIRQENABLE2__INTLINE__NOEFFECT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETIRQENABLE2__INTLINE__SET
 *
 * @BRIEF        Set the corresponding bit in the relevant Interrupt Enable 
 *               Register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETIRQENABLE2__INTLINE__SET     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARWKUPENA__INTLINE__NOEFFECT
 *
 * @BRIEF        No effect - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARWKUPENA__INTLINE__NOEFFECT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARWKUPENA__INTLINE__CLEAR
 *
 * @BRIEF        Clear the corresponding bit in the Wakeup Enable Register - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARWKUPENA__INTLINE__CLEAR    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETWKUENA__INTLINE__NOEFFECT
 *
 * @BRIEF        No effect - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETWKUENA__INTLINE__NOEFFECT    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETWKUENA__INTLINE__SET
 *
 * @BRIEF        Set the corresponding bit in the Wakeup Enable Register - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETWKUENA__INTLINE__SET         0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARDATAOUT__INTLINE__NOEFFECT
 *
 * @BRIEF        No effect - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARDATAOUT__INTLINE__NOEFFECT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_CLEARDATAOUT__INTLINE__CLEAR
 *
 * @BRIEF        Clear the corresponding bit in the Data Output Register - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_CLEARDATAOUT__INTLINE__CLEAR    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETDATAOUT__INTLINE__NOEFFECT
 *
 * @BRIEF        No effect - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETDATAOUT__INTLINE__NOEFFECT   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   GPIO_V2__GPIO_SETDATAOUT__INTLINE__SET
 *
 * @BRIEF        Set the corresponding bit in the Data Output Register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define GPIO_V2__GPIO_SETDATAOUT__INTLINE__SET        0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __GPIO_V2_CRED_H 
                                                            */
