/** ==================================================================
 *  @file   hdmi_ip_core_cec_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   HDMI_IP_CORE_CEC
 *
 *  @Filename:    hdmi_ip_core_cec_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __HDMI_IP_CORE_CEC_CRED_H
#define __HDMI_IP_CORE_CEC_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance DSS_SS_FROM_L4_PER__HDMI__HDMI_IP__HDMI_IP_CORE_CEC of component HDMI_IP_CORE_CEC mapped in MONICA at address 0x48046D00
     * Instance DSS_SS_FROM_L3__HDMI__HDMI_IP__HDMI_IP_CORE_CEC of component HDMI_IP_CORE_CEC mapped in MONICA at address 0x58006D00
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component HDMI_IP_CORE_CEC
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_OPERAND
 *
 * @BRIEF        CEC Tx Operand Registers 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_OPERAND                   0x40ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_OPERAND__ELSIZE
 *
 * @BRIEF        CEC_TX_OPERAND register array element size in Bytes
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_OPERAND__ELSIZE           0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_OPERAND__NELEMS
 *
 * @BRIEF        CEC_TX_OPERAND register array number of elements
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_OPERAND__NELEMS           15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_OPERAND
 *
 * @BRIEF        CEC Rx Operand Registers 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_OPERAND                   0xC0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_OPERAND__ELSIZE
 *
 * @BRIEF        CEC_RX_OPERAND register array element size in Bytes
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_OPERAND__ELSIZE           0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_OPERAND__NELEMS
 *
 * @BRIEF        CEC_RX_OPERAND register array number of elements
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_OPERAND__NELEMS           15

    /* 
     *  List of bundle arrays for component HDMI_IP_CORE_CEC
     *
     */

    /* 
     *  List of bundles for component HDMI_IP_CORE_CEC
     *
     */

    /* 
     * List of registers for component HDMI_IP_CORE_CEC
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DEV_ID
 *
 * @BRIEF        CEC Device ID Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DEV_ID                       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SPEC
 *
 * @BRIEF        CEC Specification Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SPEC                         0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SUFF
 *
 * @BRIEF        CEC Specification Suffix Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SUFF                         0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_FW
 *
 * @BRIEF        CEC Firmware Revision Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_FW                           0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_0
 *
 * @BRIEF        CEC Debug Register0 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_0                        0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_1
 *
 * @BRIEF        CEC Debug Register1 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_1                        0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_2
 *
 * @BRIEF        CEC Debug Register2 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_2                        0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_3
 *
 * @BRIEF        CEC Debug Register3 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_3                        0x1Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_INIT
 *
 * @BRIEF        CEC Tx Initialization Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_INIT                      0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_DEST
 *
 * @BRIEF        CEC Tx Destination Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_DEST                      0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SETUP
 *
 * @BRIEF        CEC Set Up Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SETUP                        0x38ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_COMMAND
 *
 * @BRIEF        CEC Tx Command Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_COMMAND                   0x3Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA
 *
 * @BRIEF        CEC Transmit Data Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA                0x7Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_CA_7_0
 *
 * @BRIEF        CEC Capture ID0 Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_CA_7_0                       0x88ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_CA_15_8
 *
 * @BRIEF        CEC Capture ID0 Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_CA_15_8                      0x8Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0
 *
 * @BRIEF        CEC Interrupt Enable Register0 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0                 0x90ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1
 *
 * @BRIEF        CEC Interrupt Enable Register1 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1                 0x94ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_0
 *
 * @BRIEF        CEC Interrupt Status Register0 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0                 0x98ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_1
 *
 * @BRIEF        CEC Interrupt Status Register1 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1                 0x9Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_CONTROL
 *
 * @BRIEF        CEC RX Control Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_CONTROL                   0xB0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_COUNT
 *
 * @BRIEF        CEC Rx Count Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_COUNT                     0xB4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_CMD_HEADER
 *
 * @BRIEF        CEC Rx Command Header Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_CMD_HEADER                0xB8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_COMMAND
 *
 * @BRIEF        CEC Rx Command Register 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_COMMAND                   0xBCul

    /* 
     * List of register bitfields for component HDMI_IP_CORE_CEC
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DEV_ID__CEC_DEV_ID   
 *
 * @BRIEF        ID of CEC device - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DEV_ID__CEC_DEV_ID      BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_DEV_ID__CEC_DEV_ID__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SPEC__CEC_REL   
 *
 * @BRIEF        CEC Specification major release  - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SPEC__CEC_REL           BITFIELD(7, 4)
#define HDMI_IP_CORE_CEC__CEC_SPEC__CEC_REL__POS      4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SPEC__CEC_REV   
 *
 * @BRIEF        CEC Specification minor release (rev. 1.2) - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SPEC__CEC_REV           BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_SPEC__CEC_REV__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SUFF__SUB_SYS   
 *
 * @BRIEF        Subsytem 
 *               0 = Firmware, 
 *               1 = Hardware, - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SUFF__SUB_SYS           BITFIELD(7, 7)
#define HDMI_IP_CORE_CEC__CEC_SUFF__SUB_SYS__POS      7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SUFF__CEC_SUFF   
 *
 * @BRIEF        CEC Specification Suffix  (0 = a; for rev 1.2a) - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SUFF__CEC_SUFF          BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_SUFF__CEC_SUFF__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_FW__FW_REL_ID   
 *
 * @BRIEF        Firmware Release ID - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_FW__FW_REL_ID           BITFIELD(7, 4)
#define HDMI_IP_CORE_CEC__CEC_FW__FW_REL_ID__POS      4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_FW__FW_REV_ID   
 *
 * @BRIEF        Firmware Revision ID  - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_FW__FW_REV_ID           BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_FW__FW_REV_ID__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_0__STB_LOW_P   
 *
 * @BRIEF        Start Bit Low Period.  Measured in units of 250us.  (RO) 
 *               Expected range is 3.5ms (0x0E)  to 3.9ms (0x0F). - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_0__STB_LOW_P        BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_DBG_0__STB_LOW_P__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_1__STB_DUR_P   
 *
 * @BRIEF        Start Bit Duration Period.  Measured in units of 250us.  
 *               (RO) 
 *               Expected range is 4.3ms (0x11)  to 4.7ms (0x12). - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_1__STB_DUR_P        BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_DBG_1__STB_DUR_P__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_2__CEC_SN_INI   
 *
 * @BRIEF        CEC Snoop Initiator (RW) -   
 *               Values 0000 to 1111. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_2__CEC_SN_INI       BITFIELD(7, 4)
#define HDMI_IP_CORE_CEC__CEC_DBG_2__CEC_SN_INI__POS  4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_2__CEC_BUS_OWN   
 *
 * @BRIEF        Current CEC bus owner (RO) - 
 *               Values 0000 to 1111. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_2__CEC_BUS_OWN      BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_DBG_2__CEC_BUS_OWN__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_3__FL_FIF   
 *
 * @BRIEF        Flush Tx FIFO 
 *               0=No, 
 *               1=Yes, 
 *               Self resetting bit, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_3__FL_FIF           BITFIELD(7, 7)
#define HDMI_IP_CORE_CEC__CEC_DBG_3__FL_FIF__POS      7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_3__FR_RT_CNT   
 *
 * @BRIEF        Frame Retransmit Count 
 *               Values 0 to 5, - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_3__FR_RT_CNT        BITFIELD(6, 4)
#define HDMI_IP_CORE_CEC__CEC_DBG_3__FR_RT_CNT__POS   4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_3__INV_ACK   
 *
 * @BRIEF        Invert ACK to Broadcast Commands 
 *               0 = No, 
 *               1 = Yes, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_3__INV_ACK          BITFIELD(2, 2)
#define HDMI_IP_CORE_CEC__CEC_DBG_3__INV_ACK__POS     2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_3__ACKN_HEAD   
 *
 * @BRIEF        ACK/NACK Header Block 
 *               0 = ACK, 
 *               1 = NACK, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_3__ACKN_HEAD        BITFIELD(1, 1)
#define HDMI_IP_CORE_CEC__CEC_DBG_3__ACKN_HEAD__POS   1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_DBG_3__CEC_SN   
 *
 * @BRIEF        CEC snoop 
 *               0 = disable, 
 *               1 = enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_DBG_3__CEC_SN           BITFIELD(0, 0)
#define HDMI_IP_CORE_CEC__CEC_DBG_3__CEC_SN__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_INIT__CEC_INIT_ID   
 *
 * @BRIEF        CEC Initiator ID - needs to be written to identify this 
 *               device in future transmissions. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_INIT__CEC_INIT_ID    BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_TX_INIT__CEC_INIT_ID__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_DEST__CEC_SD_POLL   
 *
 * @BRIEF        Generate a polling message 
 *               0=No, 
 *               1=yes 
 *               Self resetting bit. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_DEST__CEC_SD_POLL    BITFIELD(7, 7)
#define HDMI_IP_CORE_CEC__CEC_TX_DEST__CEC_SD_POLL__POS 7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_DEST__CEC_DEST_ID   
 *
 * @BRIEF        CEC Destination ID - identifies the target device for the 
 *               command.  Must be written before writing the corresponding 
 *               CEC command. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_DEST__CEC_DEST_ID    BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_TX_DEST__CEC_DEST_ID__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SETUP__CEC_PTRH   
 *
 * @BRIEF        CEC passthru register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SETUP__CEC_PTRH         BITFIELD(4, 4)
#define HDMI_IP_CORE_CEC__CEC_SETUP__CEC_PTRH__POS    4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SETUP__CEC_FORCE_NON_CALIB   
 *
 * @BRIEF        must be set to 1 if calibration is not needed (If a 2MHz 
 *               christal clock is available) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SETUP__CEC_FORCE_NON_CALIB BITFIELD(2, 2)
#define HDMI_IP_CORE_CEC__CEC_SETUP__CEC_FORCE_NON_CALIB__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SETUP__CEC_CAL_EN   
 *
 * @BRIEF        CEC calibration enable register (self clearing) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SETUP__CEC_CAL_EN       BITFIELD(1, 1)
#define HDMI_IP_CORE_CEC__CEC_SETUP__CEC_CAL_EN__POS  1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_SETUP__CEC_CAL_SW   
 *
 * @BRIEF        must be set to 1 for 10 ms in case of calibration - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_SETUP__CEC_CAL_SW       BITFIELD(0, 0)
#define HDMI_IP_CORE_CEC__CEC_SETUP__CEC_CAL_SW__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_COMMAND__CEC_TX_COM   
 *
 * @BRIEF        CEC Tx command - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_COMMAND__CEC_TX_COM  BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_TX_COMMAND__CEC_TX_COM__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TX_OPERAND__CEC_TX_OP   
 *
 * @BRIEF        CEC Tx Operand - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TX_OPERAND__CEC_TX_OP   BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_TX_OPERAND__CEC_TX_OP__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_BFR_ACC   
 *
 * @BRIEF        Read back internal buffer contents from 0x8F-0x9E 
 *               0 = No, 
 *               1 = Yes, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_BFR_ACC BITFIELD(6, 6)
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_BFR_ACC__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_AUT_CALC   
 *
 * @BRIEF        Auto-Calculate TX_CNT and send 
 *               0 = No, 
 *               1 = Yes, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_AUT_CALC BITFIELD(5, 5)
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_AUT_CALC__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TRA_CEC_CMD   
 *
 * @BRIEF        Send CEC Command and TX_CNT Operands 
 *               0 = No, 
 *               1 = Yes, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TRA_CEC_CMD BITFIELD(4, 4)
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TRA_CEC_CMD__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_CNT   
 *
 * @BRIEF        Transmit Byte Count - selects the number of CEC_TX_OPERAND 
 *               bytes to send with the command. 
 *               0000 = No operands, 
 *               0001 = one operand, 
 *               . . . . . . 
 *               1111 = 15 operands, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_CNT   BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_TRANSMIT_DATA__TX_CNT__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_CA_7_0__CEC_CAP_ID   
 *
 * @BRIEF        The CEC Capture ID register is separate from the CEC 
 *               Initiator ID.  It selects the received commands that will be 
 *               captured in the receive FIFO and acknowledged.  If the 
 *               command destination matches one of the bits set in this 
 *               register or is a Broadcast cycle; it will be captured.   - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_CA_7_0__CEC_CAP_ID      BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_CA_7_0__CEC_CAP_ID__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_CA_15_8__CEC_CAP_ID   
 *
 * @BRIEF        The CEC Capture ID register is separate from the CEC 
 *               Initiator ID.  It selects the received commands that will be 
 *               captured in the receive FIFO and acknowledged.  If the 
 *               command destination matches one of the bits set in this 
 *               register or is a Broadcast cycle; it will be captured.   - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_CA_15_8__CEC_CAP_ID     BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_CA_15_8__CEC_CAP_ID__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK5   
 *
 * @BRIEF        Tx: Transmit Buffer Full/Empty Change event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK5 BITFIELD(5, 5)
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK5__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK2   
 *
 * @BRIEF        Transmitter FIFO Empty event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK2 BITFIELD(2, 2)
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK2__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK1   
 *
 * @BRIEF        Receiver FIFO Not Empty event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK1 BITFIELD(1, 1)
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK0   
 *
 * @BRIEF        Command Being Received event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK0 BITFIELD(0, 0)
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_0__CEC_INTR1_MASK0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK3   
 *
 * @BRIEF        Rx FIFO Overrun Error event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK3 BITFIELD(3, 3)
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK3__POS 3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK2   
 *
 * @BRIEF        Short Pulse Detected event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK2 BITFIELD(2, 2)
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK2__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK1   
 *
 * @BRIEF        Frame Retransmit Count Exceeded event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK1 BITFIELD(1, 1)
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK0   
 *
 * @BRIEF        Start Bit Irregularity event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK0 BITFIELD(0, 0)
#define HDMI_IP_CORE_CEC__CEC_INT_ENABLE_1__CEC_INTR2_MASK0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_LSTAT   
 *
 * @BRIEF        CEC line current state 0 = Low 
 *               1 = High, - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_LSTAT BITFIELD(7, 7)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_LSTAT__POS 7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__TFIF_BFULL   
 *
 * @BRIEF        Tx FIFO Transmit Buffer Full 
 *               0=No, 
 *               1=Yes, - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__TFIF_BFULL BITFIELD(6, 6)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__TFIF_BFULL__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT4   
 *
 * @BRIEF        Tx: Transmit Buffer Full/Empty Change event Pending 
 *               0=no, 
 *               1=yes, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT4 BITFIELD(5, 5)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT4__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT2   
 *
 * @BRIEF        Transmitter FIFO Empty event pending 
 *               0=No, 
 *               1=Yes, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT2 BITFIELD(2, 2)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT2__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT1   
 *
 * @BRIEF        Receiver FIFO Not Empty event pending 
 *               0=No, 
 *               1=Yes, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT1 BITFIELD(1, 1)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT0   
 *
 * @BRIEF        Command Being Received event pending 
 *               0=No, 
 *               1=Yes, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT0 BITFIELD(0, 0)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_0__CEC_INTR1_STAT0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT3   
 *
 * @BRIEF        Rx FIFO Overrun Error event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT3 BITFIELD(3, 3)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT3__POS 3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT2   
 *
 * @BRIEF        Short Pulse Detected event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT2 BITFIELD(2, 2)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT2__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT1   
 *
 * @BRIEF        Frame Retransmit Count Exceeded event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT1 BITFIELD(1, 1)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT1__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT0   
 *
 * @BRIEF        Start Bit Irregularity event 
 *               0=Disable, 
 *               1=Enable, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT0 BITFIELD(0, 0)
#define HDMI_IP_CORE_CEC__CEC_INT_STATUS_1__CEC_INTR2_STAT0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_CONTROL__CLR_RX_FIF_ALL   
 *
 * @BRIEF        Clear All Frames from Rx FIFO 
 *               0 = No, 
 *               1 = Yes, 
 *               Self-resetting bit, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_CONTROL__CLR_RX_FIF_ALL BITFIELD(1, 1)
#define HDMI_IP_CORE_CEC__CEC_RX_CONTROL__CLR_RX_FIF_ALL__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_CONTROL__CLR_RX_FIF_CUR   
 *
 * @BRIEF        Clear Current Frame from Rx FIFO 
 *               0 = No, 
 *               1 = Yes, 
 *               Self-resetting bit, - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_CONTROL__CLR_RX_FIF_CUR BITFIELD(0, 0)
#define HDMI_IP_CORE_CEC__CEC_RX_CONTROL__CLR_RX_FIF_CUR__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_COUNT__RX_ERROR   
 *
 * @BRIEF        Error associated with this message 
 *               0=No, 
 *               1=yes , - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_COUNT__RX_ERROR      BITFIELD(7, 7)
#define HDMI_IP_CORE_CEC__CEC_RX_COUNT__RX_ERROR__POS 7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_COUNT__CEC_RX_CMD_CNT   
 *
 * @BRIEF        CEC Receive FIFO Frame Count - returns the number of frames 
 *               awaiting reading in the FIFO; 0-3. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_COUNT__CEC_RX_CMD_CNT BITFIELD(6, 4)
#define HDMI_IP_CORE_CEC__CEC_RX_COUNT__CEC_RX_CMD_CNT__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_COUNT__CEC_RX_BYTE_CNT   
 *
 * @BRIEF        CEC Receive Byte Count - returns the number of operands in 
 *               the current frame. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_COUNT__CEC_RX_BYTE_CNT BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_RX_COUNT__CEC_RX_BYTE_CNT__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_CMD_HEADER__CEC_RX_INIT   
 *
 * @BRIEF        CEC Initiator ID - identifies 
 *               the initiator of the current frame. , - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_CMD_HEADER__CEC_RX_INIT BITFIELD(7, 4)
#define HDMI_IP_CORE_CEC__CEC_RX_CMD_HEADER__CEC_RX_INIT__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_CMD_HEADER__CEC_RX_DEST   
 *
 * @BRIEF        CEC Destination ID - identifies 
 *               the intended target of the current frame. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_CMD_HEADER__CEC_RX_DEST BITFIELD(3, 0)
#define HDMI_IP_CORE_CEC__CEC_RX_CMD_HEADER__CEC_RX_DEST__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_COMMAND__CEC_RX_COM   
 *
 * @BRIEF        CEC Rx command - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_COMMAND__CEC_RX_COM  BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_RX_COMMAND__CEC_RX_COM__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMI_IP_CORE_CEC__CEC_RX_OPERAND__CEC_RX_OP   
 *
 * @BRIEF        CEC Rx Operand - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMI_IP_CORE_CEC__CEC_RX_OPERAND__CEC_RX_OP   BITFIELD(7, 0)
#define HDMI_IP_CORE_CEC__CEC_RX_OPERAND__CEC_RX_OP__POS 0

    /* 
     * List of register bitfields values for component HDMI_IP_CORE_CEC
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __HDMI_IP_CORE_CEC_CRED_H 
                                                            */
