/** ==================================================================
 *  @file   hdmitxphy_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   HDMITXPHY
 *
 *  @Filename:    hdmitxphy_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __HDMITXPHY_CRED_H
#define __HDMITXPHY_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance DSS_SS_FROM_L4_PER__HDMI__HDMI_PHY of component HDMITXPHY mapped in MONICA at address 0x48046300
     * Instance DSS_SS_FROM_L3__HDMI__HDMI_PHY of component HDMITXPHY mapped in MONICA at address 0x58006300
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component HDMITXPHY
     *
     */

    /* 
     *  List of bundle arrays for component HDMITXPHY
     *
     */

    /* 
     *  List of bundles for component HDMITXPHY
     *
     */

    /* 
     * List of registers for component HDMITXPHY
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL
 *
 * @BRIEF        Sets performace parameters of the transmitter 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL                              0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DIGITAL_CONTROL
 *
 * @BRIEF        Provides control of the digital logic in the PHY 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DIGITAL_CONTROL                         0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL
 *
 * @BRIEF        Configures power management parameters of the PHY 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL                           0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL
 *
 * @BRIEF        Configures output channel assignments and provides detection 
 *               info 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL                      0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TRIM_AND_TEST_CONTROL
 *
 * @BRIEF        Control for trim and trim bits 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TRIM_AND_TEST_CONTROL                   0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL
 *
 * @BRIEF        Analog characterization and debug options 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL                0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DATA_INTERFACE_CONTROL
 *
 * @BRIEF        Option to override the data to transmit 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DATA_INTERFACE_CONTROL                  0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL
 *
 * @BRIEF        Configuration for built in self test 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL                            0x1Cul

    /* 
     * List of register bitfields for component HDMITXPHY
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__FREQOUT   
 *
 * @BRIEF        These bits are used to indicate to the TX the TMDSCLK 
 *               operating frequency - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__FREQOUT                BITFIELD(31, 30)
#define HDMITXPHY__TX_CONTROL__FREQOUT__POS           30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__SRCTERMCNTL   
 *
 * @BRIEF        TBD. Currently source 
 *               side termination is not implemented - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__SRCTERMCNTL            BITFIELD(29, 28)
#define HDMITXPHY__TX_CONTROL__SRCTERMCNTL__POS       28

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__EMPEN_D0   
 *
 * @BRIEF        Enables de emphasis - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__EMPEN_D0               BITFIELD(27, 27)
#define HDMITXPHY__TX_CONTROL__EMPEN_D0__POS          27

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__EMPEN_D1   
 *
 * @BRIEF        Enables de emphasis - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__EMPEN_D1               BITFIELD(26, 26)
#define HDMITXPHY__TX_CONTROL__EMPEN_D1__POS          26

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__EMPEN_D2   
 *
 * @BRIEF        Enables de emphasis - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__EMPEN_D2               BITFIELD(25, 25)
#define HDMITXPHY__TX_CONTROL__EMPEN_D2__POS          25

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__EMPEN_CLK   
 *
 * @BRIEF        Enables de emphasis - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__EMPEN_CLK              BITFIELD(24, 24)
#define HDMITXPHY__TX_CONTROL__EMPEN_CLK__POS         24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__PROGEM_D0   
 *
 * @BRIEF        These bits are for different programming 
 *               of the de-emphasis values - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__PROGEM_D0              BITFIELD(23, 21)
#define HDMITXPHY__TX_CONTROL__PROGEM_D0__POS         21

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__PROGEM_D1   
 *
 * @BRIEF        These bits are for different programming 
 *               of the de-emphasis values - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__PROGEM_D1              BITFIELD(20, 18)
#define HDMITXPHY__TX_CONTROL__PROGEM_D1__POS         18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__PROGEM_D2   
 *
 * @BRIEF        These bits are for different programming 
 *               of the de-emphasis values - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__PROGEM_D2              BITFIELD(17, 15)
#define HDMITXPHY__TX_CONTROL__PROGEM_D2__POS         15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__PROGEM_CLK   
 *
 * @BRIEF        These bits are for different programming of the de-emphasis 
 *               values - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__PROGEM_CLK             BITFIELD(14, 12)
#define HDMITXPHY__TX_CONTROL__PROGEM_CLK__POS        12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__SLOWEDGE_D0   
 *
 * @BRIEF        Rise time increase control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__SLOWEDGE_D0            BITFIELD(11, 10)
#define HDMITXPHY__TX_CONTROL__SLOWEDGE_D0__POS       10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__SLOWEDGE_D1   
 *
 * @BRIEF        Rise time increase control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__SLOWEDGE_D1            BITFIELD(9, 8)
#define HDMITXPHY__TX_CONTROL__SLOWEDGE_D1__POS       8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__SLOWEDGE_D2   
 *
 * @BRIEF        Rise time increase control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__SLOWEDGE_D2            BITFIELD(7, 6)
#define HDMITXPHY__TX_CONTROL__SLOWEDGE_D2__POS       6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__SLOWEDGE_CLK   
 *
 * @BRIEF        Rise time increase control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__SLOWEDGE_CLK           BITFIELD(5, 4)
#define HDMITXPHY__TX_CONTROL__SLOWEDGE_CLK__POS      4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__TXLOWCM   
 *
 * @BRIEF        Indicates presence of low common mode at output - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__TXLOWCM                BITFIELD(3, 3)
#define HDMITXPHY__TX_CONTROL__TXLOWCM__POS           3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TX_CONTROL__TXLOWI   
 *
 * @BRIEF        Driver current reduction control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TX_CONTROL__TXLOWI                 BITFIELD(2, 1)
#define HDMITXPHY__TX_CONTROL__TXLOWI__POS            1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DIGITAL_CONTROL__USE_TMDSCLKEN   
 *
 * @BRIEF        TMDSCLKEN, use bit 30 from this register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DIGITAL_CONTROL__USE_TMDSCLKEN     BITFIELD(31, 31)
#define HDMITXPHY__DIGITAL_CONTROL__USE_TMDSCLKEN__POS 31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DIGITAL_CONTROL__TMDSCLKEN   
 *
 * @BRIEF        TMDSCLEN signal - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DIGITAL_CONTROL__TMDSCLKEN         BITFIELD(30, 30)
#define HDMITXPHY__DIGITAL_CONTROL__TMDSCLKEN__POS    30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DIGITAL_CONTROL__USE_TXVALID   
 *
 * @BRIEF        Use bit 28 from this register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DIGITAL_CONTROL__USE_TXVALID       BITFIELD(29, 29)
#define HDMITXPHY__DIGITAL_CONTROL__USE_TXVALID__POS  29

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DIGITAL_CONTROL__TXVALID   
 *
 * @BRIEF        TXVALID override with the external pin - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DIGITAL_CONTROL__TXVALID           BITFIELD(28, 28)
#define HDMITXPHY__DIGITAL_CONTROL__TXVALID__POS      28

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__FORCELDOON   
 *
 * @BRIEF        Powers up the LDO - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__FORCELDOON          BITFIELD(31, 31)
#define HDMITXPHY__POWER_CONTROL__FORCELDOON__POS     31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__LDO_POWERUP_COUNTER   
 *
 * @BRIEF        This is the counter that dictates 
 *               the LDO powerup time - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__LDO_POWERUP_COUNTER BITFIELD(30, 24)
#define HDMITXPHY__POWER_CONTROL__LDO_POWERUP_COUNTER__POS 24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__BGON_COUNTER   
 *
 * @BRIEF        BGON counter compare value - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__BGON_COUNTER        BITFIELD(23, 19)
#define HDMITXPHY__POWER_CONTROL__BGON_COUNTER__POS   19

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__RESETDONEPIXELCLK   
 *
 * @BRIEF        Reset done signal - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__RESETDONEPIXELCLK   BITFIELD(17, 17)
#define HDMITXPHY__POWER_CONTROL__RESETDONEPIXELCLK__POS 17

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__RESETDONEPWRCLK   
 *
 * @BRIEF        Reset done signal - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__RESETDONEPWRCLK     BITFIELD(16, 16)
#define HDMITXPHY__POWER_CONTROL__RESETDONEPWRCLK__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__RESETDONESCPCLK   
 *
 * @BRIEF        Reset done signal - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__RESETDONESCPCLK     BITFIELD(15, 15)
#define HDMITXPHY__POWER_CONTROL__RESETDONESCPCLK__POS 15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__RESETDONEREFCLK   
 *
 * @BRIEF        Reset done signal - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__RESETDONEREFCLK     BITFIELD(14, 14)
#define HDMITXPHY__POWER_CONTROL__RESETDONEREFCLK__POS 14

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__TBIAS_COUNTER   
 *
 * @BRIEF        This value is counted down for determining LDOON to TXON 
 *               timing. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__TBIAS_COUNTER       BITFIELD(13, 7)
#define HDMITXPHY__POWER_CONTROL__TBIAS_COUNTER__POS  7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__TEST_EN_LDO_FORCE   
 *
 * @BRIEF        Puts the LDO output in high impedance state so that it can 
 *               be externally forced - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__TEST_EN_LDO_FORCE   BITFIELD(6, 6)
#define HDMITXPHY__POWER_CONTROL__TEST_EN_LDO_FORCE__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__TEST_EN_BG_FORCE   
 *
 * @BRIEF        Enables forcing of the bandgap output externally - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__TEST_EN_BG_FORCE    BITFIELD(5, 5)
#define HDMITXPHY__POWER_CONTROL__TEST_EN_BG_FORCE__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__TEST_EN_SC_FORCE   
 *
 * @BRIEF        Enables forcing of the switched capacitor reference current 
 *               externally - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__TEST_EN_SC_FORCE    BITFIELD(4, 4)
#define HDMITXPHY__POWER_CONTROL__TEST_EN_SC_FORCE__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__POWER_CONTROL__LDOVOLTAGE   
 *
 * @BRIEF        These bits are used to control the LDO based on the 
 *               operating frequency - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__POWER_CONTROL__LDOVOLTAGE          BITFIELD(3, 0)
#define HDMITXPHY__POWER_CONTROL__LDOVOLTAGE__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__PADORDER   
 *
 * @BRIEF        Corresponds to the pin named PADORDER. Internally PADORDER 
 *               is an ?or? of the pin and register value. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__PADORDER       BITFIELD(31, 31)
#define HDMITXPHY__PAD_CONFIG_CONTROL__PADORDER__POS  31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D0   
 *
 * @BRIEF        Polarity control for channel D0 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D0 BITFIELD(30, 30)
#define HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D0__POS 30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D1   
 *
 * @BRIEF        Polarity control for channel D1 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D1 BITFIELD(29, 29)
#define HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D1__POS 29

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D2   
 *
 * @BRIEF        Polarity control for channel D2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D2 BITFIELD(28, 28)
#define HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_D2__POS 28

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_CLK   
 *
 * @BRIEF        Polarity control for channel CLK - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_CLK BITFIELD(27, 27)
#define HDMITXPHY__PAD_CONFIG_CONTROL__FLIP_P_N_ORDER_CLK__POS 27

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__ASSIGN_CH   
 *
 * @BRIEF        Sekects output channel ordering - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__ASSIGN_CH      BITFIELD(26, 22)
#define HDMITXPHY__PAD_CONFIG_CONTROL__ASSIGN_CH__POS 22

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__DET5VSHT_CLK   
 *
 * @BRIEF        Becomes ?1? if a 5V short is detected on CLKP ? CLKM in that 
 *               order. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__DET5VSHT_CLK   BITFIELD(19, 18)
#define HDMITXPHY__PAD_CONFIG_CONTROL__DET5VSHT_CLK__POS 18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__VTHRESHPU_CNTL   
 *
 * @BRIEF        The threshold for detection of pull-up on the data and clk 
 *               lines - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__VTHRESHPU_CNTL BITFIELD(17, 16)
#define HDMITXPHY__PAD_CONFIG_CONTROL__VTHRESHPU_CNTL__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__FORCE_RXDET_HIGH   
 *
 * @BRIEF        0 -> the RX detect is active.1 -> the RXDET pin is always 
 *               forced to ?1?. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__FORCE_RXDET_HIGH BITFIELD(15, 15)
#define HDMITXPHY__PAD_CONFIG_CONTROL__FORCE_RXDET_HIGH__POS 15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__RXDET_LINE   
 *
 * @BRIEF        The 3V detect bits on each of the lines? in the order 
 *               DATA2P, DATA2M, DATA1P,DATA1M,DATA0P, DATA0M,CLKP,CLKM - 
 *               (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__RXDET_LINE     BITFIELD(14, 7)
#define HDMITXPHY__PAD_CONFIG_CONTROL__RXDET_LINE__POS 7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__PAD_CONFIG_CONTROL__DET5VSHT_DATA   
 *
 * @BRIEF        Bits become ?1? respectively for shorts 
 *               on (in the order below) ? DATA2P, 
 *               DATA2M, DATA1P,DATA1M,DATA0P, DATA0M - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__PAD_CONFIG_CONTROL__DET5VSHT_DATA  BITFIELD(6, 1)
#define HDMITXPHY__PAD_CONFIG_CONTROL__DET5VSHT_DATA__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_BGTRIM_REG   
 *
 * @BRIEF        Use bits 30-16 of this register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_BGTRIM_REG BITFIELD(31, 31)
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_BGTRIM_REG__POS 31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TRIM_AND_TEST_CONTROL__BGTRIM   
 *
 * @BRIEF        The bandgap trim settings - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__BGTRIM      BITFIELD(30, 16)
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__BGTRIM__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_SWTRIM_REG   
 *
 * @BRIEF        Use bits 14-9 of this register for switch cap trim settings 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_SWTRIM_REG BITFIELD(15, 15)
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_SWTRIM_REG__POS 15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TRIM_AND_TEST_CONTROL__SWTRIM   
 *
 * @BRIEF        The switch cap trim settings - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__SWTRIM      BITFIELD(14, 8)
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__SWTRIM__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TRIM_AND_TEST_CONTROL__TRIMMODE_BG   
 *
 * @BRIEF        Enables trimming of bandgap voltage. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__TRIMMODE_BG BITFIELD(7, 7)
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__TRIMMODE_BG__POS 7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TRIM_AND_TEST_CONTROL__TRIMMODE_SC   
 *
 * @BRIEF        Enables trimming of switched cap current - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__TRIMMODE_SC BITFIELD(6, 6)
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__TRIMMODE_SC__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_TRIMMODE_REGS   
 *
 * @BRIEF        Use bits 6 and 7 from this register. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_TRIMMODE_REGS BITFIELD(5, 5)
#define HDMITXPHY__TRIM_AND_TEST_CONTROL__USE_TRIMMODE_REGS__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__ANALOG_DEBUG   
 *
 * @BRIEF        Sets the AFE into various debug modes - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__ANALOG_DEBUG BITFIELD(31, 16)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__ANALOG_DEBUG__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__USELDOPGD_REG   
 *
 * @BRIEF        USE bits from bit 14-11 of this reg - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__USELDOPGD_REG BITFIELD(15, 15)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__USELDOPGD_REG__POS 15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__LDOPGD   
 *
 * @BRIEF        Override value of analog interface signal LDOPGD - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__LDOPGD   BITFIELD(14, 14)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__LDOPGD__POS 14

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__BGON   
 *
 * @BRIEF        Override value of analog interface signal BGON - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__BGON     BITFIELD(13, 13)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__BGON__POS 13

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__TXON   
 *
 * @BRIEF        Override the TXON signal going to the afe - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__TXON     BITFIELD(12, 12)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__TXON__POS 12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__TXONDELAYED   
 *
 * @BRIEF        Override the txondelayed signal going tothe afe. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__TXONDELAYED BITFIELD(11, 11)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__TXONDELAYED__POS 11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__USE_CLOCKLANEPOS   
 *
 * @BRIEF        Use bit 9-8 in this register as override - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__USE_CLOCKLANEPOS BITFIELD(10, 10)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__USE_CLOCKLANEPOS__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__CLOCK_LANE_POS   
 *
 * @BRIEF        Override settings for the 
 *               CLOCK_LANE_POS pins to the afe - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__CLOCK_LANE_POS BITFIELD(9, 8)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__CLOCK_LANE_POS__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__ANALOG_INTERFACE_CONTROL__ANALOG_CHAR   
 *
 * @BRIEF        Analog characterization controls. TBD - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__ANALOG_CHAR BITFIELD(7, 0)
#define HDMITXPHY__ANALOG_INTERFACE_CONTROL__ANALOG_CHAR__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DATA_INTERFACE_CONTROL__USE_DATA_REG   
 *
 * @BRIEF        Use the interface override values from this 
 *               register instead of the interface - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DATA_INTERFACE_CONTROL__USE_DATA_REG BITFIELD(31, 31)
#define HDMITXPHY__DATA_INTERFACE_CONTROL__USE_DATA_REG__POS 31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DATA_INTERFACE_CONTROL__D0_OVERRIDE   
 *
 * @BRIEF        Override D0<9:0> - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DATA_INTERFACE_CONTROL__D0_OVERRIDE BITFIELD(30, 21)
#define HDMITXPHY__DATA_INTERFACE_CONTROL__D0_OVERRIDE__POS 21

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DATA_INTERFACE_CONTROL__D1_OVERRIDE   
 *
 * @BRIEF        Override D1<9:0> - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DATA_INTERFACE_CONTROL__D1_OVERRIDE BITFIELD(19, 10)
#define HDMITXPHY__DATA_INTERFACE_CONTROL__D1_OVERRIDE__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__DATA_INTERFACE_CONTROL__D2_OVERRIDE   
 *
 * @BRIEF        Override D2<9:0> - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__DATA_INTERFACE_CONTROL__D2_OVERRIDE BITFIELD(9, 0)
#define HDMITXPHY__DATA_INTERFACE_CONTROL__D2_OVERRIDE__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__USE_LDOBIST_CTRL   
 *
 * @BRIEF        Use bit 30 from this reg. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__USE_LDOBIST_CTRL     BITFIELD(31, 31)
#define HDMITXPHY__BIST_CONTROL__USE_LDOBIST_CTRL__POS 31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__LDOBIST_CTRL   
 *
 * @BRIEF        Set the ldo bist mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__LDOBIST_CTRL         BITFIELD(30, 30)
#define HDMITXPHY__BIST_CONTROL__LDOBIST_CTRL__POS    30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__LDO_BIST_OK1   
 *
 * @BRIEF        Output of ldo bist comp 1 - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__LDO_BIST_OK1         BITFIELD(29, 29)
#define HDMITXPHY__BIST_CONTROL__LDO_BIST_OK1__POS    29

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__LDO_BIST_OK2   
 *
 * @BRIEF        Output of ldo bist comp 2 - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__LDO_BIST_OK2         BITFIELD(28, 28)
#define HDMITXPHY__BIST_CONTROL__LDO_BIST_OK2__POS    28

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__USE_LB_MODE   
 *
 * @BRIEF        Use bit 26 from this reg - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__USE_LB_MODE          BITFIELD(27, 27)
#define HDMITXPHY__BIST_CONTROL__USE_LB_MODE__POS     27

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__LB_MODE   
 *
 * @BRIEF        Set the loopback mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__LB_MODE              BITFIELD(26, 26)
#define HDMITXPHY__BIST_CONTROL__LB_MODE__POS         26

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__LB_COMP   
 *
 * @BRIEF        Loopback comparator output - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__LB_COMP              BITFIELD(25, 25)
#define HDMITXPHY__BIST_CONTROL__LB_COMP__POS         25

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__USE_LB_LANE_SEL   
 *
 * @BRIEF        Use bits 23-22 from this register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__USE_LB_LANE_SEL      BITFIELD(24, 24)
#define HDMITXPHY__BIST_CONTROL__USE_LB_LANE_SEL__POS 24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__LB_LANE_SEL   
 *
 * @BRIEF        Select the lane for loopback - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__LB_LANE_SEL          BITFIELD(23, 22)
#define HDMITXPHY__BIST_CONTROL__LB_LANE_SEL__POS     22

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   HDMITXPHY__BIST_CONTROL__PRBS_EN   
 *
 * @BRIEF        Enables PRBS transmission on selected lane - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define HDMITXPHY__BIST_CONTROL__PRBS_EN              BITFIELD(21, 18)
#define HDMITXPHY__BIST_CONTROL__PRBS_EN__POS         18

    /* 
     * List of register bitfields values for component HDMITXPHY
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __HDMITXPHY_CRED_H 
                                                            */
