/** ==================================================================
 *  @file   icecruscher_ducati_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   ICECRUSCHER_DUCATI
 *
 *  @Filename:    icecruscher_ducati_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __ICECRUSCHER_DUCATI_CRED_H
#define __ICECRUSCHER_DUCATI_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance ICECRUSCHER_CPU1 of component ICECRUSCHER_DUCATI mapped in MONICA at address 0xE0042000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component ICECRUSCHER_DUCATI
     *
     */

    /* 
     *  List of bundle arrays for component ICECRUSCHER_DUCATI
     *
     */

    /* 
     *  List of bundles for component ICECRUSCHER_DUCATI
     *
     */

    /* 
     * List of registers for component ICECRUSCHER_DUCATI
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ICECRUSCHER_DUCATI__START_ADDRESS_ICEC
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define ICECRUSCHER_DUCATI__START_ADDRESS_ICEC             0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ICECRUSCHER_DUCATI__END_ADDRESS_ICEC
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define ICECRUSCHER_DUCATI__END_ADDRESS_ICEC               0xFFCul

    /* 
     * List of register bitfields for component ICECRUSCHER_DUCATI
     *
     */

    /* 
     * List of register bitfields values for component ICECRUSCHER_DUCATI
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __ICECRUSCHER_DUCATI_CRED_H 
                                                            */
