/** ==================================================================
 *  @file   ipe3_mmr_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   IPE3_MMR
 *
 *  @Filename:    ipe3_mmr_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __IPE3_MMR_CRED_H
#define __IPE3_MMR_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance IPE3_CFG__MMR of component IPE3_MMR mapped in MONICA at address 0x5A058800
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component IPE3_MMR
     *
     */

    /* 
     *  List of bundle arrays for component IPE3_MMR
     *
     */

    /* 
     *  List of bundles for component IPE3_MMR
     *
     */

    /* 
     * List of registers for component IPE3_MMR
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_PID
 *
 * @BRIEF        Peripheral ID Register 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_PID                                  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_COUNT
 *
 * @BRIEF        IPE cycle counter register 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_COUNT                                0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_CTRL
 *
 * @BRIEF        IPE control register 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_CTRL                                 0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NS
 *
 * @BRIEF        Horizontal noise suppression register 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NS                                   0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA
 *
 * @BRIEF        nA mode register 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA                                   0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T0
 *
 * @BRIEF        Luma left neighboring data 
 *               IPE3 read this register value as luma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T0                              0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T1
 *
 * @BRIEF        Luma left neighboring data 
 *               IPE3 read this register value as luma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T1                              0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T2
 *
 * @BRIEF        Luma left neighboring data 
 *               IPE3 read this register value as luma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T2                              0x1Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T3
 *
 * @BRIEF        Luma left neighboring data 
 *               IPE3 read this register value as luma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T3                              0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B0
 *
 * @BRIEF        Luma left neighboring data 
 *               IPE3 read this register value as luma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B0                              0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B1
 *
 * @BRIEF        Luma left neighboring data 
 *               IPE3 read this register value as luma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B1                              0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B2
 *
 * @BRIEF        Luma left neighboring data 
 *               IPE3 read this register value as luma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B2                              0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B3
 *
 * @BRIEF        Luma left neighboring data 
 *               IPE3 read this register value as luma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B3                              0x30ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T0
 *
 * @BRIEF        Chroma left neighboring data 
 *               IPE3 read this register value as chroma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T0                              0x34ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T1
 *
 * @BRIEF        Chroma left neighboring data 
 *               IPE3 read this register value as chroma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T1                              0x38ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T2
 *
 * @BRIEF        Chroma left neighboring data 
 *               IPE3 read this register value as chroma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T2                              0x3Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T3
 *
 * @BRIEF        Chroma left neighboring data 
 *               IPE3 read this register value as chroma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T3                              0x40ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B0
 *
 * @BRIEF        Chroma left neighboring data 
 *               IPE3 read this register value as chroma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B0                              0x44ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B1
 *
 * @BRIEF        Chroma left neighboring data 
 *               IPE3 read this register value as chroma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B1                              0x48ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B2
 *
 * @BRIEF        Chroma left neighboring data 
 *               IPE3 read this register value as chroma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B2                              0x4Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B3
 *
 * @BRIEF        Chroma left neighboring data 
 *               IPE3 read this register value as chroma left samples at the 
 *               beggining of estimation. Also right-most current pixels are 
 *               written at the ending of estimation to use data as left 
 *               sample of next macroblock. 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B3                              0x50ul

    /* 
     * List of register bitfields for component IPE3_MMR
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_PID__IPE_PID   
 *
 * @BRIEF        Peripheral ID register. !!!Note this value is not defined 
 *               yet!!! - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_PID__IPE_PID                    BITFIELD(31, 0)
#define IPE3_MMR__IPE_PID__IPE_PID__POS               0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_COUNT__CNT_EN   
 *
 * @BRIEF        Counter enable 
 *               0: benchmark counter is disabled 
 *               1: benchmark counter is enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_COUNT__CNT_EN                   BITFIELD(31, 31)
#define IPE3_MMR__IPE_COUNT__CNT_EN__POS              31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_COUNT__CNT_RST   
 *
 * @BRIEF        Counter reset 
 *               0: no effect 
 *               1: clear the benchmark counter to 0 - (WO) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_COUNT__CNT_RST                  BITFIELD(30, 30)
#define IPE3_MMR__IPE_COUNT__CNT_RST__POS             30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_COUNT__CNT_VALUE   
 *
 * @BRIEF        Current value of the benchmark counter 
 *               When CNT_EN is '1' and IP is busy ( IPE_EN==1 ), the 
 *               benchmark counter counts up based on clk. Write access has 
 *               no effect. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_COUNT__CNT_VALUE                BITFIELD(15, 0)
#define IPE3_MMR__IPE_COUNT__CNT_VALUE__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_CTRL__IPE_ADDR   
 *
 * @BRIEF        Address of parameter set 
 *               Parameter set can have 4 position in full view mode and 2 
 *               position for ping-pong view mode. User should be set the 
 *               position to be processed. 
 *               0x0: Process 1st MB 
 *               0x1: Process 2nd MB 
 *               0x2: Process 3rd MB  (Only full view mode) 
 *               0x3: Process 4th MB  (Only full view mode) 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_CTRL__IPE_ADDR                  BITFIELD(19, 18)
#define IPE3_MMR__IPE_CTRL__IPE_ADDR__POS             18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_CTRL__IPE_SSM   
 *
 * @BRIEF        Single Step Mode 
 *               This bit is set single mode. The single step mode stops 
 *               processigng even if continuous mode is set. 
 *               0: normal mode 
 *               1: single step mode 
 *               Do not write any value during IPE is running ( during IPE_EN 
 *               is '1' ) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_CTRL__IPE_SSM                   BITFIELD(2, 2)
#define IPE3_MMR__IPE_CTRL__IPE_SSM__POS              2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_CTRL__IPE_EN   
 *
 * @BRIEF        IPE start and status 
 *               Setting this bit to '1' makes IPE start processing. This bit 
 *               remains '1' while IPE is running and is cleared to '0' 
 *               automatically after the completion of the processing. 
 *               Writing '0' to this bit has no effect. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_CTRL__IPE_EN                    BITFIELD(0, 0)
#define IPE3_MMR__IPE_CTRL__IPE_EN__POS               0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NS__NS1   
 *
 * @BRIEF        Bottom block status for horizontal noise suppression. 
 *               0: activity is not higher than H_threshold 
 *               1: activity is higher than H_threshold 
 *               User can update the value if want. IPE module uses the value 
 *               for processing of next parameter set. No update at noise 
 *               suppression disable and SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NS__NS1                         BITFIELD(1, 1)
#define IPE3_MMR__IPE_NS__NS1__POS                    1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NS__NS0   
 *
 * @BRIEF        Top block status for horizontal noise suppression. 
 *               0: activity is not higher than H_threshold 
 *               1: activity is higher than H_threshold 
 *               User can update the value if want. IPE module uses the value 
 *               for processing of next parameter set. No update at noise 
 *               suppression disable and SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NS__NS0                         BITFIELD(0, 0)
#define IPE3_MMR__IPE_NS__NS0__POS                    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA__PRED_NA7   
 *
 * @BRIEF        Intra prediction mode of 4x4 block #15 of bottom macroblock 
 *               in the previous macroblock pair. 
 *               IPE3 doesn't update at SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA__PRED_NA7                    BITFIELD(31, 28)
#define IPE3_MMR__IPE_NA__PRED_NA7__POS               28

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA__PRED_NA6   
 *
 * @BRIEF        Intra prediction mode of 4x4 block #13 of bottom macroblock 
 *               in the previous macroblock pair. 
 *               IPE3 doesn't update at SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA__PRED_NA6                    BITFIELD(27, 24)
#define IPE3_MMR__IPE_NA__PRED_NA6__POS               24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA__PRED_NA5   
 *
 * @BRIEF        Intra prediction mode of 4x4 block #7 of bottom macroblock 
 *               in the previous macroblock pair. 
 *               IPE3 doesn't update at SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA__PRED_NA5                    BITFIELD(23, 20)
#define IPE3_MMR__IPE_NA__PRED_NA5__POS               20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA__PRED_NA4   
 *
 * @BRIEF        Intra prediction mode of 4x4 block #5 of bottom macroblock 
 *               in the previous macroblock pair. 
 *               IPE3 doesn't update at SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA__PRED_NA4                    BITFIELD(19, 16)
#define IPE3_MMR__IPE_NA__PRED_NA4__POS               16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA__PRED_NA3   
 *
 * @BRIEF        Intra prediction mode of 4x4 block #15 of left macroblock(or 
 *               top macroblock in the previous macroblock pair in case of 
 *               MBAFF) 
 *               IPE3 doesn't update at SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA__PRED_NA3                    BITFIELD(15, 12)
#define IPE3_MMR__IPE_NA__PRED_NA3__POS               12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA__PRED_NA2   
 *
 * @BRIEF        Intra prediction mode of 4x4 block #13 of left macroblock(or 
 *               top macroblock in the previous macroblock pair in case of 
 *               MBAFF) 
 *               IPE3 doesn't update at SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA__PRED_NA2                    BITFIELD(11, 8)
#define IPE3_MMR__IPE_NA__PRED_NA2__POS               8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA__PRED_NA1   
 *
 * @BRIEF        Intra prediction mode of 4x4 block #7 of left macroblock(or 
 *               top macroblock in the previous macroblock pair in case of 
 *               MBAFF) 
 *               IPE3 doesn't update at SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA__PRED_NA1                    BITFIELD(7, 4)
#define IPE3_MMR__IPE_NA__PRED_NA1__POS               4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_NA__PRED_NA0   
 *
 * @BRIEF        Intra prediction mode of 4x4 block #5 of left macroblock(or 
 *               top macroblock in the previous macroblock pair in case of 
 *               MBAFF) 
 *               IPE3 doesn't update at SACT mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_NA__PRED_NA0                    BITFIELD(3, 0)
#define IPE3_MMR__IPE_NA__PRED_NA0__POS               0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP3   
 *
 * @BRIEF        Luma left sample for top MB line3 
 *               The right-most luminance pixel of top MB line3 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP3          BITFIELD(31, 24)
#define IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP3__POS     24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP2   
 *
 * @BRIEF        Luma left sample for top MB line2 
 *               The right-most luminance pixel of top MB line2 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP2          BITFIELD(23, 16)
#define IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP2__POS     16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP1   
 *
 * @BRIEF        Luma left sample for top MB line1 
 *               The right-most luminance pixel of top MB line1 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP1          BITFIELD(15, 8)
#define IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP1__POS     8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP0   
 *
 * @BRIEF        Luma left sample for top MB line0 
 *               The right-most luminance pixel of top MB line0 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP0          BITFIELD(7, 0)
#define IPE3_MMR__IPE_L_LF_T0__IPE_L_LF_TOP0__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP7   
 *
 * @BRIEF        Luma left sample for top MB line7 
 *               The right-most luminance pixel of top MB line7 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP7          BITFIELD(31, 24)
#define IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP7__POS     24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP6   
 *
 * @BRIEF        Luma left sample for top MB line6 
 *               The right-most luminance pixel of top MB line6 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP6          BITFIELD(23, 16)
#define IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP6__POS     16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP5   
 *
 * @BRIEF        Luma left sample for top MB line5 
 *               The right-most luminance pixel of top MB line5 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP5          BITFIELD(15, 8)
#define IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP5__POS     8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP4   
 *
 * @BRIEF        Luma left sample for top MB line4 
 *               The right-most luminance pixel of top MB line4 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP4          BITFIELD(7, 0)
#define IPE3_MMR__IPE_L_LF_T1__IPE_L_LF_TOP4__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP11   
 *
 * @BRIEF        Luma left sample for top MB line11 
 *               The right-most luminance pixel of top MB line11 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP11         BITFIELD(31, 24)
#define IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP11__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP10   
 *
 * @BRIEF        Luma left sample for top MB line10 
 *               The right-most luminance pixel of top MB line10 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP10         BITFIELD(23, 16)
#define IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP10__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP9   
 *
 * @BRIEF        Luma left sample for top MB line9 
 *               The right-most luminance pixel of top MB line9 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP9          BITFIELD(15, 8)
#define IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP9__POS     8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP8   
 *
 * @BRIEF        Luma left sample for top MB line8 
 *               The right-most luminance pixel of top MB line8 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP8          BITFIELD(7, 0)
#define IPE3_MMR__IPE_L_LF_T2__IPE_L_LF_TOP8__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP15   
 *
 * @BRIEF        Luma left sample for top MB line 15 
 *               The right-most luminance pixel of top MB line15 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP15         BITFIELD(31, 24)
#define IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP15__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP14   
 *
 * @BRIEF        Luma left sample for top MB line14 
 *               The right-most luminance pixel of top MB line14  in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP14         BITFIELD(23, 16)
#define IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP14__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP13   
 *
 * @BRIEF        Luma left sample for top MB line13 
 *               The right-most luminance pixel of top MB line13 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP13         BITFIELD(15, 8)
#define IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP13__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP12   
 *
 * @BRIEF        Luma left sample for top MB line12 
 *               The right-most luminance pixel of top MB line12 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP12         BITFIELD(7, 0)
#define IPE3_MMR__IPE_L_LF_T3__IPE_L_LF_TOP12__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT3   
 *
 * @BRIEF        Luma left sample for bottom MB line3 
 *               The right-most luminance pixel of bottom MB line3 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT3          BITFIELD(31, 24)
#define IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT3__POS     24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT2   
 *
 * @BRIEF        Luma left sample for bottom MB line2 
 *               The right-most luminance pixel of bottom MB line2 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT2          BITFIELD(23, 16)
#define IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT2__POS     16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT1   
 *
 * @BRIEF        Luma left sample for bottom MB line1 
 *               The right-most luminance pixel of bottom MB line1 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT1          BITFIELD(15, 8)
#define IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT1__POS     8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT0   
 *
 * @BRIEF        Luma left sample for bottom MB line0 
 *               The right-most luminance pixel of bottom MB line0 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT0          BITFIELD(7, 0)
#define IPE3_MMR__IPE_L_LF_B0__IPE_L_LF_BOT0__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT7   
 *
 * @BRIEF        Luma left sample for bottom MB line7 
 *               The right-most luminance pixel of bottom MB line7 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT7          BITFIELD(31, 24)
#define IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT7__POS     24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT6   
 *
 * @BRIEF        Luma left sample for bottom MB line6 
 *               The right-most luminance pixel of bottom MB line6 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT6          BITFIELD(23, 16)
#define IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT6__POS     16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT5   
 *
 * @BRIEF        Luma left sample for bottom MB line5 
 *               The right-most luminance pixel of bottom MB line5 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT5          BITFIELD(15, 8)
#define IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT5__POS     8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT4   
 *
 * @BRIEF        Luma left sample for bottom MB line4 
 *               The right-most luminance pixel of bottom MB line4 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT4          BITFIELD(7, 0)
#define IPE3_MMR__IPE_L_LF_B1__IPE_L_LF_BOT4__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT11   
 *
 * @BRIEF        Luma left sample for bottom MB line11 
 *               The right-most luminance pixel of bottom MB line11 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT11         BITFIELD(31, 24)
#define IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT11__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT10   
 *
 * @BRIEF        Luma left sample for bottom MB line10 
 *               The right-most luminance pixel of bottom MB lin10 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT10         BITFIELD(23, 16)
#define IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT10__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT9   
 *
 * @BRIEF        Luma left sample for bottom MB line9 
 *               The right-most luminance pixel of bottom MB line9 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT9          BITFIELD(15, 8)
#define IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT9__POS     8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT8   
 *
 * @BRIEF        Luma left sample for bottom MB line8 
 *               The right-most luminance pixel of bottom MB line8 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT8          BITFIELD(7, 0)
#define IPE3_MMR__IPE_L_LF_B2__IPE_L_LF_BOT8__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT15   
 *
 * @BRIEF        Luma left sample for bottom MB line15 
 *               The right-most luminance pixel of bottom MB line15 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT15         BITFIELD(31, 24)
#define IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT15__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT14   
 *
 * @BRIEF        Luma left sample for bottom MB line14 
 *               The right-most luminance pixel of bottom MB line14 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT14         BITFIELD(23, 16)
#define IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT14__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT13   
 *
 * @BRIEF        Luma left sample for bottom MB line13 
 *               The right-most luminance pixel of bottom MB line13 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT13         BITFIELD(15, 8)
#define IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT13__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT12   
 *
 * @BRIEF        Luma left sample for bottom MB line12 
 *               The right-most luminance pixel of bottom MB line12 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT12         BITFIELD(7, 0)
#define IPE3_MMR__IPE_L_LF_B3__IPE_L_LF_BOT12__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T0__IPE_CR_LF_TOP1   
 *
 * @BRIEF        Left Cr sample of top MB line1 
 *               The right-most Cr pixel of top MB line1 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T0__IPE_CR_LF_TOP1         BITFIELD(31, 24)
#define IPE3_MMR__IPE_C_LF_T0__IPE_CR_LF_TOP1__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T0__IPE_CB_LF_TOP1   
 *
 * @BRIEF        Left Cb sample of top MB line1 
 *               The right-most Cb pixel of top MB line1 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T0__IPE_CB_LF_TOP1         BITFIELD(23, 16)
#define IPE3_MMR__IPE_C_LF_T0__IPE_CB_LF_TOP1__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T0__IPE_CR_LF_TOP0   
 *
 * @BRIEF        Left Cr sample of top MB line0 
 *               The right-most Cr pixel of top MB line0 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T0__IPE_CR_LF_TOP0         BITFIELD(15, 8)
#define IPE3_MMR__IPE_C_LF_T0__IPE_CR_LF_TOP0__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T0__IPE_CB_LF_TOP0   
 *
 * @BRIEF        Left Cb sample of top MB line0 
 *               The right-most Cb pixel of top MB line0 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T0__IPE_CB_LF_TOP0         BITFIELD(7, 0)
#define IPE3_MMR__IPE_C_LF_T0__IPE_CB_LF_TOP0__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T1__IPE_CR_LF_TOP3   
 *
 * @BRIEF        Left Cr sample of top MB line3 
 *               The right-most Cr pixel of top MB line3 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T1__IPE_CR_LF_TOP3         BITFIELD(31, 24)
#define IPE3_MMR__IPE_C_LF_T1__IPE_CR_LF_TOP3__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T1__IPE_CB_LF_TOP3   
 *
 * @BRIEF        Left Cb sample of top MB line3 
 *               The right-most Cb pixel of top MB line3 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T1__IPE_CB_LF_TOP3         BITFIELD(23, 16)
#define IPE3_MMR__IPE_C_LF_T1__IPE_CB_LF_TOP3__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T1__IPE_CR_LF_TOP2   
 *
 * @BRIEF        Left Cr sample of top MB line2 
 *               The right-most Cr pixel of top MB   line2 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T1__IPE_CR_LF_TOP2         BITFIELD(15, 8)
#define IPE3_MMR__IPE_C_LF_T1__IPE_CR_LF_TOP2__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T1__IPE_CB_LF_TOP2   
 *
 * @BRIEF        Left Cb sample of top MB line2 
 *               The right-most Cb pixel of top MB line2 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T1__IPE_CB_LF_TOP2         BITFIELD(7, 0)
#define IPE3_MMR__IPE_C_LF_T1__IPE_CB_LF_TOP2__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T2__IPE_CR_LF_TOP5   
 *
 * @BRIEF        Left Cr sample of top MB line5 
 *               The right-most Cr pixel of top MB line5 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T2__IPE_CR_LF_TOP5         BITFIELD(31, 24)
#define IPE3_MMR__IPE_C_LF_T2__IPE_CR_LF_TOP5__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T2__IPE_CB_LF_TOP5   
 *
 * @BRIEF        Left Cb sample of top MB line5 
 *               The right-most Cb pixel of top MB line5 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T2__IPE_CB_LF_TOP5         BITFIELD(23, 16)
#define IPE3_MMR__IPE_C_LF_T2__IPE_CB_LF_TOP5__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T2__IPE_CR_LF_TOP4   
 *
 * @BRIEF        Left Cr sample of top MB line4 
 *               The right-most Cr pixel of top MB line4 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T2__IPE_CR_LF_TOP4         BITFIELD(15, 8)
#define IPE3_MMR__IPE_C_LF_T2__IPE_CR_LF_TOP4__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T2__IPE_CB_LF_TOP4   
 *
 * @BRIEF        Left Cb sample of top MB line4 
 *               The right-most Cb pixel of top MB line4 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T2__IPE_CB_LF_TOP4         BITFIELD(7, 0)
#define IPE3_MMR__IPE_C_LF_T2__IPE_CB_LF_TOP4__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T3__IPE_CR_LF_TOP7   
 *
 * @BRIEF        Left Cr sample of top MB line7 
 *               The right-most Cr pixel of top MB line7 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T3__IPE_CR_LF_TOP7         BITFIELD(31, 24)
#define IPE3_MMR__IPE_C_LF_T3__IPE_CR_LF_TOP7__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T3__IPE_CB_LF_TOP7   
 *
 * @BRIEF        Left Cb sample of top MB line7 
 *               The right-most Cb pixel of top MB line7 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T3__IPE_CB_LF_TOP7         BITFIELD(23, 16)
#define IPE3_MMR__IPE_C_LF_T3__IPE_CB_LF_TOP7__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T3__IPE_CR_LF_TOP6   
 *
 * @BRIEF        Left Cr sample of top MB line6 
 *               The right-most Cr pixel of top line6 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T3__IPE_CR_LF_TOP6         BITFIELD(15, 8)
#define IPE3_MMR__IPE_C_LF_T3__IPE_CR_LF_TOP6__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_T3__IPE_CB_LF_TOP6   
 *
 * @BRIEF        Left Cb sample of top MB line6 
 *               The right-most Cb pixel of top MB line6 in left macroblock. 
 *               IPE3 always update at the end of estimation automatically 
 *               for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_T3__IPE_CB_LF_TOP6         BITFIELD(7, 0)
#define IPE3_MMR__IPE_C_LF_T3__IPE_CB_LF_TOP6__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B0__IPE_CR_LF_BOT1   
 *
 * @BRIEF        Left Cr sample of bottom MB line1 
 *               The right-most Cr pixel of bottom MB line11 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B0__IPE_CR_LF_BOT1         BITFIELD(31, 24)
#define IPE3_MMR__IPE_C_LF_B0__IPE_CR_LF_BOT1__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B0__IPE_CB_LF_BOT1   
 *
 * @BRIEF        Left Cb sample of bottom MB line1 
 *               The right-most Cb pixel of bottom MB line1 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B0__IPE_CB_LF_BOT1         BITFIELD(23, 16)
#define IPE3_MMR__IPE_C_LF_B0__IPE_CB_LF_BOT1__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B0__IPE_CR_LF_BOT0   
 *
 * @BRIEF        Left Cr sample of bottom MB line0 
 *               The right-most Cr pixel of bottom MB line0 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B0__IPE_CR_LF_BOT0         BITFIELD(15, 8)
#define IPE3_MMR__IPE_C_LF_B0__IPE_CR_LF_BOT0__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B0__IPE_CB_LF_BOT0   
 *
 * @BRIEF        Left Cb sample of bottom MB line0 
 *               The right-most Cb pixel of bottom MB line0 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B0__IPE_CB_LF_BOT0         BITFIELD(7, 0)
#define IPE3_MMR__IPE_C_LF_B0__IPE_CB_LF_BOT0__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B1__IPE_CR_LF_BOT3   
 *
 * @BRIEF        Left Cr sample of bottom MB line3 
 *               The right-most Cr pixel of bottom MB line3 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B1__IPE_CR_LF_BOT3         BITFIELD(31, 24)
#define IPE3_MMR__IPE_C_LF_B1__IPE_CR_LF_BOT3__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B1__IPE_CB_LF_BOT3   
 *
 * @BRIEF        Left Cb sample of bottom MB line3 
 *               The right-most Cb pixel of bottom MB line3 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B1__IPE_CB_LF_BOT3         BITFIELD(23, 16)
#define IPE3_MMR__IPE_C_LF_B1__IPE_CB_LF_BOT3__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B1__IPE_CR_LF_BOT2   
 *
 * @BRIEF        Left Cr sample of bottom MB line2 
 *               The right-most Cr pixel of bottom MB line2 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B1__IPE_CR_LF_BOT2         BITFIELD(15, 8)
#define IPE3_MMR__IPE_C_LF_B1__IPE_CR_LF_BOT2__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B1__IPE_CB_LF_BOT2   
 *
 * @BRIEF        Left Cb sample of bottom MB line2 
 *               The right-most Cb pixel of bottom MB line2 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B1__IPE_CB_LF_BOT2         BITFIELD(7, 0)
#define IPE3_MMR__IPE_C_LF_B1__IPE_CB_LF_BOT2__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B2__IPE_CR_LF_BOT5   
 *
 * @BRIEF        Left Cr sample of bottom MB line5 
 *               The right-most Cr pixel of bottom MB line5 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B2__IPE_CR_LF_BOT5         BITFIELD(31, 24)
#define IPE3_MMR__IPE_C_LF_B2__IPE_CR_LF_BOT5__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B2__IPE_CB_LF_BOT5   
 *
 * @BRIEF        Left Cb sample of bottom MB line5 
 *               The right-most Cb pixel of bottom MB line5 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B2__IPE_CB_LF_BOT5         BITFIELD(23, 16)
#define IPE3_MMR__IPE_C_LF_B2__IPE_CB_LF_BOT5__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B2__IPE_CR_LF_BOT4   
 *
 * @BRIEF        Left Cr sample of bottom MB line4 
 *               The right-most Cr pixel of bottom MB line4 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B2__IPE_CR_LF_BOT4         BITFIELD(15, 8)
#define IPE3_MMR__IPE_C_LF_B2__IPE_CR_LF_BOT4__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B2__IPE_CB_LF_BOT4   
 *
 * @BRIEF        Left Cb sample of bottom MB line4 
 *               The right-most Cb pixel of bottom MB line4 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B2__IPE_CB_LF_BOT4         BITFIELD(7, 0)
#define IPE3_MMR__IPE_C_LF_B2__IPE_CB_LF_BOT4__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B3__IPE_CR_LF_BOT7   
 *
 * @BRIEF        Left Cr sample of bottom MB line7 
 *               The right-most Cr pixel of bottom MB line7 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B3__IPE_CR_LF_BOT7         BITFIELD(31, 24)
#define IPE3_MMR__IPE_C_LF_B3__IPE_CR_LF_BOT7__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B3__IPE_CB_LF_BOT7   
 *
 * @BRIEF        Left Cb sample of bottom MB line7 
 *               The right-most Cb pixel of bottom MB line7 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B3__IPE_CB_LF_BOT7         BITFIELD(23, 16)
#define IPE3_MMR__IPE_C_LF_B3__IPE_CB_LF_BOT7__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B3__IPE_CR_LF_BOT6   
 *
 * @BRIEF        Left Cr sample of bottom MB line6 
 *               The right-most Cr pixel of bottom MB line6 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B3__IPE_CR_LF_BOT6         BITFIELD(15, 8)
#define IPE3_MMR__IPE_C_LF_B3__IPE_CR_LF_BOT6__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MMR__IPE_C_LF_B3__IPE_CB_LF_BOT6   
 *
 * @BRIEF        Left Cb sample of bottom MB line6 
 *               The right-most Cb pixel of bottom MB line6 in left 
 *               macroblock. IPE3 always update at the end of estimation 
 *               automatically for next macroblock. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MMR__IPE_C_LF_B3__IPE_CB_LF_BOT6         BITFIELD(7, 0)
#define IPE3_MMR__IPE_C_LF_B3__IPE_CB_LF_BOT6__POS    0

    /* 
     * List of register bitfields values for component IPE3_MMR
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __IPE3_MMR_CRED_H 
                                                            */
