/** ==================================================================
 *  @file   ipe3_mem_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   IPE3_MEM
 *
 *  @Filename:    ipe3_mem_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __IPE3_MEM_CRED_H
#define __IPE3_MEM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance IPE3_MEM of component IPE3_MEM mapped in MONICA at address 0x5A038000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component IPE3_MEM
     *
     */

    /* 
     *  List of bundle arrays for component IPE3_MEM
     *
     */

    /* 
     *  List of bundles for component IPE3_MEM
     *
     */

    /* 
     * List of registers for component IPE3_MEM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MEM__IPORGBUF_A_START
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MEM__IPORGBUF_A_START                         0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MEM__IPORGBUF_A_END
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MEM__IPORGBUF_A_END                           0x7FCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MEM__IPORGBUF_B_START
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MEM__IPORGBUF_B_START                         0x800ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MEM__IPORGBUF_B_END
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MEM__IPORGBUF_B_END                           0xFFCul

    /* 
     * List of register bitfields for component IPE3_MEM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MEM__IPORGBUF_A_START__IPORGBUF_A_START   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MEM__IPORGBUF_A_START__IPORGBUF_A_START  BITFIELD(31, 0)
#define IPE3_MEM__IPORGBUF_A_START__IPORGBUF_A_START__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MEM__IPORGBUF_A_END__IPORGBUF_A_END   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MEM__IPORGBUF_A_END__IPORGBUF_A_END      BITFIELD(31, 0)
#define IPE3_MEM__IPORGBUF_A_END__IPORGBUF_A_END__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MEM__IPORGBUF_B_START__IPORGBUF_B_START   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MEM__IPORGBUF_B_START__IPORGBUF_B_START  BITFIELD(31, 0)
#define IPE3_MEM__IPORGBUF_B_START__IPORGBUF_B_START__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPE3_MEM__IPORGBUF_B_END__IPORGBUF_B_END   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define IPE3_MEM__IPORGBUF_B_END__IPORGBUF_B_END      BITFIELD(31, 0)
#define IPE3_MEM__IPORGBUF_B_END__IPORGBUF_B_END__POS 0

    /* 
     * List of register bitfields values for component IPE3_MEM
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __IPE3_MEM_CRED_H 
                                                            */
