/** ==================================================================
 *  @file   ipipeif_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   IPIPEIF
 *
 *  @Filename:    ipipeif_cred.h
 *
 *  @Description: IPIPEIF Module 
 *                  The following registers are shadowed. They can be updated at 
 *                  any time but the new value will be taken into account on the 
 *                next VD signal (next frame). 
 *                IPIPEIF_ PPLN 
 *                IPIPEIF_LPFR 
 *                IPIPEIF_HNUM 
 *                IPIPEIF_VNUM 
 *                IPIPEIF_ADDRU 
 *                IPIPEIF_ADDRL 
 *                IPIPEIF_ADOFS 
 *                IPIPEIF_ENABLE.SYNCOFF 
 *                IPIPEIF_CFG1.DECIM 
 *                IPIPEIF_CFG1.AVGFILT 
 *                IPIPEIF_RSZ 
 *                IPIPEIF_GAIN 
 *                IPIPEIF_RSZ3A.DECIM 
 *                IPIPEIF_RSZ3A.AVGFILT 
 *                IPIPEIF_RSZ3A.RSZ 
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __IPIPEIF_CRED_H
#define __IPIPEIF_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance I_IPIPEIF of component IPIPEIF mapped in MONICA at address 0x55051200
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component IPIPEIF
     *
     */

    /* 
     *  List of bundle arrays for component IPIPEIF
     *
     */

    /* 
     *  List of bundles for component IPIPEIF
     *
     */

    /* 
     * List of registers for component IPIPEIF
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ENABLE
 *
 * @BRIEF        IPIPEIF Enable. 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ENABLE                            0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1
 *
 * @BRIEF        IPIPEIF Configuration #1 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1                              0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_PPLN
 *
 * @BRIEF        IPIPEIF Interval of HD / Start pixel in HD 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_PPLN                              0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_LPFR
 *
 * @BRIEF        IPIPEIF Interval of VD / Start line in VD 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_LPFR                              0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_HNUM
 *
 * @BRIEF        IPIPEIF Number of valid pixels per line 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_HNUM                              0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_VNUM
 *
 * @BRIEF        IPIPEIF Number of valid lines per frame 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_VNUM                              0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ADDRU
 *
 * @BRIEF        IPIPEIF Memory Address (Upper) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ADDRU                             0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ADDRL
 *
 * @BRIEF        IPIPEIF Memory Address (Lower) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ADDRL                             0x1Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ADOFS
 *
 * @BRIEF        IPIPEIF Address offset 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ADOFS                             0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ
 *
 * @BRIEF        IPIPEIF Horizontal Resizing Parameter on IPIPE datapath 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ                               0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_GAIN
 *
 * @BRIEF        IPIPEIF Gain Parameter 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_GAIN                              0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM
 *
 * @BRIEF        IPIPEIF DPCM configuration 
 *               This register applies only if IPIPEIF_CFG1.UNPACK = 1, i.e., 
 *               RAW8 data is read from SDRAM. 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM                              0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2
 *
 * @BRIEF        IPIPEIF Configuration #2 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2                              0x30ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ
 *
 * @BRIEF        IPIPEIF resize initial position - IPIPE data path. 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ                            0x34ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_OCLIP
 *
 * @BRIEF        IPIPEIF output clipping value 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_OCLIP                             0x38ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DTUDF
 *
 * @BRIEF        IPIPEIF data underflow detection 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DTUDF                             0x3Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CLKDIV
 *
 * @BRIEF        IPIPEIF CLOCK DIVIDER 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CLKDIV                            0x40ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC1
 *
 * @BRIEF        IPIPEIF defect pixel correction #1 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC1                              0x44ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC2
 *
 * @BRIEF        IPIPEIF defect pixel correction #2 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC2                              0x48ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DFSGVL
 *
 * @BRIEF        IPIPEIF DARK FRAME GAIN CONTROL - GAIN VALUE 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DFSGVL                            0x4Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DFSGTH
 *
 * @BRIEF        IPIPEIF DARK FRAME GAIN CONTROL - THRESHOLD VALUE 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DFSGTH                            0x50ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ3A
 *
 * @BRIEF        IPIPEIF HORIZONTAL RESIZING PARAMETER FOR H3A 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ3A                             0x54ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ3A
 *
 * @BRIEF        IPIPEIF resize initial position - H3A data path. 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ3A                          0x58ul

    /* 
     * List of register bitfields for component IPIPEIF
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ENABLE__SYNCOFF   
 *
 * @BRIEF        VD output mask 
 *               This register masks the VD output to the IPIPE module. This 
 *               can be useful when one wants to read data from SDRAM which 
 *               are stored in a double buffer. If the VD is not masked each 
 *               time we start the module an new VD will be generated to the 
 *               IPIPEIF module. 
 *               Let's consider two buffers A and B of N lines each. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ENABLE__SYNCOFF              BITFIELD(1, 1)
#define IPIPEIF__IPIPEIF_ENABLE__SYNCOFF__POS         1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ENABLE__ENABLE   
 *
 * @BRIEF        IPIPE I/F Enable 
 *               This register is used to start the operation of SDRAM buffer 
 *               memory read and generates SYNC signals. 
 *               This register is available when INPSRC1 or INPSCR2 = 1, 2 or 
 *               3. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ENABLE__ENABLE               BITFIELD(0, 0)
#define IPIPEIF__IPIPEIF_ENABLE__ENABLE__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC1   
 *
 * @BRIEF        Selects the source for the mux (VPORT / ISIF / SDRAM) as 
 *               well as the data format type. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC1                BITFIELD(15, 14)
#define IPIPEIF__IPIPEIF_CFG1__INPSRC1__POS           14

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT   
 *
 * @BRIEF        SDRAM read data shift 
 *               This register is available when INPSRC1 or INPSRC2 = 1 or 2, 
 *               i.e., when data are read from SDRAM. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT                BITFIELD(13, 11)
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__POS           11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__CLKSEL   
 *
 * @BRIEF        IPIPEIF & IPIPE module pixel clock selection. 
 *               This register shall be set to '1' when INPSRC1 or INPSRC2 = 
 *               1 or 3, i.e., data are solely read from SDRAM (VPORT 
 *               inactive). - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__CLKSEL                 BITFIELD(10, 10)
#define IPIPEIF__IPIPEIF_CFG1__CLKSEL__POS            10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__UNPACK   
 *
 * @BRIEF        8-Bit, 12-bit Packed Mode 
 *               When sensor raw data are stored in 8-bit packed mode or 
 *               12-bit packed mode, this register should code 1 or 3. This 
 *               register is effective when INPSRC = 1 or 2. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__UNPACK                 BITFIELD(9, 8)
#define IPIPEIF__IPIPEIF_CFG1__UNPACK__POS            8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__AVGFILT   
 *
 * @BRIEF        Averaging Filter 
 *               It applies (1,2,1) filter for the RGB/YCbCr data. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__AVGFILT                BITFIELD(7, 7)
#define IPIPEIF__IPIPEIF_CFG1__AVGFILT__POS           7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC2   
 *
 * @BRIEF        Selects the source for the mux (ISIF / SDRAM) as well as the 
 *               data format type. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC2                BITFIELD(3, 2)
#define IPIPEIF__IPIPEIF_CFG1__INPSRC2__POS           2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DECIM   
 *
 * @BRIEF        Pixel Decimation 
 *               The decimation rate defined by RSZ register. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DECIM                  BITFIELD(1, 1)
#define IPIPEIF__IPIPEIF_CFG1__DECIM__POS             1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__ONESHOT   
 *
 * @BRIEF        One Shot Mode 
 *               This register is available when INPSRC = 1 or 3. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__ONESHOT                BITFIELD(0, 0)
#define IPIPEIF__IPIPEIF_CFG1__ONESHOT__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_PPLN__PPLN   
 *
 * @BRIEF        Case-1: Interval of Horizontal Sync (HD) 
 *               Specifies the interval of horizontal sync. 
 *               This register is available when INPSRC = 1 or 3. 
 *               Case-2: Start Pixel in Horizontal Sync (HD) 
 *               Specifies the start pixel in horizontal sync. 
 *               This register is available when INPSRC = 2 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_PPLN__PPLN                   BITFIELD(12, 0)
#define IPIPEIF__IPIPEIF_PPLN__PPLN__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_LPFR__LPFR   
 *
 * @BRIEF        Case-1: Interval of Vertical Sync (VD) 
 *               Specifies the interval of vertical sync. 
 *               This register is available when INPSRC = 1 or 3. 
 *               Case-2: Start Pixel in Vertical Sync (VD) 
 *               Specifies the start line in vertical sync. 
 *               This register is available when INPSRC = 2 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_LPFR__LPFR                   BITFIELD(12, 0)
#define IPIPEIF__IPIPEIF_LPFR__LPFR__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_HNUM__HNUM   
 *
 * @BRIEF        The Number of Valid Pixels in a Line 
 *               Specifies the number of valid pixels in a horizontal line. 
 *               This register is available when INPSRC = 1, 2 or 3 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_HNUM__HNUM                   BITFIELD(12, 0)
#define IPIPEIF__IPIPEIF_HNUM__HNUM__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_VNUM__VNUM   
 *
 * @BRIEF        The Number of Valid Line in a Vertical 
 *               Specifies the number of valid line in a vertical. 
 *               This register is available when INPSRC = 1, 2 or 3 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_VNUM__VNUM                   BITFIELD(12, 0)
#define IPIPEIF__IPIPEIF_VNUM__VNUM__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ADDRU__ADDRU   
 *
 * @BRIEF        Memory Address ? Upper 
 *               Memory address upper 11-bits are specified in units of 
 *               32-bytes 
 *               This register is available when INPSRC = 1, 2 or 3. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ADDRU__ADDRU                 BITFIELD(10, 0)
#define IPIPEIF__IPIPEIF_ADDRU__ADDRU__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ADDRL__ADDRL   
 *
 * @BRIEF        Memory Address - Lower 
 *               Memory address lower 16-bits are specified in units of 
 *               32-bytes. 
 *               This register is available when INPSRC = 1, 2 or 3. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ADDRL__ADDRL                 BITFIELD(15, 0)
#define IPIPEIF__IPIPEIF_ADDRL__ADDRL__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ADOFS__ADOFS   
 *
 * @BRIEF        Specifies the SDRAM stride for each line in units of 
 *               32-bytes. This register is available when reading data from 
 *               SDRAM: INPSRC1 or INPSRC2 = 1, 2 or 3. Assuming that the 
 *               first line is at position ADDR, the second line is at 
 *               address ADDR+ ADOFS, etc. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ADOFS__ADOFS                 BITFIELD(11, 0)
#define IPIPEIF__IPIPEIF_ADOFS__ADOFS__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ__RSZ   
 *
 * @BRIEF        Horizontal Resizing Parameter for IPIPE datapath 
 *               Specifies the horizontal resizing parameter. The RSZ 
 *               register can be configured within 16 to 112 range. 
 *               This resizing ratio is determined by 16/RSZ (= 1/1 to 1/7) 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ__RSZ                     BITFIELD(6, 0)
#define IPIPEIF__IPIPEIF_RSZ__RSZ__POS                0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_GAIN__GAIN   
 *
 * @BRIEF        Gain Parameter 
 *               Specifies the gain applied to RAW data before it is 
 *               forwarded to the IPIPE module.  
 *               The gain value is expressed using the U10Q9 fractional 
 *               format. The range is from 0.00195 (1/512) to 
 *               1.99805(1023/512). By default the unity gain is applied, 
 *               i.e., IPIPEIF_GAIN.GAIN = 0x200. 
 *               The gain is applied to RAW data only (IPIPEIF_CFG1.INPSRC2 
 *               != 3): the gain is not applied if the input data is YCbCr. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_GAIN__GAIN                   BITFIELD(9, 0)
#define IPIPEIF__IPIPEIF_GAIN__GAIN__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__BITS   
 *
 * @BRIEF        DPCM bit mode for SDRAM data - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__BITS                   BITFIELD(2, 2)
#define IPIPEIF__IPIPEIF_DPCM__BITS__POS              2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__PRED   
 *
 * @BRIEF        DPCM prediction mode for SDRAM data - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__PRED                   BITFIELD(1, 1)
#define IPIPEIF__IPIPEIF_DPCM__PRED__POS              1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__ENA   
 *
 * @BRIEF        DPCM decompression enable for SDRAM data. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__ENA                    BITFIELD(0, 0)
#define IPIPEIF__IPIPEIF_DPCM__ENA__POS               0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV8P   
 *
 * @BRIEF        8-bit YUV data unpacking to 16 bits 
 *               When IPIPEIF_CFG1.INPSRC2 = 0 and IPIPEIF_CFG2.YUV16 = 1, 
 *               the 8-bit YUV data are transformed into 16-bit YUV data. The 
 *               way the data are unpacked from 8 bits to 16 bits is 
 *               controlled by the IPIPEIF_CFG2.YUV8P register. The upper 8 
 *               bits of the 16-bit output are set to 0. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV8P                  BITFIELD(7, 7)
#define IPIPEIF__IPIPEIF_CFG2__YUV8P__POS             7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV8   
 *
 * @BRIEF        YUV 8bit mode 
 *               When ISIF_CFG1.INPSRC2 = 0 and YUV16 = 1, setting this bit 
 *               to 1 enables the conversion from 8bit YUV input to 16bit 
 *               YUV. This register is used when the input data from the ISIF 
 *               module is 8-bit YUV data. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV8                   BITFIELD(6, 6)
#define IPIPEIF__IPIPEIF_CFG2__YUV8__POS              6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__DFSDIR   
 *
 * @BRIEF        DFS direction 
 *               Selects the direction of dark frame subtraction. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__DFSDIR                 BITFIELD(5, 5)
#define IPIPEIF__IPIPEIF_CFG2__DFSDIR__POS            5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__WENE   
 *
 * @BRIEF        External WEN signal selection 
 *               Do not use for OMAP4 and MONICA since there is not parallel 
 *               interface at chip level. This register shall always be set 
 *               to 0. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__WENE                   BITFIELD(4, 4)
#define IPIPEIF__IPIPEIF_CFG2__WENE__POS              4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV16   
 *
 * @BRIEF        Data type selection. The behavior of this bitfield depends 
 *               upon other register settings. The functionality is best 
 *               explained with the following pseudo code: 
 *               if ((CFG1.INPSRC2==0 && CFG2.YUV16) || CFG1.INPSRC2==3) { 
 *                  data_out[15:0] = yuv[15:0] 
 *               } 
 *               else if (CFG1.INPSRC2==1 && CFG2.YUV16 && CFG1.UNPACK=1) { 
 *                   data_out[15:8] = gain_clip[7:0]; 
 *                   data_out[ 7:0] = 0; 
 *               } 
 *               else { 
 *                   data_out[15:12] = 0; 
 *                   data_out[11: 0] = gain_clip[11:0]; 
 *               } 
 *               where: 
 *               o data_out[15:0] =  16bit yuv or 12bit raw data to ipipe 
 *               o yuv[15:0] = 16bit yuv data from "horizontal pixel 
 *               decimator" block. 
 *               o gain_clip[11:0] = 12bit raw data from "gain" block. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV16                  BITFIELD(3, 3)
#define IPIPEIF__IPIPEIF_CFG2__YUV16__POS             3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__VDPOL   
 *
 * @BRIEF        VD Sync Polarity 
 *               When input VD is active low SYNC pulse, this bit needs to be 
 *               set to  ?1?. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__VDPOL                  BITFIELD(2, 2)
#define IPIPEIF__IPIPEIF_CFG2__VDPOL__POS             2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__HDPOL   
 *
 * @BRIEF        HD Sync Polarity 
 *               When input HD is active low SYNC pulse, this bit needs to be 
 *               set to  ?1?. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__HDPOL                  BITFIELD(1, 1)
#define IPIPEIF__IPIPEIF_CFG2__HDPOL__POS             1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__INTSW   
 *
 * @BRIEF        IPIPEIF interrupt source selection.  
 *               This register select the interrupt source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__INTSW                  BITFIELD(0, 0)
#define IPIPEIF__IPIPEIF_CFG2__INTSW__POS             0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ__ALNSYNC   
 *
 * @BRIEF        Align the HSYNC,VSYNC to initial position defined by INIRSZ. 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ__ALNSYNC              BITFIELD(13, 13)
#define IPIPEIF__IPIPEIF_INIRSZ__ALNSYNC__POS         13

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ__INIRSZ   
 *
 * @BRIEF        Offset used to re-initialize the HD/VD position after 
 *               resizer. From 0 to 8191 PCLK cycles. 
 *               Skips INIRSZ pixels for every line. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ__INIRSZ               BITFIELD(12, 0)
#define IPIPEIF__IPIPEIF_INIRSZ__INIRSZ__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_OCLIP__OCLIP   
 *
 * @BRIEF        Output clipping value after gain control on IPIPE data path. 
 *               This value is in U12Q0 data format. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_OCLIP__OCLIP                 BITFIELD(11, 0)
#define IPIPEIF__IPIPEIF_OCLIP__OCLIP__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DTUDF__DTUDF   
 *
 * @BRIEF        Data under flow error status register. 
 *               Reading ?1? shows there is data under flow and at least one 
 *               data is corrupted while reading from SDRAM. 
 *               Writing ?1? to this register clears (=0) the error (=1) 
 *               status. 
 *               Programmers need to configure proper read clock frequency or 
 *               SDRAM priority not to occur the data underflow. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DTUDF__DTUDF                 BITFIELD(0, 0)
#define IPIPEIF__IPIPEIF_DTUDF__DTUDF__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CLKDIV__CLKDIV   
 *
 * @BRIEF        IPIPEIF clock rate configuration 
 *               IPIPE/IPIPEIF clock frequency = M/N x clk_vpss clock 
 *               frequency. 
 *               We have M = CLKDIV[15:8] + 1 and N = CLKDIV[7:0] + 1 
 *               When clk_vpss > 121.5 MHz, M/N shall not be greater that 1/2 
 *               value 
 *               This register is available when IPIPEIF_CFG1.CLKSEL = 1. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CLKDIV__CLKDIV               BITFIELD(15, 0)
#define IPIPEIF__IPIPEIF_CLKDIV__CLKDIV__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC1__ENA   
 *
 * @BRIEF        DPC enable. Applies DPC for video port data, ISIF input 
 *               path. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC1__ENA                    BITFIELD(12, 12)
#define IPIPEIF__IPIPEIF_DPC1__ENA__POS               12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC1__TH   
 *
 * @BRIEF        DPC threshold value - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC1__TH                     BITFIELD(11, 0)
#define IPIPEIF__IPIPEIF_DPC1__TH__POS                0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC2__ENA   
 *
 * @BRIEF        DPC enable. Applies DPC for SDRAM input path. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC2__ENA                    BITFIELD(12, 12)
#define IPIPEIF__IPIPEIF_DPC2__ENA__POS               12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC2__TH   
 *
 * @BRIEF        DPC threshold value - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC2__TH                     BITFIELD(11, 0)
#define IPIPEIF__IPIPEIF_DPC2__TH__POS                0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DFSGVL__DFSGEN   
 *
 * @BRIEF        DFS gain control enable. 
 *               This functionality is protected by an eFuse. Not available 
 *               when ISP5_EFUSE4_EN = '0'. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DFSGVL__DFSGEN               BITFIELD(10, 10)
#define IPIPEIF__IPIPEIF_DFSGVL__DFSGEN__POS          10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DFSGVL__DFSGVL   
 *
 * @BRIEF        DFS gain value. 
 *               This functionality is protected by an eFuse. Not available 
 *               when ISP5_EFUSE4_EN = '0'. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DFSGVL__DFSGVL               BITFIELD(9, 0)
#define IPIPEIF__IPIPEIF_DFSGVL__DFSGVL__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DFSGTH__DFSGTH   
 *
 * @BRIEF        DFS gain threshold value. 
 *               This functionality is protected by an eFuse. Not available 
 *               when ISP5_EFUSE4_EN = '0'. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DFSGTH__DFSGTH               BITFIELD(11, 0)
#define IPIPEIF__IPIPEIF_DFSGTH__DFSGTH__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ3A__DECIM   
 *
 * @BRIEF        Pixel Decimation Enable 
 *               The decimation rate defined by the RSZ bitfield. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ3A__DECIM                 BITFIELD(9, 9)
#define IPIPEIF__IPIPEIF_RSZ3A__DECIM__POS            9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ3A__AVGFILT   
 *
 * @BRIEF        Averaging Filter 
 *               It applies a (1, 2, 1) filter for the RGB/YCbCr data. 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ3A__AVGFILT               BITFIELD(8, 8)
#define IPIPEIF__IPIPEIF_RSZ3A__AVGFILT__POS          8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ3A__RSZ   
 *
 * @BRIEF        Horizontal Resizing Parameter for H3A datapath 
 *               Specifies the horizontal resizing parameter. The RSZ 
 *               register can be configured within 16 to 112 range. 
 *               This resizing ratio is determined by 16/RSZ (= 1/1 to 1/7) 
 *               *This bit field is latched by VD. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ3A__RSZ                   BITFIELD(6, 0)
#define IPIPEIF__IPIPEIF_RSZ3A__RSZ__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ3A__ALNSYNC   
 *
 * @BRIEF        Align the HD, VD to initial position defined by the INIRSZ 
 *               bit field. It means that HD and VD are effectivly shifted by 
 *               INIRSZ pixel clock cycles. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ3A__ALNSYNC            BITFIELD(13, 13)
#define IPIPEIF__IPIPEIF_INIRSZ3A__ALNSYNC__POS       13

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ3A__INIRSZ   
 *
 * @BRIEF        Offset used to re-initialize the HD/VD position after 
 *               resizer. From 0 to 8191 PCLK cycles. 
 *               Skips INIRSZ pixels for every line. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ3A__INIRSZ             BITFIELD(12, 0)
#define IPIPEIF__IPIPEIF_INIRSZ3A__INIRSZ__POS        0

    /* 
     * List of register bitfields values for component IPIPEIF
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ENABLE__SYNCOFF__NEWENUM1
 *
 * @BRIEF        VD output mask is disabled. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ENABLE__SYNCOFF__NEWENUM1    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ENABLE__SYNCOFF__NEWENUM2
 *
 * @BRIEF        VD output mask is enabled. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ENABLE__SYNCOFF__NEWENUM2    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ENABLE__ENABLE__NEWENUM1
 *
 * @BRIEF        disable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ENABLE__ENABLE__NEWENUM1     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_ENABLE__ENABLE__NEWENUM2
 *
 * @BRIEF        enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_ENABLE__ENABLE__NEWENUM2     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC1__NEWENUM1
 *
 * @BRIEF        VPORT_RAW - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC1__NEWENUM1      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC1__NEWENUM2
 *
 * @BRIEF        SDRAM_RAW - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC1__NEWENUM2      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC1__NEWENUM3
 *
 * @BRIEF        ISIF_DARKFM 
 *               Input ports to DFS submodule are are ISIF and SDRAM. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC1__NEWENUM3      0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC1__NEWENUM4
 *
 * @BRIEF        SDRAM_YUV - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC1__NEWENUM4      0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM1
 *
 * @BRIEF        Output data[11:0] = (read data[11:0]) & 0x0FFF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM1      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM2
 *
 * @BRIEF        Output data[11:0] = (read data[11:0] << 1)  & 0x0FFF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM2      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM3
 *
 * @BRIEF        Output data[11:0] = (read data[11:0] << 2)  & 0x0FFF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM3      0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM4
 *
 * @BRIEF        Output data[11:0] = (read data[11:0] << 3)  & 0x0FFF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM4      0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM5
 *
 * @BRIEF        Output data[11:0] = (read data[11:0] << 4)  & 0x0FFF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM5      0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM6
 *
 * @BRIEF        Output data[11:0] = (read data[15:4] >> 4)  & 0x0FFF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM6      0x5ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM7
 *
 * @BRIEF        Output data[11:0] = (read data[15:4] >> 4)  & 0x0FFF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM7      0x6ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM8
 *
 * @BRIEF        Output data[11:0] = (read data[15:4] >> 4)  & 0x0FFF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DATASFT__NEWENUM8      0x7ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__CLKSEL__NEWENUM1
 *
 * @BRIEF        Selects the pixel clock from the VPORT. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__CLKSEL__NEWENUM1       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__CLKSEL__NEWENUM2
 *
 * @BRIEF        Selects the pixel clock from the fractional clock divider. 
 *               The fractional clock divider value is setup with the 
 *               IPIPEIF_CLKDIV register. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__CLKSEL__NEWENUM2       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__UNPACK__NEWENUM1
 *
 * @BRIEF        16 bits / pixel - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__UNPACK__NEWENUM1       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__UNPACK__NEWENUM2
 *
 * @BRIEF        8 bits / pixel - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__UNPACK__NEWENUM2       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__UNPACK__NEWENUM3
 *
 * @BRIEF        8 bits / pixel + inverse A law (8 bits to 10 bits) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__UNPACK__NEWENUM3       0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__UNPACK__NEWENUM4
 *
 * @BRIEF        12 bits / pixel - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__UNPACK__NEWENUM4       0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__AVGFILT__NEWENUM1
 *
 * @BRIEF        disable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__AVGFILT__NEWENUM1      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__AVGFILT__NEWENUM2
 *
 * @BRIEF        enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__AVGFILT__NEWENUM2      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC2__NEWENUM1
 *
 * @BRIEF        ISIF - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC2__NEWENUM1      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC2__NEWENUM2
 *
 * @BRIEF        SDRAM_RAW - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC2__NEWENUM2      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC2__NEWENUM3
 *
 * @BRIEF        ISIF_DARKFM 
 *               Input ports to DFS submodule are are VPORT and SDRAM. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC2__NEWENUM3      0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__INPSRC2__NEWENUM4
 *
 * @BRIEF        SDRAM_YUV - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__INPSRC2__NEWENUM4      0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DECIM__NEWENUM1
 *
 * @BRIEF        No decimation - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DECIM__NEWENUM1        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__DECIM__NEWENUM2
 *
 * @BRIEF        Decimation - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__DECIM__NEWENUM2        0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__ONESHOT__NEWENUM1
 *
 * @BRIEF        Continuous mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__ONESHOT__NEWENUM1      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG1__ONESHOT__NEWENUM2
 *
 * @BRIEF        One shot mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG1__ONESHOT__NEWENUM2      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__BITS__NEWENUM1
 *
 * @BRIEF        8bit to 10bit DPCM decompression - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__BITS__NEWENUM1         0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__BITS__NEWENUM2
 *
 * @BRIEF        8bit to 12bit DPCM decompression - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__BITS__NEWENUM2         0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__PRED__NEWENUM1
 *
 * @BRIEF        Simple predictor - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__PRED__NEWENUM1         0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__PRED__NEWENUM2
 *
 * @BRIEF        Advanced predictor - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__PRED__NEWENUM2         0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__ENA__NEWENUM1
 *
 * @BRIEF        DPCM off (no decompression) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__ENA__NEWENUM1          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPCM__ENA__NEWENUM2
 *
 * @BRIEF        DPCM on - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPCM__ENA__NEWENUM2          0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV8P__NEWENUM1
 *
 * @BRIEF        Y output on even pixels 
 *               C output on odd pixels - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV8P__NEWENUM1        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV8P__NEWENUM2
 *
 * @BRIEF        C output on even pixels 
 *               Y output on odd pixels - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV8P__NEWENUM2        0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV8__NEWENUM1
 *
 * @BRIEF        YUV16 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV8__NEWENUM1         0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV8__NEWENUM2
 *
 * @BRIEF        YUV8 to 16 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV8__NEWENUM2         0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__DFSDIR__NEWENUM1
 *
 * @BRIEF        VPORT IF(capture frame) - SDRAM (dark frame) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__DFSDIR__NEWENUM1       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__DFSDIR__NEWENUM2
 *
 * @BRIEF        SDRAM (capture frame) - VPORT IF(dark frame) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__DFSDIR__NEWENUM2       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV16__NEWENUM1
 *
 * @BRIEF        12-bit RAW data - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV16__NEWENUM1        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__YUV16__NEWENUM2
 *
 * @BRIEF        16-bit YUV data - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__YUV16__NEWENUM2        0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__VDPOL__NEWENUM1
 *
 * @BRIEF        Positive - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__VDPOL__NEWENUM1        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__VDPOL__NEWENUM2
 *
 * @BRIEF        Negative - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__VDPOL__NEWENUM2        0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__HDPOL__NEWENUM1
 *
 * @BRIEF        Positive - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__HDPOL__NEWENUM1        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__HDPOL__NEWENUM2
 *
 * @BRIEF        Negative - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__HDPOL__NEWENUM2        0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__INTSW__NEWENUM1
 *
 * @BRIEF        Start position of VD from VPORT interface - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__INTSW__NEWENUM1        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_CFG2__INTSW__NEWENUM2
 *
 * @BRIEF        Start position of VD from ISIF module - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_CFG2__INTSW__NEWENUM2        0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ__ALNSYNC__NEWENUM1
 *
 * @BRIEF        Disable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ__ALNSYNC__NEWENUM1    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ__ALNSYNC__NEWENUM2
 *
 * @BRIEF        Enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ__ALNSYNC__NEWENUM2    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC1__ENA__NEWENUM1
 *
 * @BRIEF        Disable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC1__ENA__NEWENUM1          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC1__ENA__NEWENUM2
 *
 * @BRIEF        Enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC1__ENA__NEWENUM2          0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC2__ENA__NEWENUM1
 *
 * @BRIEF        Disable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC2__ENA__NEWENUM1          0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_DPC2__ENA__NEWENUM2
 *
 * @BRIEF        Enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_DPC2__ENA__NEWENUM2          0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ3A__DECIM__NEWENUM1
 *
 * @BRIEF        No Decimation - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ3A__DECIM__NEWENUM1       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ3A__DECIM__NEWENUM2
 *
 * @BRIEF        Decimate - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ3A__DECIM__NEWENUM2       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ3A__AVGFILT__NEWENUM1
 *
 * @BRIEF        Disable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ3A__AVGFILT__NEWENUM1     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_RSZ3A__AVGFILT__NEWENUM2
 *
 * @BRIEF        Enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_RSZ3A__AVGFILT__NEWENUM2     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ3A__ALNSYNC__NEWENUM1
 *
 * @BRIEF        Disable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ3A__ALNSYNC__NEWENUM1  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IPIPEIF__IPIPEIF_INIRSZ3A__ALNSYNC__NEWENUM2
 *
 * @BRIEF        Enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IPIPEIF__IPIPEIF_INIRSZ3A__ALNSYNC__NEWENUM2  0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __IPIPEIF_CRED_H 
                                                            */
