/** ==================================================================
 *  @file   isp5_sys2_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   ISP5_SYS2
 *
 *  @Filename:    isp5_sys2_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __ISP5_SYS2_CRED_H
#define __ISP5_SYS2_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance I_ISP5_SYS2 of component ISP5_SYS2 mapped in MONICA at address 0x550500A0
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component ISP5_SYS2
     *
     */

    /* 
     *  List of bundle arrays for component ISP5_SYS2
     *
     */

    /* 
     *  List of bundles for component ISP5_SYS2
     *
     */

    /* 
     * List of registers for component ISP5_SYS2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN1
 *
 * @BRIEF        IPIPE eFuse enable. 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN1                            0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN2
 *
 * @BRIEF        ISIF eFuse enable. 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN2                            0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN3
 *
 * @BRIEF        ISIF eFuse enable. 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN3                            0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN4
 *
 * @BRIEF        IPIPEIF eFuse enable. 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN4                            0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN5
 *
 * @BRIEF        H3A eFuse enable. 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN5                            0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN6
 *
 * @BRIEF        H3A eFuse enable. 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN6                            0x14ul

    /* 
     * List of register bitfields for component ISP5_SYS2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN1__KEY1_EN   
 *
 * @BRIEF        EFUSE enable 
 *               Equals 1 when ISP5_EFUSE3_EN = 1 or 0 otherwise. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN1__KEY1_EN              BITFIELD(0, 0)
#define ISP5_SYS2__ISP5_KEY_EN1__KEY1_EN__POS         0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN2__KEY1_EN   
 *
 * @BRIEF        EFUSE enable 
 *               Equals 1 when ISP5_EFUSE1_EN = 1 or 0 otherwise. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN2__KEY1_EN              BITFIELD(0, 0)
#define ISP5_SYS2__ISP5_KEY_EN2__KEY1_EN__POS         0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN3__KEY_EN   
 *
 * @BRIEF        EFUSE enable 
 *               Equals 1 when ISP5_EFUSE3_EN = 1 or 0 otherwise. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN3__KEY_EN               BITFIELD(0, 0)
#define ISP5_SYS2__ISP5_KEY_EN3__KEY_EN__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN4__KEY2_EN   
 *
 * @BRIEF        EFUSE enable 
 *               Equals 1 when ISP5_EFUSE4_EN = 1 or 0 otherwise. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN4__KEY2_EN              BITFIELD(1, 1)
#define ISP5_SYS2__ISP5_KEY_EN4__KEY2_EN__POS         1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN4__KEY1_EN   
 *
 * @BRIEF        EFUSE enable 
 *               Equals 1 when ISP5_EFUSE1_EN = 1 or 0 otherwise. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN4__KEY1_EN              BITFIELD(0, 0)
#define ISP5_SYS2__ISP5_KEY_EN4__KEY1_EN__POS         0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN5__KEY_EN   
 *
 * @BRIEF        EFUSE enable 
 *               Equals 1 when ISP5_EFUSE2_EN = 1 or 0 otherwise. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN5__KEY_EN               BITFIELD(0, 0)
#define ISP5_SYS2__ISP5_KEY_EN5__KEY_EN__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN6__KEY_EN   
 *
 * @BRIEF        EFUSE enable 
 *               Equals 1 when ISP5_EFUSE3_EN = 1 or 0 otherwise. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN6__KEY_EN               BITFIELD(0, 0)
#define ISP5_SYS2__ISP5_KEY_EN6__KEY_EN__POS          0

    /* 
     * List of register bitfields values for component ISP5_SYS2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN1__KEY1_EN__NEWENUM1
 *
 * @BRIEF        Disable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN1__KEY1_EN__NEWENUM1    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN1__KEY1_EN__NEWENUM2
 *
 * @BRIEF        Enable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN1__KEY1_EN__NEWENUM2    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN2__KEY1_EN__NEWENUM1
 *
 * @BRIEF        Disable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN2__KEY1_EN__NEWENUM1    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN2__KEY1_EN__NEWENUM2
 *
 * @BRIEF        Enable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN2__KEY1_EN__NEWENUM2    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN3__KEY_EN__NEWENUM1
 *
 * @BRIEF        Disable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN3__KEY_EN__NEWENUM1     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN3__KEY_EN__NEWENUM2
 *
 * @BRIEF        Enable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN3__KEY_EN__NEWENUM2     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN4__KEY2_EN__NEWENUM1
 *
 * @BRIEF        Disable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN4__KEY2_EN__NEWENUM1    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN4__KEY2_EN__NEWENUM2
 *
 * @BRIEF        Enable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN4__KEY2_EN__NEWENUM2    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN4__KEY1_EN__NEWENUM1
 *
 * @BRIEF        Disable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN4__KEY1_EN__NEWENUM1    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN4__KEY1_EN__NEWENUM2
 *
 * @BRIEF        Enable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN4__KEY1_EN__NEWENUM2    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN5__KEY_EN__NEWENUM1
 *
 * @BRIEF        Disable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN5__KEY_EN__NEWENUM1     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN5__KEY_EN__NEWENUM2
 *
 * @BRIEF        Enable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN5__KEY_EN__NEWENUM2     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN6__KEY_EN__NEWENUM1
 *
 * @BRIEF        Disable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN6__KEY_EN__NEWENUM1     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   ISP5_SYS2__ISP5_KEY_EN6__KEY_EN__NEWENUM2
 *
 * @BRIEF        Enable - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define ISP5_SYS2__ISP5_KEY_EN6__KEY_EN__NEWENUM2     0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __ISP5_SYS2_CRED_H 
                                                            */
