/** ==================================================================
 *  @file   ivahd_prm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   IVAHD_PRM
 *
 *  @Filename:    ivahd_prm_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __IVAHD_PRM_CRED_H
#define __IVAHD_PRM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance IVAHD_PRM of component IVAHD_PRM mapped in MONICA at address 0x4A306F00
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component IVAHD_PRM
     *
     */

    /* 
     *  List of bundle arrays for component IVAHD_PRM
     *
     */

    /* 
     *  List of bundles for component IVAHD_PRM
     *
     */

    /* 
     * List of registers for component IVAHD_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL
 *
 * @BRIEF        This register controls the IVAHD power state to reach upon a 
 *               domain sleep transition 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL                      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST
 *
 * @BRIEF        This register provides a status on the current IVAHD power 
 *               domain state. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST                        0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL
 *
 * @BRIEF        This register controls the release of the IVAHD sub-system 
 *               resets. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL                        0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST
 *
 * @BRIEF        This register logs the different reset sources of the IVAHD 
 *               domain. Each bit is set upon release of the domain reset 
 *               signal. Must be cleared by software. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST                          0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT
 *
 * @BRIEF        This register contains dedicated IVAHD context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT                  0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_SL2_CONTEXT
 *
 * @BRIEF        This register contains dedicated SL2 context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT                    0x2Cul

    /* 
     * List of register bitfields for component IVAHD_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_ONSTATE   
 *
 * @BRIEF        TCM2 memory state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_ONSTATE BITFIELD(23, 22)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_ONSTATE__POS 22

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_ONSTATE   
 *
 * @BRIEF        TCM1 memory state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_ONSTATE BITFIELD(21, 20)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_ONSTATE__POS 20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_ONSTATE   
 *
 * @BRIEF        SL2 memory state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_ONSTATE BITFIELD(19, 18)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_ONSTATE__POS 18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_ONSTATE   
 *
 * @BRIEF        HWA memory state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_ONSTATE BITFIELD(17, 16)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_ONSTATE__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_RETSTATE   
 *
 * @BRIEF        TCM2 memory state when domain is RETENTION. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_RETSTATE BITFIELD(11, 11)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_RETSTATE__POS 11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_RETSTATE   
 *
 * @BRIEF        TCM1 memory state when domain is RETENTION. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_RETSTATE BITFIELD(10, 10)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_RETSTATE__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_RETSTATE   
 *
 * @BRIEF        SL2 memory state when domain is RETENTION. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_RETSTATE BITFIELD(9, 9)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_RETSTATE__POS 9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_RETSTATE   
 *
 * @BRIEF        HWA memory state when domain is RETENTION. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_RETSTATE BITFIELD(8, 8)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_RETSTATE__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOWPOWERSTATECHANGE   
 *
 * @BRIEF        Power state change request when domain has already performed 
 *               a sleep transition. Allows going into deeper low power state 
 *               without waking up the power domain. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOWPOWERSTATECHANGE BITFIELD(4, 4)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOWPOWERSTATECHANGE__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOGICRETSTATE   
 *
 * @BRIEF        Logic state when power domain is RETENTION - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOGICRETSTATE  BITFIELD(2, 2)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOGICRETSTATE__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE   
 *
 * @BRIEF        Power state control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE     BITFIELD(1, 0)
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__INTRANSITION   
 *
 * @BRIEF        Domain transition status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__INTRANSITION     BITFIELD(20, 20)
#define IVAHD_PRM__PM_IVAHD_PWRSTST__INTRANSITION__POS 20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST   
 *
 * @BRIEF        TCM2 memory state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST BITFIELD(11, 10)
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST   
 *
 * @BRIEF        TCM1 memory state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST BITFIELD(9, 8)
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST   
 *
 * @BRIEF        SL2 memory state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST  BITFIELD(7, 6)
#define IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST   
 *
 * @BRIEF        HWA memory state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST  BITFIELD(5, 4)
#define IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__LOGICSTATEST   
 *
 * @BRIEF        Logic state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__LOGICSTATEST     BITFIELD(2, 2)
#define IVAHD_PRM__PM_IVAHD_PWRSTST__LOGICSTATEST__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST   
 *
 * @BRIEF        Current power state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST     BITFIELD(1, 0)
#define IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST3   
 *
 * @BRIEF        IVAHD logic and SL2 reset control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST3             BITFIELD(2, 2)
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST3__POS        2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST2   
 *
 * @BRIEF        IVAHD Sequencer2 reset control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST2             BITFIELD(1, 1)
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST2__POS        1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST1   
 *
 * @BRIEF        IVAHD sequencer1 reset control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST1             BITFIELD(0, 0)
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST1__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ2_RST2ST   
 *
 * @BRIEF        Sequencer2 CPU  has been reset due to IVAHD ICECRUSHER2 
 *               reset event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ2_RST2ST BITFIELD(6, 6)
#define IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ2_RST2ST__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ1_RST1ST   
 *
 * @BRIEF        Sequencer1 CPU  has been reset due to IVAHD ICECRUSHER1 
 *               reset event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ1_RST1ST BITFIELD(5, 5)
#define IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ1_RST1ST__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ2_RST2ST   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ2_RST2ST BITFIELD(4, 4)
#define IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ2_RST2ST__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ1_RST1ST   
 *
 * @BRIEF        Sequencer1 CPU  has been reset due to emulation reset source 
 *               e.g. assert reset command initiated by the icepick module - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ1_RST1ST BITFIELD(3, 3)
#define IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ1_RST1ST__POS 3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST3ST   
 *
 * @BRIEF        IVAHD logic and SL2 SW reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST3ST             BITFIELD(2, 2)
#define IVAHD_PRM__RM_IVAHD_RSTST__RST3ST__POS        2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST2ST   
 *
 * @BRIEF        IVAHD Sequencer2 CPU SW reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST2ST             BITFIELD(1, 1)
#define IVAHD_PRM__RM_IVAHD_RSTST__RST2ST__POS        1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST1ST   
 *
 * @BRIEF        IVAHD Sequencer1 CPU SW reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST1ST             BITFIELD(0, 0)
#define IVAHD_PRM__RM_IVAHD_RSTST__RST1ST__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_HWA_MEM   
 *
 * @BRIEF        Specify if memory-based context in HWA_MEM memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_HWA_MEM BITFIELD(10, 10)
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_HWA_MEM__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM2_MEM   
 *
 * @BRIEF        Specify if memory-based context in TCM2_MEM memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM2_MEM BITFIELD(9, 9)
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM2_MEM__POS 9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM1_MEM   
 *
 * @BRIEF        Specify if memory-based context in TCM1_MEM memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM1_MEM BITFIELD(8, 8)
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM1_MEM__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of IVAHD_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTCONTEXT_DFF__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTMEM_SL2_MEM   
 *
 * @BRIEF        Specify if memory-based context in SL2_MEM memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTMEM_SL2_MEM BITFIELD(8, 8)
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTMEM_SL2_MEM__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of IVAHD_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTCONTEXT_DFF__POS 0

    /* 
     * List of register bitfields values for component IVAHD_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_RETSTATE__MEM_OFF
 *
 * @BRIEF        Memory bank is off when the domain is in the RETENTION 
 *               state. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_RETSTATE__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_RETSTATE__MEM_RET
 *
 * @BRIEF        Memory bank is retained when domain is in RETENTION state. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM2_MEM_RETSTATE__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_RETSTATE__MEM_OFF
 *
 * @BRIEF        Memory bank is off when the domain is in the RETENTION 
 *               state. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_RETSTATE__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_RETSTATE__MEM_RET
 *
 * @BRIEF        Memory bank is retained when domain is in RETENTION state. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__TCM1_MEM_RETSTATE__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_RETSTATE__MEM_OFF
 *
 * @BRIEF        Memory bank is off when the domain is in the RETENTION 
 *               state. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_RETSTATE__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_RETSTATE__MEM_RET
 *
 * @BRIEF        Memory bank is retained when domain is in RETENTION state. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__SL2_MEM_RETSTATE__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_RETSTATE__MEM_OFF
 *
 * @BRIEF        Memory bank is off when the domain is in the RETENTION 
 *               state. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__HWA_MEM_RETSTATE__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOWPOWERSTATECHANGE__DIS
 *
 * @BRIEF        Do not request a low power state change. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOWPOWERSTATECHANGE__DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOWPOWERSTATECHANGE__EN
 *
 * @BRIEF        Request a low power state change. This bit is automatically 
 *               cleared when the power state is effectively changed or when 
 *               power state is ON. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOWPOWERSTATECHANGE__EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOGICRETSTATE__LOGIC_OFF
 *
 * @BRIEF        Whole logic is off when the domain is in RETENTION state. - 
 *               (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__LOGICRETSTATE__LOGIC_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__OFF
 *
 * @BRIEF        OFF state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__RET
 *
 * @BRIEF        RETENTION state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__INACT
 *
 * @BRIEF        INACTIVE state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__INACT 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__ON
 *
 * @BRIEF        ON State - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTCTRL__POWERSTATE__ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__INTRANSITION__NO
 *
 * @BRIEF        No on-going transition on power domain - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__INTRANSITION__NO 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__INTRANSITION__ONGOING
 *
 * @BRIEF        Power domain transition is in progress. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__INTRANSITION__ONGOING 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__MEM_RET
 *
 * @BRIEF        Memory is RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM2_MEM_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__MEM_RET
 *
 * @BRIEF        Memory is RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__TCM1_MEM_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__MEM_RET
 *
 * @BRIEF        Memory is RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__SL2_MEM_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__MEM_RET
 *
 * @BRIEF        Memory is RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__HWA_MEM_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__LOGICSTATEST__OFF
 *
 * @BRIEF        Logic in domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__LOGICSTATEST__OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__LOGICSTATEST__ON
 *
 * @BRIEF        Logic in domain is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__LOGICSTATEST__ON 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__OFF
 *
 * @BRIEF        Power domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__RET
 *
 * @BRIEF        Power domain is in RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__INACTIVE
 *
 * @BRIEF        Power domain is ON-INACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__INACTIVE 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__ON
 *
 * @BRIEF        Power domain is ON-ACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__PM_IVAHD_PWRSTST__POWERSTATEST__ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST3__CLEAR
 *
 * @BRIEF        Reset is cleared for the IVAHD logic and SL2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST3__CLEAR      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST3__ASSERT
 *
 * @BRIEF        Reset is asserted for IVAHD logic and SL2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST3__ASSERT     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST2__CLEAR
 *
 * @BRIEF        Reset is cleared for IVAHD Sequencer CPU2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST2__CLEAR      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST2__ASSERT
 *
 * @BRIEF        Reset is asserted for IVAHD Sequencer CPU2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST2__ASSERT     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST1__CLEAR
 *
 * @BRIEF        Reset is cleared for the IVAHD Sequencer CPU1 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST1__CLEAR      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTCTRL__RST1__ASSERT
 *
 * @BRIEF        Reset is asserted for the IVAHD sequencer CPU1 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTCTRL__RST1__ASSERT     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ2_RST2ST__RESET_NO
 *
 * @BRIEF        No icecrusher reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ2_RST2ST__RESET_NO 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ2_RST2ST__RESET_YES
 *
 * @BRIEF        Sequencer2 has been reset upon icecrusher reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ2_RST2ST__RESET_YES 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ1_RST1ST__RESET_NO
 *
 * @BRIEF        No icecrusher reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ1_RST1ST__RESET_NO 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ1_RST1ST__RESET_YES
 *
 * @BRIEF        Sequencer1 has been reset upon icecrusher reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__ICECRUSHER_SEQ1_RST1ST__RESET_YES 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ2_RST2ST__RESET_NO
 *
 * @BRIEF        No emulation reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ2_RST2ST__RESET_NO 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ2_RST2ST__RESET_YES
 *
 * @BRIEF        Sequencer2  has been reset upon emulation reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ2_RST2ST__RESET_YES 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ1_RST1ST__RESET_NO
 *
 * @BRIEF        No emulation reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ1_RST1ST__RESET_NO 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ1_RST1ST__RESET_YES
 *
 * @BRIEF        Sequencer1 has been reset upon emulation reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__EMULATION_SEQ1_RST1ST__RESET_YES 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST3ST__RESET_NO
 *
 * @BRIEF        No SW reset occured - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST3ST__RESET_NO   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST3ST__RESET_YES
 *
 * @BRIEF        IVAHD logic and SL2  has been reset upon SW reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST3ST__RESET_YES  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST2ST__RESET_NO
 *
 * @BRIEF        No SW reset occured - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST2ST__RESET_NO   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST2ST__RESET_YES
 *
 * @BRIEF        Sequencer2  has been reset upon SW reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST2ST__RESET_YES  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST1ST__RESET_NO
 *
 * @BRIEF        No SW reset occured - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST1ST__RESET_NO   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_RSTST__RST1ST__RESET_YES
 *
 * @BRIEF        Sequencer1 has been reset upon SW reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_RSTST__RST1ST__RESET_YES  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_HWA_MEM__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_HWA_MEM__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_HWA_MEM__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_HWA_MEM__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM2_MEM__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM2_MEM__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM2_MEM__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM2_MEM__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM1_MEM__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM1_MEM__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM1_MEM__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTMEM_TCM1_MEM__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_IVAHD_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTMEM_SL2_MEM__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTMEM_SL2_MEM__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTMEM_SL2_MEM__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTMEM_SL2_MEM__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_PRM__RM_IVAHD_SL2_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __IVAHD_PRM_CRED_H 
                                                            */
