/** ==================================================================
 *  @file   ivahd_sysctrl_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   IVAHD_SYSCTRL
 *
 *  @Filename:    ivahd_sysctrl_cred.h
 *
 *  @Description: Sysctrl module registers 
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __IVAHD_SYSCTRL_CRED_H
#define __IVAHD_SYSCTRL_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance SYSCTRL of component IVAHD_SYSCTRL mapped in MONICA at address 0x5A05A400
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component IVAHD_SYSCTRL
     *
     */

    /* 
     *  List of bundle arrays for component IVAHD_SYSCTRL
     *
     */

    /* 
     *  List of bundles for component IVAHD_SYSCTRL
     *
     */

    /* 
     * List of registers for component IVAHD_SYSCTRL
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION
 *
 * @BRIEF        IVA-HD Revision Identifier (X.Y.R) 
 *               Used by software to track features, bugs, and compatibility 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION                      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO
 *
 * @BRIEF        Information about the IP module's hardware configuration. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO                        0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG
 *
 * @BRIEF        Clock management configuration 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG                     0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQ_EOI
 *
 * @BRIEF        End Of Interrupt number specification 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQ_EOI                       0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW
 *
 * @BRIEF        Per-event raw interrupt status vector. 
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW                 0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #0. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS                     0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET
 *
 * @BRIEF        Per-event interrupt enable bit vector.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET                 0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR
 *
 * @BRIEF        Per-event interrupt enable bit vector.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR                 0x30ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS_RAW
 *
 * @BRIEF        Per-event raw interrupt status vector. 
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS_RAW            0x34ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS
 *
 * @BRIEF        Per-event "enabled" interrupt status vector, line #0. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS                0x38ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_SET
 *
 * @BRIEF        Per-event interrupt enable bit vector.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_SET            0x3Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_CLR
 *
 * @BRIEF        Per-event interrupt enable bit vector.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_CLR            0x40ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL
 *
 * @BRIEF        IVAHD clock control register 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL                       0x50ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST
 *
 * @BRIEF        IVA-HD clock status register.  
 *               Each bitfield of this register is set to '0' when sub-module 
 *               is in idle state otherwise set to '1'. 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST                         0x54ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_STDBYST
 *
 * @BRIEF        IVA-HD STANDBY status 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_STDBYST                       0x58ul

    /* 
     * List of register bitfields for component IVAHD_SYSCTRL
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__SCHEME   
 *
 * @BRIEF        Used to distinguish between old scheme and current. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__SCHEME         BITFIELD(31, 30)
#define IVAHD_SYSCTRL__IVAHD_REVISION__SCHEME__POS    30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__FUNC   
 *
 * @BRIEF        Function indicates a software compatible module family.   
 *               If there is no level of software compatibility a new Func 
 *               number (and hence REVISION) should be assigned. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__FUNC           BITFIELD(27, 16)
#define IVAHD_SYSCTRL__IVAHD_REVISION__FUNC__POS      16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__R_RTL   
 *
 * @BRIEF        RTL Version (R), maintained by IP design owner.  
 *               RTL follows a numbering such as X.Y.R.Z which are explained 
 *               in this table.  
 *               R changes ONLY when:  
 *               (1) PDS uploads occur which may have been due to spec 
 *               changes  
 *               (2) Bug fixes occur  
 *               (3) Resets to '0' when X or Y changes.  
 *               Design team has an internal 'Z' (customer invisible) number 
 *               which increments on every drop that happens due to DV and 
 *               RTL updates. Z resets to 0 when R increments. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__R_RTL          BITFIELD(15, 11)
#define IVAHD_SYSCTRL__IVAHD_REVISION__R_RTL__POS     11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__X_MAJOR   
 *
 * @BRIEF        Major Revision (X), maintained by IP specification owner.  
 *               X changes ONLY when:  
 *               (1) There is a major feature addition. An example would be 
 *               adding Master Mode to Utopia Level2. The Func field (or 
 *               Class/Type in old PID format) will remain the same.  
 *               X does NOT change due to:  
 *               (1) Bug fixes  
 *               (2) Change in feature parameters. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__X_MAJOR        BITFIELD(10, 8)
#define IVAHD_SYSCTRL__IVAHD_REVISION__X_MAJOR__POS   8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__CUSTOM   
 *
 * @BRIEF        Indicates a special version for a particular device. 
 *               Consequence of use may avoid use of standard Chip Support 
 *               Library (CSL) / Drivers. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__CUSTOM         BITFIELD(7, 6)
#define IVAHD_SYSCTRL__IVAHD_REVISION__CUSTOM__POS    6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__Y_MINOR   
 *
 * @BRIEF        Minor Revision (Y), maintained by IP specification owner.  
 *               Y changes ONLY when:  
 *               (1) Features are scaled (up or down). Flexibility exists in 
 *               that this feature scalability may either be represented in 
 *               the Y change or a specific register in the IP that indicates 
 *               which features are exactly available.  
 *               (2) When feature creeps from Is-Not list to Is list. But 
 *               this may not be the case once it sees silicon; in which case 
 *               X will change.  
 *               Y does NOT change due to:  
 *               (1) Bug fixes  
 *               (2) Typos or clarifications  
 *               (3) major functional/feature change/addition/deletion. 
 *               Instead these changes may be reflected via R, S, X as 
 *               applicable.  
 *               Spec owner maintains a customer-invisible number 'S' which 
 *               changes due to:  
 *               (1) Typos/clarifications  
 *               (2) Bug documentation. Note that this bug is not due to a 
 *               spec change but due to implementation. Nevertheless, the 
 *               spec tracks the IP bugs. An RTL release (say for silicon 
 *               PG1.1) that occurs due to bug fix should document the 
 *               corresponding spec number (X.Y.S) in its release notes. - 
 *               (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__Y_MINOR        BITFIELD(5, 0)
#define IVAHD_SYSCTRL__IVAHD_REVISION__Y_MINOR__POS   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__RESERVED   
 *
 * @BRIEF        Reserved - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__RESERVED         BITFIELD(31, 15)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__RESERVED__POS    15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__ECD3   
 *
 * @BRIEF        ECD3 available 
 *               0: ECD3 not present 
 *               1: ECD3 present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__ECD3             BITFIELD(14, 14)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__ECD3__POS        14

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__MC3   
 *
 * @BRIEF        MC3 available 
 *               0: MC3 not present 
 *               1: MC3 present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__MC3              BITFIELD(13, 13)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__MC3__POS         13

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__IPE3   
 *
 * @BRIEF        IPE3 available 
 *               0: IPE3 not present 
 *               1: IPE3 present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__IPE3             BITFIELD(12, 12)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__IPE3__POS        12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__CALC3   
 *
 * @BRIEF        CALC3 available 
 *               0: CALC3 not present 
 *               1: CALC3 present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__CALC3            BITFIELD(11, 11)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__CALC3__POS       11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__IME3   
 *
 * @BRIEF        IME3 available 
 *               0: IME3 not present 
 *               1: IME3 present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__IME3             BITFIELD(10, 10)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__IME3__POS        10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__ILF3   
 *
 * @BRIEF        ILF3 available 
 *               0: ILF3 not present 
 *               1: ILF3 present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__ILF3             BITFIELD(9, 9)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__ILF3__POS        9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__VDMA   
 *
 * @BRIEF        VDMA available 
 *               0: VDMA not present 
 *               1: VDMA present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__VDMA             BITFIELD(8, 8)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__VDMA__POS        8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__ICONT2   
 *
 * @BRIEF        ICONT2 available 
 *               0: ICONT2 not present 
 *               1: ICONT2 present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__ICONT2           BITFIELD(7, 7)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__ICONT2__POS      7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__ICONT1   
 *
 * @BRIEF        ICONT1 available 
 *               0: ICONT1 not present 
 *               1: ICONT1 present - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__ICONT1           BITFIELD(6, 6)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__ICONT1__POS      6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK   
 *
 * @BRIEF        Bitfield description is not available - (RO)
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK          BITFIELD(5, 4)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__POS     4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE   
 *
 * @BRIEF        Size of SL2 memory - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE          BITFIELD(3, 0)
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE   
 *
 * @BRIEF        Configuration of the local initiator state management mode. 
 *               By definition, initiator may generate read/write transaction 
 *               as long as it is out of STANDBY state. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE   BITFIELD(5, 4)
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE   
 *
 * @BRIEF        Configuration of the local target state management mode. 
 *               By definition, target can handle read/write transaction as 
 *               long as it is out of IDLE state. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE      BITFIELD(3, 2)
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER   
 *
 * @BRIEF        Software End Of Interrupt (EOI) control. Write number of 
 *               interrupt output. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER     BITFIELD(0, 0)
#define IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR   
 *
 * @BRIEF        settable raw status for Clock Programming Error event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR BITFIELD(0, 0)
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR   
 *
 * @BRIEF        clearable, enabled status for Clock Programming Error event 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR BITFIELD(0, 0)
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR   
 *
 * @BRIEF        Clock Programing Error - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR BITFIELD(0, 0)
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR   
 *
 * @BRIEF        Clock Programing Error - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR BITFIELD(0, 0)
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS_RAW__SYNC_INPUT7_0   
 *
 * @BRIEF        Settable raw status for SYNC INPUT event. 
 *               For each bit of the bitfield: 
 *                 Read 0: No event pending  
 *                 Read 1: Event pending  
 *                 Write 0: No action  
 *                 Write 1: Set event (debug) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS_RAW__SYNC_INPUT7_0 BITFIELD(7, 0)
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS_RAW__SYNC_INPUT7_0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS__SYNC_INPUT7_0   
 *
 * @BRIEF        Clearable, enabled status for SYNC INPUT event. 
 *               For each bit of the bitfield: 
 *                 Read 0: No (enabled) event pending  
 *                 Read 1: Event pending  
 *                 Write 0: No action  
 *                 Write 1: Clear (raw) event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS__SYNC_INPUT7_0 BITFIELD(7, 0)
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQSTATUS__SYNC_INPUT7_0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_SET__SYNC_INPUT7_0   
 *
 * @BRIEF        Enable for interrupt event. 
 *               For each bit of the bitfield: 
 *                 Read 0: Interrupt disabled (masked)  
 *                 Read 1: Interrupt enabled  
 *                 Write 0: No action  
 *                 Write 1: Enable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_SET__SYNC_INPUT7_0 BITFIELD(7, 0)
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_SET__SYNC_INPUT7_0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_CLR__SYNC_INPUT7_0   
 *
 * @BRIEF        Enable for interrupt event. 
 *               For each bit of the bitfiled: 
 *                 Read 0: Interrupt disabled (masked)  
 *                 Read 1: Interrupt enabled  
 *                 Write 0: No action  
 *                 Write 1: Disable interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_CLR__SYNC_INPUT7_0 BITFIELD(7, 0)
#define IVAHD_SYSCTRL__IVAHD_SYNC_IRQENABLE_CLR__SYNC_INPUT7_0__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__SMSET   
 *
 * @BRIEF        Clock control of SMSET 
 *                 0: Exit idle state and start SMSET clock 
 *                 1: Request SMSET to go to idle state and stop SMSET clock 
 *               Note: Shutting-down SMSET clock may hang system if SW 
 *               performs SW instrumentation and/or access to its 
 *               configuration port. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__SMSET           BITFIELD(10, 10)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__SMSET__POS      10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__MSGIF   
 *
 * @BRIEF        Clock control of MSGIF 
 *                 0: Exit idle state and start MSGIF clock 
 *                 1: Request MSGIF to go to idle state and stop MSGIF clock 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__MSGIF           BITFIELD(9, 9)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__MSGIF__POS      9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__ECD3   
 *
 * @BRIEF        Clock control of ECD3 
 *                 0: Exit idle state and start ECD3 clock 
 *                 1: Request ECD3 to go to idle state and stop ECD3 clock - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__ECD3            BITFIELD(8, 8)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__ECD3__POS       8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__MC3   
 *
 * @BRIEF        Clock control of MC3 
 *                 0: Exit idle state and start MC3 clock 
 *                 1: Request MC3 to go to idle state and stop MC3 clock - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__MC3             BITFIELD(7, 7)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__MC3__POS        7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__IPE3   
 *
 * @BRIEF        Clock control of IPE3 
 *                 0: Exit idle state and start IPE3 clock 
 *                 1: Request IME3 to go to idle state and stop IPE3 clock - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__IPE3            BITFIELD(6, 6)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__IPE3__POS       6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__CALC3   
 *
 * @BRIEF        Clock control of CALC3 
 *                 0: Exit idle state and start CALC3 clock 
 *                 1: Request CALC3 to go to idle state and stop CALC3 clock 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__CALC3           BITFIELD(5, 5)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__CALC3__POS      5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__ILF3   
 *
 * @BRIEF        Clock control of ILF3 
 *                 0: Exit idle state and start ILF3 clock 
 *                 1: Request ILF3 to go to idle state and stop ILF3 clock - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__ILF3            BITFIELD(4, 4)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__ILF3__POS       4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__IME3   
 *
 * @BRIEF        Clock control of IME3 
 *                 0: Exit idle state and start IME3 clock 
 *                 1: Request IME3 to go to idle state and stop IME3 clock - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__IME3            BITFIELD(3, 3)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__IME3__POS       3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__VDMA   
 *
 * @BRIEF        Clock control of VDMA 
 *                 0: Exit idle state and start VDMA clock 
 *                 1: Request VDMA to go to idle state and stop VDMA clock - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__VDMA            BITFIELD(2, 2)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__VDMA__POS       2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__ICONT2   
 *
 * @BRIEF        Clock control of ICONT2 
 *                 0: Exit idle state and start ICONT2 clock 
 *                 1: Request ICONT2 to go to idle state and stop ICONT2 
 *               clock - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__ICONT2          BITFIELD(1, 1)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__ICONT2__POS     1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKCTRL__ICONT1   
 *
 * @BRIEF        Clock control of ICONT1 
 *                 0: Exit idle state and start ICONT1 clock 
 *                 1: Request ICONT1 to go to idle state and stop ICONT1 
 *               clock - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__ICONT1          BITFIELD(0, 0)
#define IVAHD_SYSCTRL__IVAHD_CLKCTRL__ICONT1__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__SMSET   
 *
 * @BRIEF        Clock status of SMSET 
 *                 1: SMSET clock is active 
 *                 0: SMSET clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__SMSET             BITFIELD(10, 10)
#define IVAHD_SYSCTRL__IVAHD_CLKST__SMSET__POS        10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__MSGIF   
 *
 * @BRIEF        Clock status of MSGIF 
 *                 1: MSGIF clock is active 
 *                 0: MSGIF clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__MSGIF             BITFIELD(9, 9)
#define IVAHD_SYSCTRL__IVAHD_CLKST__MSGIF__POS        9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__ECD3   
 *
 * @BRIEF        Clock status of ECD3 
 *                 1: ECD3 clock is active 
 *                 0: ECD3 clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__ECD3              BITFIELD(8, 8)
#define IVAHD_SYSCTRL__IVAHD_CLKST__ECD3__POS         8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__MC3   
 *
 * @BRIEF        Clock status of MC3 
 *                 1: MC3 clock is active 
 *                 0: MC3 clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__MC3               BITFIELD(7, 7)
#define IVAHD_SYSCTRL__IVAHD_CLKST__MC3__POS          7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__IPE3   
 *
 * @BRIEF        Clock status of IPE3 
 *                 1: IPE3 clock is active 
 *                 0: IPE3 clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__IPE3              BITFIELD(6, 6)
#define IVAHD_SYSCTRL__IVAHD_CLKST__IPE3__POS         6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__CALC3   
 *
 * @BRIEF        Clock status of CALC3 
 *                 1: CALC3 clock is active 
 *                 0: CALC3 clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__CALC3             BITFIELD(5, 5)
#define IVAHD_SYSCTRL__IVAHD_CLKST__CALC3__POS        5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__ILF3   
 *
 * @BRIEF        Clock status of ILF3 
 *                 1: ILF3 clock is active 
 *                 0: ILF3 clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__ILF3              BITFIELD(4, 4)
#define IVAHD_SYSCTRL__IVAHD_CLKST__ILF3__POS         4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__IME3   
 *
 * @BRIEF        Clock status of IME3 
 *                 1: IME3 clock is active 
 *                 0: IME3 clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__IME3              BITFIELD(3, 3)
#define IVAHD_SYSCTRL__IVAHD_CLKST__IME3__POS         3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__VDMA   
 *
 * @BRIEF        Clock status of VDMA 
 *                 1: VDMA clock is active 
 *                 0: VDMA clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__VDMA              BITFIELD(2, 2)
#define IVAHD_SYSCTRL__IVAHD_CLKST__VDMA__POS         2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__ICONT2   
 *
 * @BRIEF        Clock status of ICONT2 
 *                 1: ICONT2 clock is active 
 *                 0: ICONT2 clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__ICONT2            BITFIELD(1, 1)
#define IVAHD_SYSCTRL__IVAHD_CLKST__ICONT2__POS       1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_CLKST__ICONT1   
 *
 * @BRIEF        Clock status of ICONT1 
 *                 1: ICONT1 clock is active 
 *                 0: ICONT1 clock is idled - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_CLKST__ICONT1            BITFIELD(0, 0)
#define IVAHD_SYSCTRL__IVAHD_CLKST__ICONT1__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_STDBYST__VDMA   
 *
 * @BRIEF        VDMA Standby status 
 *                 0: module is not in Standby 
 *                 1: module is in Standby - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_STDBYST__VDMA            BITFIELD(2, 2)
#define IVAHD_SYSCTRL__IVAHD_STDBYST__VDMA__POS       2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_STDBYST__ICONT2   
 *
 * @BRIEF        ICONT2 Standby status 
 *                 0: module is not in Standby 
 *                 1: module is in Standby - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_STDBYST__ICONT2          BITFIELD(1, 1)
#define IVAHD_SYSCTRL__IVAHD_STDBYST__ICONT2__POS     1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_STDBYST__ICONT1   
 *
 * @BRIEF        ICONT1 Standby status 
 *                 0: module is not in Standby 
 *                 1: module is in Standby - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_STDBYST__ICONT1          BITFIELD(0, 0)
#define IVAHD_SYSCTRL__IVAHD_STDBYST__ICONT1__POS     0

    /* 
     * List of register bitfields values for component IVAHD_SYSCTRL
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__SCHEME__LEGACY
 *
 * @BRIEF        Legacy ASP or WTBU scheme - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__SCHEME__LEGACY 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__SCHEME__H08
 *
 * @BRIEF        Highlander 0.8 scheme - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__SCHEME__H08    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_REVISION__CUSTOM__STANDARD
 *
 * @BRIEF        Non custom (standard) revision - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_REVISION__CUSTOM__STANDARD 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__1BANK
 *
 * @BRIEF        1 memory bank - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__1BANK   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__2BANK
 *
 * @BRIEF        2 memory bank - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__2BANK   0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__4BANK
 *
 * @BRIEF        4 memory bank - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__4BANK   0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__8BANK
 *
 * @BRIEF        8 memory bank - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2BANK__8BANK   0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__16KB
 *
 * @BRIEF        16 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__16KB    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__32KB
 *
 * @BRIEF        32 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__32KB    0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__48KB
 *
 * @BRIEF        48kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__48KB    0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__64KB
 *
 * @BRIEF        64 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__64KB    0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__96KB
 *
 * @BRIEF        96 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__96KB    0x5ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__128KB
 *
 * @BRIEF        128 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__128KB   0x6ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__160KB
 *
 * @BRIEF        160 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__160KB   0x7ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__192KB
 *
 * @BRIEF        192 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__192KB   0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__224KB
 *
 * @BRIEF        224 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__224KB   0x9ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__256KB
 *
 * @BRIEF        256 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__256KB   0xAul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__320KB
 *
 * @BRIEF        320kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__320KB   0xBul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__384KB
 *
 * @BRIEF        384 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__384KB   0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__448KB
 *
 * @BRIEF        448 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__448KB   0xDul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__512KB
 *
 * @BRIEF        512 kBytes - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_HWINFO__SL2SIZE__512KB   0xEul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__RESERVED
 *
 * @BRIEF        Reserved - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__RESERVED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__NO
 *
 * @BRIEF        No-standby mode: local initiator is unconditionally placed 
 *               out of standby state. 
 *               Backup mode, for debug only. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__NO 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__SMART
 *
 * @BRIEF        Smart-standby mode: local initiator standby status depends 
 *               on local conditions, i.e. the module's functional 
 *               requirement from the initiator. 
 *               IP module shall not generate (initiator-related) wakeup 
 *               events. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__SMART 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__RESERVED1
 *
 * @BRIEF        Reserved - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__STANDBYMODE__RESERVED1 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__RESERVED
 *
 * @BRIEF        reserved - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__RESERVED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__NO
 *
 * @BRIEF        No-idle mode: local target never enters idle state. 
 *               Backup mode, for debug only. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__NO  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__SMART
 *
 * @BRIEF        Smart-idle mode: local target's idle state eventually 
 *               follows (acknowledges) the system's idle requests, depending 
 *               on the IP module's internal requirements. 
 *               IP module shall not generate (IRQ- or DMA-request-related) 
 *               wakeup events. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__SMART 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__RESERVED1
 *
 * @BRIEF        Reserved - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_SYSCONFIG__IDLEMODE__RESERVED1 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER__READ0
 *
 * @BRIEF        Reads always 0 (no EOI memory) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER__READ0 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER__EOI0
 *
 * @BRIEF        EOI for SYSCTRL error interrupt output line - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER__EOI0 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER__EOI1
 *
 * @BRIEF        EOI for SYSCTRL SYNC interrupt output line - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQ_EOI__LINE_NUMBER__EOI1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__NOACTION
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__NOACTION 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__NOEVENT
 *
 * @BRIEF        No event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__NOEVENT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__PENDING
 *
 * @BRIEF        Event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__PENDING 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__SET
 *
 * @BRIEF        Set event (debug) - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS_RAW__SYSCTRL_CLKERR__SET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__NOACTION
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__NOACTION 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__NOEVENT
 *
 * @BRIEF        No (enabled) event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__NOEVENT 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__PENDING
 *
 * @BRIEF        Event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__PENDING 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__CLEAR
 *
 * @BRIEF        Clear (raw) event - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQSTATUS__SYSCTRL_CLKERR__CLEAR 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__NOACTION
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__NOACTION 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__DISABLED
 *
 * @BRIEF        Interrupt disabled (masked) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__ENABLED
 *
 * @BRIEF        Interrupt enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__ENABLE
 *
 * @BRIEF        Enable interrupt - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_SET__SYSCTRL_CLKERR__ENABLE 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__NOACTION
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__NOACTION 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__DISABLED
 *
 * @BRIEF        Interrupt disabled (masked) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__ENABLED
 *
 * @BRIEF        Interrupt enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__DISABLE
 *
 * @BRIEF        Disable interrupt - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define IVAHD_SYSCTRL__IVAHD_IRQENABLE_CLR__SYSCTRL_CLKERR__DISABLE 0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __IVAHD_SYSCTRL_CRED_H 
                                                            */
