/** ==================================================================
 *  @file   ldc_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   LDC
 *
 *  @Filename:    ldc_cred.h
 *
 * *  @Description: The Lens Distortion Correction (LDC) module performs a 
 *                geometric warping of an image.   
 *                  It accepts YUV420 and YUV422 formats.  It also supports 
 *                Bayer data in chromatic aberration  
 *                mode. 
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __LDC_CRED_H
#define __LDC_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance LDC of component LDC mapped in MONICA at address 0x55060100
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component LDC
     *
     */

    /* 
     *  List of bundle arrays for component LDC
     *
     */

    /* 
     *  List of bundles for component LDC
     *
     */

    /* 
     * List of registers for component LDC
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PID
 *
 * @BRIEF        LDC Peripheral ID 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PID                                       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PCR
 *
 * @BRIEF        LDC Peripheral Control 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PCR                                       0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_RD_BASE
 *
 * @BRIEF        LDC Read Frame Base 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_RD_BASE                                   0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_RD_OFST
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_RD_OFST                                   0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_FRAME_SIZE
 *
 * @BRIEF        LDC Frame Size 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_FRAME_SIZE                                0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_INITXY
 *
 * @BRIEF        LDC Initial XY 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_INITXY                                    0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_WR_BASE
 *
 * @BRIEF        LDC Write Frame Base 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_WR_BASE                                   0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_WR_OFST
 *
 * @BRIEF        LDC Write Frame Line Offset 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_WR_OFST                                   0x1Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_420C_RD_BASE
 *
 * @BRIEF        LDC Read Frame Base For Cb/Cr in 420 Mode 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_420C_RD_BASE                              0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_420C_WR_BASE
 *
 * @BRIEF        LDC Write Frame Base for Cb/Cr in 420 Mode 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_420C_WR_BASE                              0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CONFIG
 *
 * @BRIEF        LDC Configuration 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CONFIG                                    0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CENTER
 *
 * @BRIEF        LDC Lens Center 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CENTER                                    0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_KHV
 *
 * @BRIEF        LDC Horizontal/Vertical Scaling Factor 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_KHV                                       0x30ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_BLOCK
 *
 * @BRIEF        LDC Block Size 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_BLOCK                                     0x34ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_LUT_ADDR
 *
 * @BRIEF        LDC LUT Initial Address 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_LUT_ADDR                                  0x38ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_LUT_WDATA
 *
 * @BRIEF        LDC LUT Write Data 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_LUT_WDATA                                 0x3Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_LUT_RDATA
 *
 * @BRIEF        LDC LUT Read Data 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_LUT_RDATA                                 0x40ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_AB
 *
 * @BRIEF        LDC Affine Transwarp A/B 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_AB                                        0x44ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CD
 *
 * @BRIEF        LDC Affine Transwarp C/D 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CD                                        0x48ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_EF
 *
 * @BRIEF        LDC Affine Transwarp EF 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_EF                                        0x4Cul

    /* 
     * List of register bitfields for component LDC
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PID__TID   
 *
 * @BRIEF        Peripheral ID - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PID__TID                             BITFIELD(23, 16)
#define LDC__LDC_PID__TID__POS                        16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PID__CID   
 *
 * @BRIEF        Class ID - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PID__CID                             BITFIELD(15, 8)
#define LDC__LDC_PID__CID__POS                        8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PID__PREV   
 *
 * @BRIEF        Revision ID - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PID__PREV                            BITFIELD(7, 0)
#define LDC__LDC_PID__PREV__POS                       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PCR__BMODE   
 *
 * @BRIEF        Bayer data format (only applicable when MODE=1).  3:  A-law 
 *               data in/out,  2: Packed 8-bit data in/out,  1: Packed 12-bit 
 *               data in/out,  0: Unpacked 12-bit data in/out - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PCR__BMODE                           BITFIELD(6, 5)
#define LDC__LDC_PCR__BMODE__POS                      5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PCR__MODE   
 *
 * @BRIEF        2: YCbCr 4:2:0 Lens Distortion, 1:  Bayer chromatic 
 *               aberration mode, 0: YCbCr 4:2:2 Lens Distortion - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PCR__MODE                            BITFIELD(4, 3)
#define LDC__LDC_PCR__MODE__POS                       3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PCR__BUSY   
 *
 * @BRIEF        Idle/busy status, 0: Idle, 1: Busy, asserted when function 
 *               is started, cleared when function is complete - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PCR__BUSY                            BITFIELD(2, 2)
#define LDC__LDC_PCR__BUSY__POS                       2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PCR__LDMAPEN   
 *
 * @BRIEF        LD Mapping Enable, 1: Enabled, 0: Disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PCR__LDMAPEN                         BITFIELD(1, 1)
#define LDC__LDC_PCR__LDMAPEN__POS                    1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_PCR__EN   
 *
 * @BRIEF        Write 1 to start the function, as specified in MODE - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_PCR__EN                              BITFIELD(0, 0)
#define LDC__LDC_PCR__EN__POS                         0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_RD_BASE__RBASE   
 *
 * @BRIEF        Read frame base, must be 32-byte aligned so internally [4:0] 
 *               bits are hard-wired zero. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_RD_BASE__RBASE                       BITFIELD(31, 0)
#define LDC__LDC_RD_BASE__RBASE__POS                  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_RD_OFST__ROFST   
 *
 * @BRIEF        Read frame line offset, must be 32-byte aligned so 
 *               internally [4:0] bits are hard-wired zero. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_RD_OFST__ROFST                       BITFIELD(15, 0)
#define LDC__LDC_RD_OFST__ROFST__POS                  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_FRAME_SIZE__H   
 *
 * @BRIEF        Frame number of lines - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_FRAME_SIZE__H                        BITFIELD(29, 16)
#define LDC__LDC_FRAME_SIZE__H__POS                   16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_FRAME_SIZE__W   
 *
 * @BRIEF        Frame width - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_FRAME_SIZE__W                        BITFIELD(13, 0)
#define LDC__LDC_FRAME_SIZE__W__POS                   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_INITXY__INITY   
 *
 * @BRIEF        Output starting Y-coordinate (must be even) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_INITXY__INITY                        BITFIELD(29, 16)
#define LDC__LDC_INITXY__INITY__POS                   16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_INITXY__INITX   
 *
 * @BRIEF        Output starting X-coordiinate (must be even) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_INITXY__INITX                        BITFIELD(13, 0)
#define LDC__LDC_INITXY__INITX__POS                   0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_WR_BASE__WBASE   
 *
 * @BRIEF        Write frame base, must be 32-byte aligned so internally 
 *               [4:0] bits are hard-wired zero. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_WR_BASE__WBASE                       BITFIELD(31, 0)
#define LDC__LDC_WR_BASE__WBASE__POS                  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_WR_OFST__WOFST   
 *
 * @BRIEF        Write frame line offset, must be 32-byte aligned so 
 *               internally [4:0] bits are hard-wired zero. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_WR_OFST__WOFST                       BITFIELD(15, 0)
#define LDC__LDC_WR_OFST__WOFST__POS                  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_420C_RD_BASE__RBASE   
 *
 * @BRIEF        Read frame base for Cb/Cr in 420 mode, must be 32-byte 
 *               aligned so internally [4:0] bits are hard-wired zero - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_420C_RD_BASE__RBASE                  BITFIELD(31, 0)
#define LDC__LDC_420C_RD_BASE__RBASE__POS             0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_420C_WR_BASE__WBASE   
 *
 * @BRIEF        Write frame base for Cb/Cr in 420 mode, must be 32-byte 
 *               aligned so internally [4:0] bits are hard-wired zero - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_420C_WR_BASE__WBASE                  BITFIELD(31, 0)
#define LDC__LDC_420C_WR_BASE__WBASE__POS             0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CONFIG__RTH   
 *
 * @BRIEF        Threshold in back mapping - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CONFIG__RTH                          BITFIELD(29, 16)
#define LDC__LDC_CONFIG__RTH__POS                     16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CONFIG__CNST_MD   
 *
 * @BRIEF        Constant output address mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CONFIG__CNST_MD                      BITFIELD(7, 7)
#define LDC__LDC_CONFIG__CNST_MD__POS                 7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CONFIG__YINT_TYP   
 *
 * @BRIEF        Interpolation type for Y data, 0: bicubic, 1: bilinear - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CONFIG__YINT_TYP                     BITFIELD(6, 6)
#define LDC__LDC_CONFIG__YINT_TYP__POS                6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CONFIG__INITC   
 *
 * @BRIEF        Initial color for LD back mapping (Bayer mode only), 0: R, 
 *               1: Gr, 2: Gb, 3: B - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CONFIG__INITC                        BITFIELD(5, 4)
#define LDC__LDC_CONFIG__INITC__POS                   4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CONFIG__T   
 *
 * @BRIEF        Right shift bits in back mapping - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CONFIG__T                            BITFIELD(3, 0)
#define LDC__LDC_CONFIG__T__POS                       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CENTER__V0   
 *
 * @BRIEF        Lens center Y-coordinate - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CENTER__V0                           BITFIELD(29, 16)
#define LDC__LDC_CENTER__V0__POS                      16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CENTER__H0   
 *
 * @BRIEF        Lens center X-coordinate - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CENTER__H0                           BITFIELD(13, 0)
#define LDC__LDC_CENTER__H0__POS                      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_KHV__KVL   
 *
 * @BRIEF        Vertical lower scaling factor (U8) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_KHV__KVL                             BITFIELD(31, 24)
#define LDC__LDC_KHV__KVL__POS                        24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_KHV__KVU   
 *
 * @BRIEF        Vertical upper scaling factor (U8) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_KHV__KVU                             BITFIELD(23, 16)
#define LDC__LDC_KHV__KVU__POS                        16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_KHV__KHR   
 *
 * @BRIEF        Horizontal right scaling factor (U8) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_KHV__KHR                             BITFIELD(15, 8)
#define LDC__LDC_KHV__KHR__POS                        8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_KHV__KHL   
 *
 * @BRIEF        Horizontal left scaling factor (U8) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_KHV__KHL                             BITFIELD(7, 0)
#define LDC__LDC_KHV__KHL__POS                        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_BLOCK__PIXPAD   
 *
 * @BRIEF        Pixel pad (must be greater than 1) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_BLOCK__PIXPAD                        BITFIELD(19, 16)
#define LDC__LDC_BLOCK__PIXPAD__POS                   16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_BLOCK__OBH   
 *
 * @BRIEF        Output block height (must be >0 and even) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_BLOCK__OBH                           BITFIELD(15, 8)
#define LDC__LDC_BLOCK__OBH__POS                      8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_BLOCK__OBW   
 *
 * @BRIEF        Output block width (must be >0 and multiple of 16 in 422 
 *               mode or in 420 mode, 32, or in Bayer mode, 16, 32, or 64 
 *               depending on Bayer format) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_BLOCK__OBW                           BITFIELD(7, 0)
#define LDC__LDC_BLOCK__OBW__POS                      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_LUT_ADDR__ADDR   
 *
 * @BRIEF        LD LUT initial address (U8) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_LUT_ADDR__ADDR                       BITFIELD(7, 0)
#define LDC__LDC_LUT_ADDR__ADDR__POS                  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_LUT_WDATA__WDATA   
 *
 * @BRIEF        Write data, writing to this register will write to an entry 
 *               in LD LUT, pointed by LDC_LUT_ADDR, which is automatically 
 *               incremented after each write - (WO) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_LUT_WDATA__WDATA                     BITFIELD(13, 0)
#define LDC__LDC_LUT_WDATA__WDATA__POS                0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_LUT_RDATA__RDATA   
 *
 * @BRIEF        Read data, reading from this register will return an entry 
 *               in LD LUT, pointed by LDC_LUT_ADDR, which is automatically 
 *               inccremented after each read - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_LUT_RDATA__RDATA                     BITFIELD(13, 0)
#define LDC__LDC_LUT_RDATA__RDATA__POS                0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_AB__B   
 *
 * @BRIEF        Affine transwarp B (S14Q12) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_AB__B                                BITFIELD(29, 16)
#define LDC__LDC_AB__B__POS                           16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_AB__A   
 *
 * @BRIEF        Affine transwarp A (S14Q12) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_AB__A                                BITFIELD(13, 0)
#define LDC__LDC_AB__A__POS                           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CD__D   
 *
 * @BRIEF        Affine transwarp D (S14Q12) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CD__D                                BITFIELD(29, 16)
#define LDC__LDC_CD__D__POS                           16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_CD__C   
 *
 * @BRIEF        Affine transwarp C (S16Q3) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_CD__C                                BITFIELD(15, 0)
#define LDC__LDC_CD__C__POS                           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_EF__F   
 *
 * @BRIEF        Affine transwarp F (S16Q3) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_EF__F                                BITFIELD(31, 16)
#define LDC__LDC_EF__F__POS                           16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   LDC__LDC_EF__E   
 *
 * @BRIEF        Affine transwarp E (S14Q12) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define LDC__LDC_EF__E                                BITFIELD(13, 0)
#define LDC__LDC_EF__E__POS                           0

    /* 
     * List of register bitfields values for component LDC
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __LDC_CRED_H */
