/** ==================================================================
 *  @file   monica_l4cfg_ia_ip0_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   MONICA_L4CFG_IA_IP0
 *
 *  @Filename:    monica_l4cfg_ia_ip0_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __MONICA_L4CFG_IA_IP0_CRED_H
#define __MONICA_L4CFG_IA_IP0_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance MONICA_L4CFG_IA_IP0 of component MONICA_L4CFG_IA_IP0 mapped in MONICA at address 0x4A000800
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_64

    /* 
     *  List of Register arrays for component MONICA_L4CFG_IA_IP0
     *
     */

    /* 
     *  List of bundle arrays for component MONICA_L4CFG_IA_IP0
     *
     */

    /* 
     *  List of bundles for component MONICA_L4CFG_IA_IP0
     *
     */

    /* 
     * List of registers for component MONICA_L4CFG_IA_IP0
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__COMPONENT
 *
 * @BRIEF        ID of the component 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__COMPONENT                     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__CORE
 *
 * @BRIEF        ID of the core 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__CORE                          0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_CONTROL
 *
 * @BRIEF        Core control for an initiator OCP interface 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL                 0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_STATUS
 *
 * @BRIEF        Core status for an initiator OCP interface 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS                  0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG
 *
 * @BRIEF        Extended error log (error code and request details other 
 *               than address) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG                     0x58ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG_ADDR
 *
 * @BRIEF        Extended error log (address information) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG_ADDR                0x60ul

    /* 
     * List of register bitfields for component MONICA_L4CFG_IA_IP0
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__COMPONENT__CODE   
 *
 * @BRIEF        Interconnect code - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__COMPONENT__CODE          BITFIELD(31, 16)
#define MONICA_L4CFG_IA_IP0__COMPONENT__CODE__POS     16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__COMPONENT__REV   
 *
 * @BRIEF        Sonics3220 revision - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__COMPONENT__REV           BITFIELD(15, 0)
#define MONICA_L4CFG_IA_IP0__COMPONENT__REV__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__CORE__VENDOR_CODE   
 *
 * @BRIEF        Vendor code - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__CORE__VENDOR_CODE        BITFIELD(47, 32)
#define MONICA_L4CFG_IA_IP0__CORE__VENDOR_CODE__POS   32

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__CORE__CORE_CODE   
 *
 * @BRIEF        Core code - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__CORE__CORE_CODE          BITFIELD(31, 16)
#define MONICA_L4CFG_IA_IP0__CORE__CORE_CODE__POS     16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__CORE__REV_CODE   
 *
 * @BRIEF        Revision code - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__CORE__REV_CODE           BITFIELD(15, 0)
#define MONICA_L4CFG_IA_IP0__CORE__REV_CODE__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_CONTROL__PROT_ERROR_SECONDARY_REP   
 *
 * @BRIEF        Out-of-band reporting of protection mechanism secondary 
 *               errors - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL__PROT_ERROR_SECONDARY_REP BITFIELD(31, 31)
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL__PROT_ERROR_SECONDARY_REP__POS 31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_CONTROL__PROT_ERROR_PRIMARY_REP   
 *
 * @BRIEF        Out-of-band reporting of protection mechanism primary errors 
 *               - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL__PROT_ERROR_PRIMARY_REP BITFIELD(30, 30)
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL__PROT_ERROR_PRIMARY_REP__POS 30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_CONTROL__INBAND_ERROR_REP   
 *
 * @BRIEF        Reporting of errors - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL__INBAND_ERROR_REP BITFIELD(27, 27)
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL__INBAND_ERROR_REP__POS 27

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_CONTROL__MERROR_REP   
 *
 * @BRIEF        OCP MError reporting control - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL__MERROR_REP BITFIELD(24, 24)
#define MONICA_L4CFG_IA_IP0__AGENT_CONTROL__MERROR_REP__POS 24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_STATUS__PROT_ERROR_SECONDARY   
 *
 * @BRIEF        Protection error status. MErrorSteer indicates a secondary 
 *               error. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS__PROT_ERROR_SECONDARY BITFIELD(31, 31)
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS__PROT_ERROR_SECONDARY__POS 31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_STATUS__PROT_ERROR_PRIMARY   
 *
 * @BRIEF        Protection error status. MErrorSteer indicates a primary 
 *               error (or is not enabled). - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS__PROT_ERROR_PRIMARY BITFIELD(30, 30)
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS__PROT_ERROR_PRIMARY__POS 30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_STATUS__INBAND_ERROR   
 *
 * @BRIEF        Error status - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS__INBAND_ERROR BITFIELD(27, 27)
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS__INBAND_ERROR__POS 27

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__AGENT_STATUS__MERROR   
 *
 * @BRIEF        Value of the OCP MError signal - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS__MERROR     BITFIELD(24, 24)
#define MONICA_L4CFG_IA_IP0__AGENT_STATUS__MERROR__POS 24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__REQ_INFO   
 *
 * @BRIEF        MReqInfo bits of request that caused the error - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__REQ_INFO      BITFIELD(47, 32)
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__REQ_INFO__POS 32

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__MULTI   
 *
 * @BRIEF        Multiple errors detected - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__MULTI         BITFIELD(31, 31)
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__MULTI__POS    31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__SECONDARY   
 *
 * @BRIEF        Indicates whether protection violation was a primary or 
 *               secondary error - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__SECONDARY     BITFIELD(30, 30)
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__SECONDARY__POS 30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE   
 *
 * @BRIEF        Initiator request error code - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE          BITFIELD(25, 24)
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__POS     24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__CONNID   
 *
 * @BRIEF        ConnID of request causing the error - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CONNID        BITFIELD(13, 8)
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CONNID__POS   8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__CMD   
 *
 * @BRIEF        Command that caused error - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CMD           BITFIELD(2, 0)
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CMD__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG_ADDR__ADDR   
 *
 * @BRIEF        Address of request that caused the error. N is the number 
 *               MAddr bits. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG_ADDR__ADDR     BITFIELD(31, 0)
#define MONICA_L4CFG_IA_IP0__ERROR_LOG_ADDR__ADDR__POS 0

    /* 
     * List of register bitfields values for component MONICA_L4CFG_IA_IP0
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__IA_IP0_ERROR_LOG_CODE_0
 *
 * @BRIEF        no errors - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__IA_IP0_ERROR_LOG_CODE_0 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__IA_IP0_ERROR_LOG_CODE_1
 *
 * @BRIEF        reserved - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__IA_IP0_ERROR_LOG_CODE_1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__IA_IP0_ERROR_LOG_CODE_2
 *
 * @BRIEF        address hole error - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__IA_IP0_ERROR_LOG_CODE_2 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__IA_IP0_ERROR_LOG_CODE_3
 *
 * @BRIEF        protection violation - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define MONICA_L4CFG_IA_IP0__ERROR_LOG__CODE__IA_IP0_ERROR_LOG_CODE_3 0x3ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __MONICA_L4CFG_IA_IP0_CRED_H 
                                                            */
