/** ==================================================================
 *  @file   tesla_prm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   TESLA_PRM
 *
 *  @Filename:    tesla_prm_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __TESLA_PRM_CRED_H
#define __TESLA_PRM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance TESLA_PRM of component TESLA_PRM mapped in MONICA at address 0x4A306400
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component TESLA_PRM
     *
     */

    /* 
     *  List of bundle arrays for component TESLA_PRM
     *
     */

    /* 
     *  List of bundles for component TESLA_PRM
     *
     */

    /* 
     * List of registers for component TESLA_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL
 *
 * @BRIEF        This register controls the TESLA power state to reach upon a 
 *               domain sleep transition 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL                      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST
 *
 * @BRIEF        This register provides a status on the TESLA domain current 
 *               power state. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST                        0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTCTRL
 *
 * @BRIEF        This register controls the release of the TESLA sub-system 
 *               resets. 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTCTRL                        0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST
 *
 * @BRIEF        This register logs the different reset sources of the Tesla 
 *               domain. Each bit is set upon release of the domain reset 
 *               signal. Must be cleared by software. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST                          0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT
 *
 * @BRIEF        This register contains dedicated TESLA context statuses. 
 *               [warm reset insensitive] 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT                  0x24ul

    /* 
     * List of register bitfields for component TESLA_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_ONSTATE   
 *
 * @BRIEF        TESLA_EDMA  state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_ONSTATE BITFIELD(21, 20)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_ONSTATE__POS 20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_ONSTATE   
 *
 * @BRIEF        TESLA_L2  state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_ONSTATE BITFIELD(19, 18)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_ONSTATE__POS 18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_ONSTATE   
 *
 * @BRIEF        TESLA_L1  state when domain is ON. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_ONSTATE BITFIELD(17, 16)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_ONSTATE__POS 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_RETSTATE   
 *
 * @BRIEF        TESLA_EDMA state when domain is RETENTION. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_RETSTATE BITFIELD(10, 10)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_RETSTATE__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_RETSTATE   
 *
 * @BRIEF        TESLA_L2  state when domain is RETENTION. 
 *               Should always stay high according to use-case definition. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_RETSTATE BITFIELD(9, 9)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_RETSTATE__POS 9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_RETSTATE   
 *
 * @BRIEF        TESLA_L2  state when domain is RETENTION. 
 *               Should always stay high according to use-case definition. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_RETSTATE BITFIELD(8, 8)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_RETSTATE__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__LOWPOWERSTATECHANGE   
 *
 * @BRIEF        Power state change request when domain has already performed 
 *               a sleep transition. Allows going into deeper low power state 
 *               without waking up the power domain. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__LOWPOWERSTATECHANGE BITFIELD(4, 4)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__LOWPOWERSTATECHANGE__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__LOGICRETSTATE   
 *
 * @BRIEF        Logic state when power domain is RETENTION - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__LOGICRETSTATE  BITFIELD(2, 2)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__LOGICRETSTATE__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE   
 *
 * @BRIEF        Power state control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE     BITFIELD(1, 0)
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__INTRANSITION   
 *
 * @BRIEF        Domain transition status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__INTRANSITION     BITFIELD(20, 20)
#define TESLA_PRM__PM_TESLA_PWRSTST__INTRANSITION__POS 20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST   
 *
 * @BRIEF        TESLA_EDMA memory state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST BITFIELD(9, 8)
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST   
 *
 * @BRIEF        TESLA_L2 memory state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST BITFIELD(7, 6)
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST   
 *
 * @BRIEF        TESLA_L1 memory state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST BITFIELD(5, 4)
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__LOGICSTATEST   
 *
 * @BRIEF        Logic state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__LOGICSTATEST     BITFIELD(2, 2)
#define TESLA_PRM__PM_TESLA_PWRSTST__LOGICSTATEST__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST   
 *
 * @BRIEF        Current power state status - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST     BITFIELD(1, 0)
#define TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTCTRL__RST2   
 *
 * @BRIEF        TESLA - MMU, cache and slave interface reset control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTCTRL__RST2             BITFIELD(1, 1)
#define TESLA_PRM__RM_TESLA_RSTCTRL__RST2__POS        1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTCTRL__RST1   
 *
 * @BRIEF        TESLA - DSP reset control - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTCTRL__RST1             BITFIELD(0, 0)
#define TESLA_PRM__RM_TESLA_RSTCTRL__RST1__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__TESLA_DSP_EMU_REQ_RSTST   
 *
 * @BRIEF        TESLA DSP processor has been reset due to Tesla emulation 
 *               reset request  
 *               driven from TESLASS - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__TESLA_DSP_EMU_REQ_RSTST BITFIELD(3, 3)
#define TESLA_PRM__RM_TESLA_RSTST__TESLA_DSP_EMU_REQ_RSTST__POS 3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__TESLASS_EMU_RSTST   
 *
 * @BRIEF        TESLA domain has been reset due to emulation reset source  
 *               e.g. assert reset command initiated by the icepick module - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__TESLASS_EMU_RSTST  BITFIELD(2, 2)
#define TESLA_PRM__RM_TESLA_RSTST__TESLASS_EMU_RSTST__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__RST2ST   
 *
 * @BRIEF        TESLA MMU, cache and slave interface SW reset status - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__RST2ST             BITFIELD(1, 1)
#define TESLA_PRM__RM_TESLA_RSTST__RST2ST__POS        1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__RST1ST   
 *
 * @BRIEF        TESLA DSP SW reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__RST1ST             BITFIELD(0, 0)
#define TESLA_PRM__RM_TESLA_RSTST__RST1ST__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_EDMA   
 *
 * @BRIEF        Specify if memory-based context in TESLA_EDMA memory bank 
 *               has been lost due to a previous power transition or other 
 *               reset source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_EDMA BITFIELD(10, 10)
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_EDMA__POS 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L2   
 *
 * @BRIEF        Specify if memory-based context in TESLA_L2 memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L2 BITFIELD(9, 9)
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L2__POS 9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L1   
 *
 * @BRIEF        Specify if memory-based context in TESLA_L1 memory bank has 
 *               been lost due to a previous power transition or other reset 
 *               source. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L1 BITFIELD(8, 8)
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L1__POS 8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_RFF   
 *
 * @BRIEF        Specify if RFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of TESLA_RET_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_RFF BITFIELD(1, 1)
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_RFF__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_DFF   
 *
 * @BRIEF        Specify if DFF-based context has been lost due to a previous 
 *               power transition or other reset source. 
 *               (set upon assertion of TESLA_SYS_RST signal) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_DFF BITFIELD(0, 0)
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_DFF__POS 0

    /* 
     * List of register bitfields values for component TESLA_PRM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_ONSTATE__MEM_ON
 *
 * @BRIEF        Memory bank is on when the domain is ON. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_ONSTATE__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_RETSTATE__MEM_RET
 *
 * @BRIEF        Memory bank is retained when domain is in RETENTION state. - 
 *               (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_EDMA_RETSTATE__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_RETSTATE__MEM_OFF
 *
 * @BRIEF        Memory bank is off when the domain is in the RETENTION 
 *               state. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_RETSTATE__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_RETSTATE__MEM_RET
 *
 * @BRIEF        Memory bank is retained when domain is in RETENTION state. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L2_RETSTATE__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_RETSTATE__MEM_OFF
 *
 * @BRIEF        Memory bank is off when the domain is in the RETENTION 
 *               state. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_RETSTATE__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_RETSTATE__MEM_RET
 *
 * @BRIEF        Memory bank is retained when domain is in RETENTION state. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__TESLA_L1_RETSTATE__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__LOWPOWERSTATECHANGE__DIS
 *
 * @BRIEF        Do not request a low power state change. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__LOWPOWERSTATECHANGE__DIS 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__LOWPOWERSTATECHANGE__EN
 *
 * @BRIEF        Request a low power state change. This bit is automatically 
 *               cleared when the power state is effectively changed or when 
 *               power state is ON. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__LOWPOWERSTATECHANGE__EN 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__LOGICRETSTATE__LOGIC_OFF
 *
 * @BRIEF        Only retention registers are retained and remaing logic is 
 *               off when the domain is in RETENTION state. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__LOGICRETSTATE__LOGIC_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__LOGICRETSTATE__LOGIC_RET
 *
 * @BRIEF        Whole logic is retained when domain is in RETENTION state. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__LOGICRETSTATE__LOGIC_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__OFF
 *
 * @BRIEF        OFF state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__RET
 *
 * @BRIEF        RETENTION state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__INACT
 *
 * @BRIEF        INACTIVE state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__INACT 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__ON
 *
 * @BRIEF        ON State - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTCTRL__POWERSTATE__ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__INTRANSITION__NO
 *
 * @BRIEF        No on-going transition on power domain - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__INTRANSITION__NO 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__INTRANSITION__ONGOING
 *
 * @BRIEF        Power domain transition is in progress. - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__INTRANSITION__ONGOING 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__MEM_RET
 *
 * @BRIEF        Memory is RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_EDMA_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__MEM_RET
 *
 * @BRIEF        Memory is RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L2_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__MEM_OFF
 *
 * @BRIEF        Memory is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__MEM_OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__MEM_RET
 *
 * @BRIEF        Memory is RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__MEM_RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__RESERVED
 *
 * @BRIEF        Reserved - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__RESERVED 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__MEM_ON
 *
 * @BRIEF        Memory is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__TESLA_L1_STATEST__MEM_ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__LOGICSTATEST__OFF
 *
 * @BRIEF        Logic in domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__LOGICSTATEST__OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__LOGICSTATEST__ON
 *
 * @BRIEF        Logic in domain is ON - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__LOGICSTATEST__ON 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__OFF
 *
 * @BRIEF        Power domain is OFF - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__OFF 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__RET
 *
 * @BRIEF        Power domain is in RETENTION - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__RET 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__INACTIVE
 *
 * @BRIEF        Power domain is ON-INACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__INACTIVE 0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__ON
 *
 * @BRIEF        Power domain is ON-ACTIVE - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__PM_TESLA_PWRSTST__POWERSTATEST__ON 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTCTRL__RST2__CLEAR
 *
 * @BRIEF        Reset is cleared for the MMU, cache and slave interface - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTCTRL__RST2__CLEAR      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTCTRL__RST2__ASSERT
 *
 * @BRIEF        Reset is asserted for the MMU, cache and slave interface - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTCTRL__RST2__ASSERT     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTCTRL__RST1__CLEAR
 *
 * @BRIEF        Reset is cleared for the TESLA - DSP - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTCTRL__RST1__CLEAR      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTCTRL__RST1__ASSERT
 *
 * @BRIEF        Reset is asserted for the TESLA - DSP - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTCTRL__RST1__ASSERT     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__TESLA_DSP_EMU_REQ_RSTST__RESET_NO
 *
 * @BRIEF        No emulation reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__TESLA_DSP_EMU_REQ_RSTST__RESET_NO 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__TESLA_DSP_EMU_REQ_RSTST__RESET_YES
 *
 * @BRIEF        TESLA DSP has been reset upon emulation reset 
 *               request - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__TESLA_DSP_EMU_REQ_RSTST__RESET_YES 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__TESLASS_EMU_RSTST__RESET_NO
 *
 * @BRIEF        No emulation reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__TESLASS_EMU_RSTST__RESET_NO 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__TESLASS_EMU_RSTST__RESET_YES
 *
 * @BRIEF        TESLA has been reset upon emulation reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__TESLASS_EMU_RSTST__RESET_YES 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__RST2ST__RESET_NO
 *
 * @BRIEF        No SW reset occured - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__RST2ST__RESET_NO   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__RST2ST__RESET_YES
 *
 * @BRIEF        MMU, cache and slave interface has been reset upon SW reset 
 *               - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__RST2ST__RESET_YES  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__RST1ST__RESET_NO
 *
 * @BRIEF        No SW reset occured - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__RST1ST__RESET_NO   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_RSTST__RST1ST__RESET_YES
 *
 * @BRIEF        DSP has been reset upon SW reset - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_RSTST__RST1ST__RESET_YES  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_EDMA__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_EDMA__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_EDMA__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_EDMA__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L2__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L2__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L2__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L2__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L1__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L1__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L1__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTMEM_TESLA_L1__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_RFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_RFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_RFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_RFF__LOST 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED
 *
 * @BRIEF        Context has been maintained - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_DFF__MAINTAINED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_DFF__LOST
 *
 * @BRIEF        Context has been lost - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define TESLA_PRM__RM_TESLA_TESLA_CONTEXT__LOSTCONTEXT_DFF__LOST 0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __TESLA_PRM_CRED_H 
                                                            */
