/** ==================================================================
 *  @file   unipro_rmm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   UNIPRO_RMM
 *
 *  @Filename:    unipro_rmm_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __UNIPRO_RMM_CRED_H
#define __UNIPRO_RMM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance UNIPRO_RMM of component UNIPRO_RMM mapped in MONICA at address 0x4A069000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component UNIPRO_RMM
     *
     */

    /* 
     *  List of bundle arrays for component UNIPRO_RMM
     *
     */

    /* 
     *  List of bundles for component UNIPRO_RMM
     *
     */

    /* 
     * List of registers for component UNIPRO_RMM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   UNIPRO_RMM__UNIPRO_CREDITS_INC_0
 *
 * @BRIEF        Register mapped command for coherent CreditsToSend / 
 *               CFDcredits counter increment, for CPORT #0 
 *               Credits are dierctly incremented with Credits_amount in TN 
 *               accelerator cache without need for memory coherency 
 *               operation. 
 *
    *//*------------------------------------------------------------------------ */
#define UNIPRO_RMM__UNIPRO_CREDITS_INC_0                   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   UNIPRO_RMM__UNIPRO_CREDITS_INC_2047
 *
 * @BRIEF        Register mapped command for coherent CreditsToSend / 
 *               CFDcredits counter increment, for CPORT #2047 
 *               Credits are dierctly incremented with Credits_amount in TN 
 *               accelerator cache without need for memory coherency 
 *               operation. 
 *
    *//*------------------------------------------------------------------------ */
#define UNIPRO_RMM__UNIPRO_CREDITS_INC_2047                0x1FFCul

    /* 
     * List of register bitfields for component UNIPRO_RMM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   UNIPRO_RMM__UNIPRO_CREDITS_INC_0__VALUE   
 *
 * @BRIEF        Bitfield description is not available - (WO)
 *
    *//*------------------------------------------------------------------------ */
#define UNIPRO_RMM__UNIPRO_CREDITS_INC_0__VALUE       BITFIELD(31, 0)
#define UNIPRO_RMM__UNIPRO_CREDITS_INC_0__VALUE__POS  0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   UNIPRO_RMM__UNIPRO_CREDITS_INC_2047__VALUE   
 *
 * @BRIEF        Bitfield description is not available - (WO)
 *
    *//*------------------------------------------------------------------------ */
#define UNIPRO_RMM__UNIPRO_CREDITS_INC_2047__VALUE    BITFIELD(31, 0)
#define UNIPRO_RMM__UNIPRO_CREDITS_INC_2047__VALUE__POS 0

    /* 
     * List of register bitfields values for component UNIPRO_RMM
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __UNIPRO_RMM_CRED_H 
                                                            */
