/** ==================================================================
 *  @file   vlcd_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   VLCD
 *
 *  @Filename:    vlcd_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __VLCD_CRED_H
#define __VLCD_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance VLCD of component VLCD mapped in MONICA at address 0x55060600
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component VLCD
     *
     */

    /* 
     *  List of bundle arrays for component VLCD
     *
     */

    /* 
     *  List of bundles for component VLCD
     *
     */

    /* 
     * List of registers for component VLCD
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_REVISION
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_REVISION                               0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL
 *
 * @BRIEF        Control common between encode and decode 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL                                   0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_CFG
 *
 * @BRIEF        Encode configuration 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_CFG                                   0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_DCPREDY
 *
 * @BRIEF        Encode DC predictor for Y 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_DCPREDY                               0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_DCPREDUV
 *
 * @BRIEF        Encode DC predictor for U and V 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_DCPREDUV                              0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_BSPTR
 *
 * @BRIEF        Encode bitstream pointer 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_BSPTR                                 0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_CBUF
 *
 * @BRIEF        Encode bitstream circular buffer 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_CBUF                                  0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTCFG
 *
 * @BRIEF        Encode restart marker configuration 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTCFG                                0x1Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_DCTQM
 *
 * @BRIEF        Encode DCT coefficient and quantizer matrix pointers 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_DCTQM                                 0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_VLCTBL
 *
 * @BRIEF        Encode Huffman table pointer 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_VLCTBL                                0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTPTR
 *
 * @BRIEF        Encode restart marker locations 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTPTR                                0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTOFST
 *
 * @BRIEF        SDRAM address to add to encode restart marker locations 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTOFST                               0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CFG
 *
 * @BRIEF        Decode configuration 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CFG                                   0x40ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCPREDY
 *
 * @BRIEF        Decode DC predictor for Y 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCPREDY                               0x44ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCPREDUV
 *
 * @BRIEF        Decode DC predictor for U and V 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCPREDUV                              0x48ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_BSPTR
 *
 * @BRIEF        Decode bitstream pointer 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_BSPTR                                 0x4Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CBUF
 *
 * @BRIEF        Decode bitstream circular buffer 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CBUF                                  0x50ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCTQM
 *
 * @BRIEF        Decode DCT coefficient and quantizer matrix pointers 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCTQM                                 0x54ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CTRLTBL
 *
 * @BRIEF        Decode control table base 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CTRLTBL                               0x58ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCDTBL01
 *
 * @BRIEF        Decode Huffman tables 0 and 1 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCDTBL01                              0x5Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCDTBL23
 *
 * @BRIEF        Decode Huffman tables 2 and 3 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCDTBL23                              0x60ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCTERR
 *
 * @BRIEF        Register description is not available
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCTERR                                0x64ul

    /* 
     * List of register bitfields for component VLCD
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_REVISION__REV   
 *
 * @BRIEF        Revision number - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_REVISION__REV                     BITFIELD(7, 0)
#define VLCD__VLCDJ_REVISION__REV__POS                0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__RB1_STATUS   
 *
 * @BRIEF        Status of VLCDJ_RB1 signal - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__RB1_STATUS                  BITFIELD(18, 18)
#define VLCD__VLCDJ_CTRL__RB1_STATUS__POS             18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__RB0_STATUS   
 *
 * @BRIEF        Status of VLCDJ_RB0 signal - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__RB0_STATUS                  BITFIELD(17, 17)
#define VLCD__VLCDJ_CTRL__RB0_STATUS__POS             17

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__BUSY   
 *
 * @BRIEF        Idle/busy status, 0 = idle, 1 = busy - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__BUSY                        BITFIELD(16, 16)
#define VLCD__VLCDJ_CTRL__BUSY__POS                   16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__CLRRB   
 *
 * @BRIEF        When written 1, VLCDJ clears VLCDJ_REQ_B0/1 signals. 
 *               Write-only, read back 0 always. - (WO) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__CLRRB                       BITFIELD(7, 7)
#define VLCD__VLCDJ_CTRL__CLRRB__POS                  7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__RBEN   
 *
 * @BRIEF        Enable VLCDJ_RB0/1 signals. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__RBEN                        BITFIELD(6, 6)
#define VLCD__VLCDJ_CTRL__RBEN__POS                   6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__INTEN_ERR   
 *
 * @BRIEF        Interrupt enable for decode error - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__INTEN_ERR                   BITFIELD(5, 5)
#define VLCD__VLCDJ_CTRL__INTEN_ERR__POS              5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__INTEN_DONE   
 *
 * @BRIEF        Interrupt enable for task completion. 
 *               Note that DONE_VLCD is not gated by this and is always 
 *               asserted at task completion. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__INTEN_DONE                  BITFIELD(4, 4)
#define VLCD__VLCDJ_CTRL__INTEN_DONE__POS             4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__AUTOGATING   
 *
 * @BRIEF        Internal clock gating on OCP clock and functional clock 
 *               0 = clocks are free-running 
 *               1 = clocks are gated off in subblocks that are not needed 
 *               for operation - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__AUTOGATING                  BITFIELD(3, 3)
#define VLCD__VLCDJ_CTRL__AUTOGATING__POS             3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__TRIG_SRC   
 *
 * @BRIEF        Which mechanism starts VLCDJ operation 
 *               0 = MMR write to VLCDJ_CTRL.EN 
 *               1 = hardware start signal - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__TRIG_SRC                    BITFIELD(2, 2)
#define VLCD__VLCDJ_CTRL__TRIG_SRC__POS               2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__MODE   
 *
 * @BRIEF        0 = encode, 1 = decode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__MODE                        BITFIELD(1, 1)
#define VLCD__VLCDJ_CTRL__MODE__POS                   1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJ_CTRL__EN   
 *
 * @BRIEF        Module enable by software (write-only, read back 0 always) 
 *               When TRIG_SRC=0 and BUSY=0, write 1 to this field to start 
 *               VLCDJ. 
 *               When TRIG_SRC=1, writes to this field are ignored. 
 *               Setting both TRIG_SRC=0 and EN=1 on the same register write 
 *               is recognized. - (WO) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJ_CTRL__EN                          BITFIELD(0, 0)
#define VLCD__VLCDJ_CTRL__EN__POS                     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_CFG__NMCUS   
 *
 * @BRIEF        Number of MCUs (FMT = 0, 1) or blocks (FMT = 2) to encode 
 *               0 = 1 MCU, 1 = 2 MCUs, etc - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_CFG__NMCUS                       BITFIELD(13, 8)
#define VLCD__VLCDJE_CFG__NMCUS__POS                  8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_CFG__RLOCEN   
 *
 * @BRIEF        Restart marker location recording enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_CFG__RLOCEN                      BITFIELD(3, 3)
#define VLCD__VLCDJE_CFG__RLOCEN__POS                 3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_CFG__RSTEN   
 *
 * @BRIEF        Restart marker insertion enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_CFG__RSTEN                       BITFIELD(2, 2)
#define VLCD__VLCDJE_CFG__RSTEN__POS                  2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_CFG__FMT   
 *
 * @BRIEF        0 = YUV420 
 *               1 = YUV422 
 *               2 = sequential blocks - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_CFG__FMT                         BITFIELD(1, 0)
#define VLCD__VLCDJE_CFG__FMT__POS                    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_DCPREDY__PREDY   
 *
 * @BRIEF        DC predictor for Y - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_DCPREDY__PREDY                   BITFIELD(11, 0)
#define VLCD__VLCDJE_DCPREDY__PREDY__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_DCPREDUV__PREDV   
 *
 * @BRIEF        DC predictor for V - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_DCPREDUV__PREDV                  BITFIELD(27, 16)
#define VLCD__VLCDJE_DCPREDUV__PREDV__POS             16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_DCPREDUV__PREDU   
 *
 * @BRIEF        DC predictor for U - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_DCPREDUV__PREDU                  BITFIELD(11, 0)
#define VLCD__VLCDJE_DCPREDUV__PREDU__POS             0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_BSPTR__BITPTR   
 *
 * @BRIEF        Bit pointer, 1..8, indicates number of available bits - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_BSPTR__BITPTR                    BITFIELD(19, 16)
#define VLCD__VLCDJE_BSPTR__BITPTR__POS               16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_BSPTR__BYTEPTR   
 *
 * @BRIEF        Byte pointer (to BSMEM) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_BSPTR__BYTEPTR                   BITFIELD(11, 0)
#define VLCD__VLCDJE_BSPTR__BYTEPTR__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_CBUF__END   
 *
 * @BRIEF        Ending quarter (1K bytes each unit) of bitstream buffer. 
 *               Software can write a byte address into the upper 16-bit - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_CBUF__END                        BITFIELD(27, 26)
#define VLCD__VLCDJE_CBUF__END__POS                   26

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_CBUF__START   
 *
 * @BRIEF        Starting quarter (1K bytes each unit) of bitstream buffer. 
 *               Software can write a byte address to the lower 16-bit. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_CBUF__START                      BITFIELD(11, 10)
#define VLCD__VLCDJE_CBUF__START__POS                 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTCFG__INC   
 *
 * @BRIEF        Restart count increment value - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTCFG__INC                      BITFIELD(30, 28)
#define VLCD__VLCDJE_RSTCFG__INC__POS                 28

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTCFG__INIT   
 *
 * @BRIEF        Restart marker initial count - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTCFG__INIT                     BITFIELD(26, 24)
#define VLCD__VLCDJE_RSTCFG__INIT__POS                24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTCFG__PHASE   
 *
 * @BRIEF        MCU count within the interval - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTCFG__PHASE                    BITFIELD(21, 12)
#define VLCD__VLCDJE_RSTCFG__PHASE__POS               12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTCFG__INTRVL   
 *
 * @BRIEF        Restart interval (in MCUs) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTCFG__INTRVL                   BITFIELD(9, 0)
#define VLCD__VLCDJE_RSTCFG__INTRVL__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_DCTQM__QMR   
 *
 * @BRIEF        Quarter (128 bytes/unit) of quantization matrix reciprocal 
 *               Software can write a byte address to the upper 16-bit - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_DCTQM__QMR                       BITFIELD(24, 23)
#define VLCD__VLCDJE_DCTQM__QMR__POS                  23

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_DCTQM__DCT   
 *
 * @BRIEF        128-bit/word address of DCT coefficients. 
 *               Software can write a byte address to the lower 16-bit. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_DCTQM__DCT                       BITFIELD(13, 4)
#define VLCD__VLCDJE_DCTQM__DCT__POS                  4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_VLCTBL__ADDR   
 *
 * @BRIEF        Encode Huffman table pointer, 32-bit/word address 
 *               Software can write a byte address into the whole register - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_VLCTBL__ADDR                     BITFIELD(11, 2)
#define VLCD__VLCDJE_VLCTBL__ADDR__POS                2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTPTR__ADDR   
 *
 * @BRIEF        Pointer to restart marker locations in image buffer, 
 *               128-bit/word address 
 *               Software can write a byte address into the whole register - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTPTR__ADDR                     BITFIELD(13, 4)
#define VLCD__VLCDJE_RSTPTR__ADDR__POS                4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJE_RSTOFST__OFFSET   
 *
 * @BRIEF        SDRAM address of bitstream buffer, to be added to the 
 *               restart marker locations - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJE_RSTOFST__OFFSET                  BITFIELD(31, 0)
#define VLCD__VLCDJE_RSTOFST__OFFSET__POS             0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CFG__NMCUS   
 *
 * @BRIEF        Number of MCUs (FMT = 0, 1) or blocks (FMT = 2) to decode 
 *               0 = 1 MCU, 1 = 2 MCUs, etc - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CFG__NMCUS                       BITFIELD(13, 8)
#define VLCD__VLCDJD_CFG__NMCUS__POS                  8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CFG__RSTEN   
 *
 * @BRIEF        Restart marker detection/processing enable - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CFG__RSTEN                       BITFIELD(2, 2)
#define VLCD__VLCDJD_CFG__RSTEN__POS                  2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CFG__FMT   
 *
 * @BRIEF        0 = YUV420 
 *               1 = YUV422 
 *               2 = sequential blocks - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CFG__FMT                         BITFIELD(1, 0)
#define VLCD__VLCDJD_CFG__FMT__POS                    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCPREDY__PREDY   
 *
 * @BRIEF        DC predictor for Y - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCPREDY__PREDY                   BITFIELD(11, 0)
#define VLCD__VLCDJD_DCPREDY__PREDY__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCPREDUV__PREDV   
 *
 * @BRIEF        DC predictor for V - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCPREDUV__PREDV                  BITFIELD(27, 16)
#define VLCD__VLCDJD_DCPREDUV__PREDV__POS             16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCPREDUV__PREDU   
 *
 * @BRIEF        DC predictor for U - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCPREDUV__PREDU                  BITFIELD(11, 0)
#define VLCD__VLCDJD_DCPREDUV__PREDU__POS             0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_BSPTR__BITPTR   
 *
 * @BRIEF        Bit pointer, 1..8, indicates number of available bits - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_BSPTR__BITPTR                    BITFIELD(19, 16)
#define VLCD__VLCDJD_BSPTR__BITPTR__POS               16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_BSPTR__BYTEPTR   
 *
 * @BRIEF        Byte pointer (to BSMEM) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_BSPTR__BYTEPTR                   BITFIELD(11, 0)
#define VLCD__VLCDJD_BSPTR__BYTEPTR__POS              0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CBUF__END   
 *
 * @BRIEF        Ending quarter (1K bytes each unit) of bitstream buffer. 
 *               Software can write a byte address into the upper 16-bit - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CBUF__END                        BITFIELD(27, 26)
#define VLCD__VLCDJD_CBUF__END__POS                   26

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CBUF__START   
 *
 * @BRIEF        Starting quarter (1K bytes each unit) of bitstream buffer. 
 *               Software can write a byte address to the lower 16-bit. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CBUF__START                      BITFIELD(11, 10)
#define VLCD__VLCDJD_CBUF__START__POS                 10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCTQM__QM   
 *
 * @BRIEF        Quarter (128 bytes/unit) of quantization matrix  
 *               Software can write a byte address to the upper 16-bit - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCTQM__QM                        BITFIELD(24, 23)
#define VLCD__VLCDJD_DCTQM__QM__POS                   23

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCTQM__DCT   
 *
 * @BRIEF        128-bit/word address of DCT coefficients. 
 *               Software can write a byte address to the lower 16-bit. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCTQM__DCT                       BITFIELD(13, 4)
#define VLCD__VLCDJD_DCTQM__DCT__POS                  4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_CTRLTBL__ADDR   
 *
 * @BRIEF        Starting address of decode control table, 32-bit/word. 
 *               Software can write a byte address into the whole register - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_CTRLTBL__ADDR                    BITFIELD(11, 2)
#define VLCD__VLCDJD_CTRLTBL__ADDR__POS               2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCDTBL01__DCDTBL1   
 *
 * @BRIEF        Starting byte address of decode table 1, 32-bit/word. 
 *               Software can write a byte address into the lower 16-bit of 
 *               register. 
 *               This is for luma AC. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCDTBL01__DCDTBL1                BITFIELD(27, 18)
#define VLCD__VLCDJD_DCDTBL01__DCDTBL1__POS           18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCDTBL01__DCDTBL0   
 *
 * @BRIEF        Starting byte address of decode table 0, 32-bit/word. 
 *               Software can write a byte address into the lower 16-bit of 
 *               register. 
 *               This is for luma DC. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCDTBL01__DCDTBL0                BITFIELD(11, 2)
#define VLCD__VLCDJD_DCDTBL01__DCDTBL0__POS           2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCDTBL23__DCDTBL3   
 *
 * @BRIEF        Starting byte address of decode table 3, 32-bit/word. 
 *               Software can write a byte address into the lower 16-bit of 
 *               register. 
 *               This is for chroma AC. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCDTBL23__DCDTBL3                BITFIELD(27, 18)
#define VLCD__VLCDJD_DCDTBL23__DCDTBL3__POS           18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCDTBL23__DCDTBL2   
 *
 * @BRIEF        Starting byte address of decode table 2, 32-bit/word. 
 *               Software can write a byte address into the lower 16-bit of 
 *               register. 
 *               This is for chroma DC. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCDTBL23__DCDTBL2                BITFIELD(11, 2)
#define VLCD__VLCDJD_DCDTBL23__DCDTBL2__POS           2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   VLCD__VLCDJD_DCTERR__ERRPTR   
 *
 * @BRIEF        Byte address pointer to DCT coefficients, near where decode 
 *               error occurs (read-only) - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define VLCD__VLCDJD_DCTERR__ERRPTR                   BITFIELD(13, 0)
#define VLCD__VLCDJD_DCTERR__ERRPTR__POS              0

    /* 
     * List of register bitfields values for component VLCD
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __VLCD_CRED_H */
