/** ==================================================================
 *  @file   watchdogocp2_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   WATCHDOGOCP2
 *
 *  @Filename:    watchdogocp2_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __WATCHDOGOCP2_CRED_H
#define __WATCHDOGOCP2_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance WATCHDOGOCP2 of component WATCHDOGOCP2 mapped in MONICA at address 0x49030000
     * Instance WATCHDOGOCP2_2 of component WATCHDOGOCP2 mapped in MONICA at address 0x4A314000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component WATCHDOGOCP2
     *
     */

    /* 
     *  List of bundle arrays for component WATCHDOGOCP2
     *
     */

    /* 
     *  List of bundles for component WATCHDOGOCP2
     *
     */

    /* 
     * List of registers for component WATCHDOGOCP2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIDR
 *
 * @BRIEF        IP Revision Identifier 
 *               This allows a PID showing X.Y.R in silicon to relate the RTL 
 *               release with a (close-to-correct) spec version X.Y.S. 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIDR                                 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC
 *
 * @BRIEF        This register controls the various parameters of the OCP 
 *               interface 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC                                 0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDST
 *
 * @BRIEF        This register provides status information about the module 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDST                                 0x14ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR
 *
 * @BRIEF        This register shows which interrupt events are pending 
 *               inside the module 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR                                 0x18ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIER
 *
 * @BRIEF        This register controls (enable/disable) the interrupt events 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIER                                 0x1Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWER
 *
 * @BRIEF        This register controls (enable/disable) the wakeup events 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWER                                 0x20ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WCLR
 *
 * @BRIEF        This register controls the prescaler stage of the counter 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WCLR                                 0x24ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WCRR
 *
 * @BRIEF        This register holds the value of the internal counter 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WCRR                                 0x28ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WLDR
 *
 * @BRIEF        This register holds the timer's load value 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WLDR                                 0x2Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WTGR
 *
 * @BRIEF        Writing a different value than the one alredy written in 
 *               this register does a watchdog counter reload 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WTGR                                 0x30ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS
 *
 * @BRIEF        This register contains the write posting bits for all 
 *               write-able functional registers 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS                                 0x34ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDLY
 *
 * @BRIEF        This register holds the delay value that controls the 
 *               internal pre-overflow event detection 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDLY                                 0x44ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WSPR
 *
 * @BRIEF        This register holds the start-stop value that controls the 
 *               internal start-stop fsm 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WSPR                                 0x48ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQEOI
 *
 * @BRIEF        Software End Of Interrupt 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQEOI                              0x50ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW
 *
 * @BRIEF        IRQ unmasked status, status set 
 *               Per-event raw interrupt status vector, line #0.  
 *               Raw status is set even if event is not enabled. 
 *               Write 1 to set the (raw) status, mostly for debug. 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW                          0x54ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT
 *
 * @BRIEF        IRQ masked status, status clear 
 *               Per-event "enabled" interrupt status vector, line #0. 
 *               Enabled status isn't set unless event is enabled. 
 *               Write 1 to clear the status after interrupt has been 
 *               serviced (raw status gets cleared, i.e. even if not 
 *               enabled). 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT                             0x58ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET
 *
 * @BRIEF        IRQ enable set 
 *               Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to set (enable interrupt). 
 *               Readout equal to corresponding _CLR register. 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET                            0x5Cul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR
 *
 * @BRIEF        IRQ enable clear 
 *               Per-event interrupt enable bit vector, line #0.  
 *               Write 1 to clear (disable interrupt). 
 *               Readout equal to corresponding _SET register. 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR                            0x60ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQWAKEEN
 *
 * @BRIEF        This register controls (enable/disable) the wakeup events 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQWAKEEN                           0x64ul

    /* 
     * List of register bitfields for component WATCHDOGOCP2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIDR__SCHEME   
 *
 * @BRIEF        Used to distinguish between old Scheme and current.  
 *               Spare bit to encode future schemes. 
 *               Highlander 0.8 value: 0b01 - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIDR__SCHEME                    BITFIELD(31, 30)
#define WATCHDOGOCP2__WIDR__SCHEME__POS               30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIDR__FUNC   
 *
 * @BRIEF        Function indicates a software compatible module family.   
 *               If there is no level of software compatibility a new Func 
 *               number (and hence PID) should be assigned. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIDR__FUNC                      BITFIELD(27, 16)
#define WATCHDOGOCP2__WIDR__FUNC__POS                 16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIDR__RTL   
 *
 * @BRIEF        RTL Version.  
 *               R as described in PDR with additional 
 *               clarifications/definitions below.  Must be easily ECO-able 
 *               or controlled during fabrication.  Ideally through a top 
 *               level metal mask or e-fuse. This number is maintained/owned 
 *               by IP design owner - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIDR__RTL                       BITFIELD(15, 11)
#define WATCHDOGOCP2__WIDR__RTL__POS                  11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIDR__MAJOR   
 *
 * @BRIEF        Major Revision.   
 *               X as described in PDR with additional 
 *               clarifications/definitions below. This number is 
 *               owned/maintained by IP specification owner. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIDR__MAJOR                     BITFIELD(10, 8)
#define WATCHDOGOCP2__WIDR__MAJOR__POS                8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIDR__CUSTOM   
 *
 * @BRIEF        Indicates a special version for a particular device.  
 *               Consequence of use may avoid use of standard Chip Support 
 *               Library (CSL) / Drivers.   
 *               0 if non-custom. - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIDR__CUSTOM                    BITFIELD(7, 6)
#define WATCHDOGOCP2__WIDR__CUSTOM__POS               6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIDR__MINOR   
 *
 * @BRIEF        Minor Revision.   
 *               Y as described in PDR with additional 
 *               clarifications/definitions below.  
 *               This number is owned/maintained by IP specification owner. - 
 *               (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIDR__MINOR                     BITFIELD(5, 0)
#define WATCHDOGOCP2__WIDR__MINOR__POS                0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__EMUFREE   
 *
 * @BRIEF        Emulation mode - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__EMUFREE                   BITFIELD(5, 5)
#define WATCHDOGOCP2__WDSC__EMUFREE__POS              5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__IDLEMODE   
 *
 * @BRIEF        Configuration of the local target state management mode. 
 *               By definition, target can handle read/write transaction as 
 *               long as it is out of IDLE state - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__IDLEMODE                  BITFIELD(4, 3)
#define WATCHDOGOCP2__WDSC__IDLEMODE__POS             3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__SOFTRESET   
 *
 * @BRIEF        Software reset. (Optional) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__SOFTRESET                 BITFIELD(1, 1)
#define WATCHDOGOCP2__WDSC__SOFTRESET__POS            1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDST__RESETDONE   
 *
 * @BRIEF        Internal Module reset monitoring - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDST__RESETDONE                 BITFIELD(0, 0)
#define WATCHDOGOCP2__WDST__RESETDONE__POS            0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__DLY_IT_FLAG   
 *
 * @BRIEF        Pending delay interrupt status. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__DLY_IT_FLAG               BITFIELD(1, 1)
#define WATCHDOGOCP2__WISR__DLY_IT_FLAG__POS          1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__OVF_IT_FLAG   
 *
 * @BRIEF        Pending overflow interrupt status. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__OVF_IT_FLAG               BITFIELD(0, 0)
#define WATCHDOGOCP2__WISR__OVF_IT_FLAG__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIER__DLY_IT_ENA   
 *
 * @BRIEF        Enable/disable delay interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIER__DLY_IT_ENA                BITFIELD(1, 1)
#define WATCHDOGOCP2__WIER__DLY_IT_ENA__POS           1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIER__OVF_IT_ENA   
 *
 * @BRIEF        Enable/disable overflow interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIER__OVF_IT_ENA                BITFIELD(0, 0)
#define WATCHDOGOCP2__WIER__OVF_IT_ENA__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWER__DLY_WK_ENA   
 *
 * @BRIEF        Enable delay wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWER__DLY_WK_ENA                BITFIELD(1, 1)
#define WATCHDOGOCP2__WWER__DLY_WK_ENA__POS           1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWER__OVF_WK_ENA   
 *
 * @BRIEF        Enable overflow wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWER__OVF_WK_ENA                BITFIELD(0, 0)
#define WATCHDOGOCP2__WWER__OVF_WK_ENA__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WCLR__PRE   
 *
 * @BRIEF        Prescaler enable/disable configuration - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WCLR__PRE                       BITFIELD(5, 5)
#define WATCHDOGOCP2__WCLR__PRE__POS                  5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WCLR__PTV   
 *
 * @BRIEF        Prescaler value 
 *               The timer counter is prescaled with the value: 2**PTV 
 *               Example: PTV = 3 -> counter increases value is started after 
 *               8 functional clock periods 
 *               On reset it is loaded from PI_PTV_RESET_VALUE input port. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WCLR__PTV                       BITFIELD(4, 2)
#define WATCHDOGOCP2__WCLR__PTV__POS                  2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WCRR__TIMER_COUNTER   
 *
 * @BRIEF        The value of the timer counter register 
 *               On reset it is loaded from PI_WLDR_RESET_VALUE input port. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WCRR__TIMER_COUNTER             BITFIELD(31, 0)
#define WATCHDOGOCP2__WCRR__TIMER_COUNTER__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WLDR__TIMER_LOAD   
 *
 * @BRIEF        The value of the timer load register 
 *               On reset it is loaded from PI_WLDR_RESET_VALUE input port. - 
 *               (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WLDR__TIMER_LOAD                BITFIELD(31, 0)
#define WATCHDOGOCP2__WLDR__TIMER_LOAD__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WTGR__TTGR_VALUE   
 *
 * @BRIEF        The value of the trigger register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WTGR__TTGR_VALUE                BITFIELD(31, 0)
#define WATCHDOGOCP2__WTGR__TTGR_VALUE__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WDLY   
 *
 * @BRIEF        Write pending for register WDLY - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WDLY               BITFIELD(5, 5)
#define WATCHDOGOCP2__WWPS__W_PEND_WDLY__POS          5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WSPR   
 *
 * @BRIEF        Write pending for register WSPR - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WSPR               BITFIELD(4, 4)
#define WATCHDOGOCP2__WWPS__W_PEND_WSPR__POS          4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WTGR   
 *
 * @BRIEF        Write pending for register WTGR - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WTGR               BITFIELD(3, 3)
#define WATCHDOGOCP2__WWPS__W_PEND_WTGR__POS          3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WLDR   
 *
 * @BRIEF        Write pending for register WLDR - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WLDR               BITFIELD(2, 2)
#define WATCHDOGOCP2__WWPS__W_PEND_WLDR__POS          2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WCRR   
 *
 * @BRIEF        Write pending for register WCRR - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WCRR               BITFIELD(1, 1)
#define WATCHDOGOCP2__WWPS__W_PEND_WCRR__POS          1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WCLR   
 *
 * @BRIEF        Write pending for register WCLR - (RO) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WCLR               BITFIELD(0, 0)
#define WATCHDOGOCP2__WWPS__W_PEND_WCLR__POS          0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDLY__WDLY_VALUE   
 *
 * @BRIEF        The value of the delay register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDLY__WDLY_VALUE                BITFIELD(31, 0)
#define WATCHDOGOCP2__WDLY__WDLY_VALUE__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WSPR__WSPR_VALUE   
 *
 * @BRIEF        The value of the start-stop register - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WSPR__WSPR_VALUE                BITFIELD(31, 0)
#define WATCHDOGOCP2__WSPR__WSPR_VALUE__POS           0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQEOI__LINE_NUMBER   
 *
 * @BRIEF        EOI for interrupt output line 
 *               Reads always 0 (no EOI memory) - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQEOI__LINE_NUMBER            BITFIELD(0, 0)
#define WATCHDOGOCP2__WIRQEOI__LINE_NUMBER__POS       0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY   
 *
 * @BRIEF        settable raw status for delay event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY          BITFIELD(1, 1)
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__POS     1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF   
 *
 * @BRIEF        settable raw status for overflow event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF          BITFIELD(0, 0)
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_DLY   
 *
 * @BRIEF        clearable, enabled status for  delay event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_DLY             BITFIELD(1, 1)
#define WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__POS        1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_OVF   
 *
 * @BRIEF        clearable, enabled status for  overflow event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_OVF             BITFIELD(0, 0)
#define WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__POS        0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_DLY   
 *
 * @BRIEF        enable for delay event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_DLY           BITFIELD(1, 1)
#define WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__POS      1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_OVF   
 *
 * @BRIEF        enable for overflow event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_OVF           BITFIELD(0, 0)
#define WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY   
 *
 * @BRIEF        enable for delay event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY           BITFIELD(1, 1)
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__POS      1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF   
 *
 * @BRIEF        enable for overflow event - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF           BITFIELD(0, 0)
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__POS      0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQWAKEEN__DLY_WK_ENA   
 *
 * @BRIEF        Enable delay wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQWAKEEN__DLY_WK_ENA          BITFIELD(1, 1)
#define WATCHDOGOCP2__WIRQWAKEEN__DLY_WK_ENA__POS     1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQWAKEEN__OVF_WK_ENA   
 *
 * @BRIEF        Enable overflow wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQWAKEEN__OVF_WK_ENA          BITFIELD(0, 0)
#define WATCHDOGOCP2__WIRQWAKEEN__OVF_WK_ENA__POS     0

    /* 
     * List of register bitfields values for component WATCHDOGOCP2
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__EMUFREE__DISABLED
 *
 * @BRIEF        Timer counter frozen in emulation - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__EMUFREE__DISABLED         0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__EMUFREE__ENABLED
 *
 * @BRIEF        Timer counter free-running in emulation - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__EMUFREE__ENABLED          0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__IDLEMODE__FORCEIDLE
 *
 * @BRIEF        Force-idle mode: local target's idle state follows 
 *               (acknowledges) the system's idle requests unconditionally, 
 *               i.e. regardless of the IP module's internal requirements. 
 *               Backup mode, for debug only. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__IDLEMODE__FORCEIDLE       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__IDLEMODE__NOIDLE
 *
 * @BRIEF        No-idle mode: local target never enters idle state. 
 *               Backup mode, for debug only. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__IDLEMODE__NOIDLE          0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__IDLEMODE__SMARTIDLE
 *
 * @BRIEF        Smart-idle mode: local target's idle state eventually 
 *               follows (acknowledges) the system's idle requests, depending 
 *               on the IP module's internal requirements. 
 *               IP module shall not generate (IRQ- or DMA-request-related) 
 *               wakeup events. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__IDLEMODE__SMARTIDLE       0x2ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__IDLEMODE__SMARTIDLEWAKEUP
 *
 * @BRIEF        Smart-idle wakeup-capable mode: local target's idle state 
 *               eventually follows (acknowledges) the system's idle 
 *               requests, depending on the IP module's internal 
 *               requirements. 
 *               IP module may generate (IRQ- or DMA-request-related) wakeup 
 *               events when in idle state. 
 *               Mode is only relevant if the appropriate IP module "swakeup" 
 *               output(s) is (are) implemented. - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__IDLEMODE__SMARTIDLEWAKEUP 0x3ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__SOFTRESET__RESETCOMPLETED
 *
 * @BRIEF        Reset done, no pending action - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__SOFTRESET__RESETCOMPLETED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__SOFTRESET__NOACTION
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__SOFTRESET__NOACTION       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__SOFTRESET__RESETCMD
 *
 * @BRIEF        Initiate software reset - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__SOFTRESET__RESETCMD       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDSC__SOFTRESET__RESETONGOING
 *
 * @BRIEF        Reset (software or other) ongoing - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDSC__SOFTRESET__RESETONGOING   0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDST__RESETDONE__ONGOING
 *
 * @BRIEF        Internal module reset in on-going - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDST__RESETDONE__ONGOING        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WDST__RESETDONE__RESETDONE
 *
 * @BRIEF        Reset completed - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WDST__RESETDONE__RESETDONE      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__DLY_IT_FLAG__READ_0
 *
 * @BRIEF        No delay interrupt pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__DLY_IT_FLAG__READ_0       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__DLY_IT_FLAG__WRITE_0
 *
 * @BRIEF        Status unchanged - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__DLY_IT_FLAG__WRITE_0      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__DLY_IT_FLAG__WRITE_1
 *
 * @BRIEF        Status bit cleared - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__DLY_IT_FLAG__WRITE_1      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__DLY_IT_FLAG__READ_1
 *
 * @BRIEF        Delay interrupt pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__DLY_IT_FLAG__READ_1       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__OVF_IT_FLAG__READ_0
 *
 * @BRIEF        No overflow interrupt pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__OVF_IT_FLAG__READ_0       0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__OVF_IT_FLAG__WRITE_0
 *
 * @BRIEF        Status unchanged - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__OVF_IT_FLAG__WRITE_0      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__OVF_IT_FLAG__WRITE_1
 *
 * @BRIEF        Status bit cleared - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__OVF_IT_FLAG__WRITE_1      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WISR__OVF_IT_FLAG__READ_1
 *
 * @BRIEF        Overflow interrupt pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WISR__OVF_IT_FLAG__READ_1       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIER__DLY_IT_ENA__DISABLED
 *
 * @BRIEF        Disable delay interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIER__DLY_IT_ENA__DISABLED      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIER__DLY_IT_ENA__ENABLED
 *
 * @BRIEF        Enable delay interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIER__DLY_IT_ENA__ENABLED       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIER__OVF_IT_ENA__DISABLED
 *
 * @BRIEF        Disable overflow interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIER__OVF_IT_ENA__DISABLED      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIER__OVF_IT_ENA__ENABLED
 *
 * @BRIEF        Enable overflow interrupt - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIER__OVF_IT_ENA__ENABLED       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWER__DLY_WK_ENA__DISABLED
 *
 * @BRIEF        Disable delay wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWER__DLY_WK_ENA__DISABLED      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWER__DLY_WK_ENA__ENABLED
 *
 * @BRIEF        Enable delay wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWER__DLY_WK_ENA__ENABLED       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWER__OVF_WK_ENA__DISABLED
 *
 * @BRIEF        Disable overflow wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWER__OVF_WK_ENA__DISABLED      0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWER__OVF_WK_ENA__ENABLED
 *
 * @BRIEF        Enable overflow wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWER__OVF_WK_ENA__ENABLED       0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WCLR__PRE__DISABLED
 *
 * @BRIEF        Prescaler disabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WCLR__PRE__DISABLED             0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WCLR__PRE__ENABLED
 *
 * @BRIEF        Prescaler enabled - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WCLR__PRE__ENABLED              0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WDLY__READY
 *
 * @BRIEF        No register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WDLY__READY        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WDLY__PENDING
 *
 * @BRIEF        Register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WDLY__PENDING      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WSPR__READY
 *
 * @BRIEF        No register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WSPR__READY        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WSPR__PENDING
 *
 * @BRIEF        Register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WSPR__PENDING      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WTGR__READY
 *
 * @BRIEF        No register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WTGR__READY        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WTGR__PENDING
 *
 * @BRIEF        Register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WTGR__PENDING      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WLDR__READY
 *
 * @BRIEF        No register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WLDR__READY        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WLDR__PENDING
 *
 * @BRIEF        Register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WLDR__PENDING      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WCRR__READY
 *
 * @BRIEF        No register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WCRR__READY        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WCRR__PENDING
 *
 * @BRIEF        Register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WCRR__PENDING      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WCLR__READY
 *
 * @BRIEF        No register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WCLR__READY        0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WWPS__W_PEND_WCLR__PENDING
 *
 * @BRIEF        Register write pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WWPS__W_PEND_WCLR__PENDING      0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__READ_0
 *
 * @BRIEF        No event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__READ_0  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__WRITE_0
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__WRITE_0 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__WRITE_1
 *
 * @BRIEF        Set event (debug) - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__WRITE_1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__READ_1
 *
 * @BRIEF        Event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_DLY__READ_1  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__READ_0
 *
 * @BRIEF        No event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__READ_0  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__WRITE_0
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__WRITE_0 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__WRITE_1
 *
 * @BRIEF        Set event (debug) - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__WRITE_1 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__READ_1
 *
 * @BRIEF        Event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTATRAW__EVENT_OVF__READ_1  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__READ_0
 *
 * @BRIEF        No (enabled) event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__READ_0     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__WRITE_0
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__WRITE_0    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__WRITE_1
 *
 * @BRIEF        Clear (raw) event - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__WRITE_1    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__READ_1
 *
 * @BRIEF        Event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_DLY__READ_1     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__READ_0
 *
 * @BRIEF        No (enabled) event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__READ_0     0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__WRITE_0
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__WRITE_0    0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__WRITE_1
 *
 * @BRIEF        Clear (raw) event - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__WRITE_1    0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__READ_1
 *
 * @BRIEF        Event pending - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQSTAT__EVENT_OVF__READ_1     0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__READ_0
 *
 * @BRIEF        Interrupt disabled (masked) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__READ_0   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__WRITE_0
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__WRITE_0  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__WRITE_1
 *
 * @BRIEF        Enable interrupt - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__WRITE_1  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__READ_1
 *
 * @BRIEF        Interrupt enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_DLY__READ_1   0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__READ_0
 *
 * @BRIEF        Interrupt disabled (masked) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__READ_0   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__WRITE_0
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__WRITE_0  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__WRITE_1
 *
 * @BRIEF        Enable interrupt - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__WRITE_1  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__READ_1
 *
 * @BRIEF        Interrupt enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENSET__ENABLE_OVF__READ_1   0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__READ_0
 *
 * @BRIEF        Interrupt disabled (masked) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__READ_0   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__WRITE_0
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__WRITE_0  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__WRITE_1
 *
 * @BRIEF        Disable interrupt - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__WRITE_1  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__READ_1
 *
 * @BRIEF        Interrupt enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_DLY__READ_1   0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__READ_0
 *
 * @BRIEF        Interrupt disabled (masked) - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__READ_0   0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__WRITE_0
 *
 * @BRIEF        No action - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__WRITE_0  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__WRITE_1
 *
 * @BRIEF        Disable interrupt - (Write) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__WRITE_1  0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__READ_1
 *
 * @BRIEF        Interrupt enabled - (Read) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQENCLR__ENABLE_OVF__READ_1   0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQWAKEEN__DLY_WK_ENA__DISABLED
 *
 * @BRIEF        Disable delay wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQWAKEEN__DLY_WK_ENA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQWAKEEN__DLY_WK_ENA__ENABLED
 *
 * @BRIEF        Enable delay wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQWAKEEN__DLY_WK_ENA__ENABLED 0x1ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQWAKEEN__OVF_WK_ENA__DISABLED
 *
 * @BRIEF        Disable overflow wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQWAKEEN__OVF_WK_ENA__DISABLED 0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WATCHDOGOCP2__WIRQWAKEEN__OVF_WK_ENA__ENABLED
 *
 * @BRIEF        Enable overflow wakeup - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WATCHDOGOCP2__WIRQWAKEEN__OVF_WK_ENA__ENABLED 0x1ul

#ifdef __cplusplus
}
#endif
#endif                                                     /* __WATCHDOGOCP2_CRED_H 
                                                            */
