/** ==================================================================
 *  @file   wugen_local_prcm_cred.h                                                  
 *                                                                    
 *  @path   /ti/psp/iss/hal/cred_cram/cred/inc/cortexm3_sys_ape/                                                  
 *                                                                    
 *  @desc   This  File contains.                                      
 * ===================================================================
 *  Copyright (c) Texas Instruments Inc 2011, 2012                    
 *                                                                    
 *  Use of this software is controlled by the terms and conditions found
 *  in the license agreement under which this software has been supplied
 * ===================================================================*/

/* ============================================================================ 
 * TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION Property of Texas
 * Instruments For Unrestricted Internal Use Only Unauthorized reproduction
 * and/or distribution is strictly prohibited.  This product is protected
 * under copyright law and trade secret law as an unpublished work.  Created
 * 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved. */

/**
 *  @Component:   WUGEN_LOCAL_PRCM
 *
 *  @Filename:    wugen_local_prcm_cred.h
 *
 *  @Description: WUGEN module registers 
 *
 *  Generated by: Socrates CRED generator prototype
 *
    *//* ====================================================================== */

#ifndef __WUGEN_LOCAL_PRCM_CRED_H
#define __WUGEN_LOCAL_PRCM_CRED_H

#ifdef __cplusplus
extern "C" {
#endif

    /* 
     * Instance WUGEN_LOCAL_PRCM of component WUGEN_LOCAL_PRCM mapped in MONICA at address 0x40001000
     */

                                                                              /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
    *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

    /* 
     *  List of Register arrays for component WUGEN_LOCAL_PRCM
     *
     */

    /* 
     *  List of bundle arrays for component WUGEN_LOCAL_PRCM
     *
     */

    /* 
     *  List of bundles for component WUGEN_LOCAL_PRCM
     *
     */

    /* 
     * List of registers for component WUGEN_LOCAL_PRCM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_CTRL_REG
 *
 * @BRIEF        Interrupt set/clear to CortexM3 CPU1 or CPU2 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_CTRL_REG                  0x0ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__STANDBY_CORE_SYSCONFIG
 *
 * @BRIEF        Standby Protocol 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__STANDBY_CORE_SYSCONFIG           0x4ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__IDLE_CORE_SYSCONFIG
 *
 * @BRIEF        Idle protocol 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__IDLE_CORE_SYSCONFIG              0x8ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0
 *
 * @BRIEF        This register contains the interrupt mask (LSB)  
 *               Wakeup enable bit per interrupt request 
 *               0: Interrupt is disabled 
 *               1: Interrupt is enabled. 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0                      0xCul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1
 *
 * @BRIEF        This register contains the interrupt mask (MSB)  
 *               Wakeup enable bit per interrupt request 
 *               0: Interrupt is disabled 
 *               1: Interrupt is enabled. 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1                      0x10ul

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG
 *
 * @BRIEF        GPO pin mapping 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG                    0x14ul

    /* 
     * List of register bitfields for component WUGEN_LOCAL_PRCM
     *
     */

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_CTRL_REG__INT_CORTEX_2   
 *
 * @BRIEF        Interrupt to Cortex 2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_CTRL_REG__INT_CORTEX_2 BITFIELD(1, 1)
#define WUGEN_LOCAL_PRCM__DUCATI_CTRL_REG__INT_CORTEX_2__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_CTRL_REG__INT_CORTEX_1   
 *
 * @BRIEF        Interrupt to Cortex 1 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_CTRL_REG__INT_CORTEX_1 BITFIELD(0, 0)
#define WUGEN_LOCAL_PRCM__DUCATI_CTRL_REG__INT_CORTEX_1__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__STANDBY_CORE_SYSCONFIG__STANDBYMODE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__STANDBY_CORE_SYSCONFIG__STANDBYMODE BITFIELD(1, 0)
#define WUGEN_LOCAL_PRCM__STANDBY_CORE_SYSCONFIG__STANDBYMODE__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__IDLE_CORE_SYSCONFIG__IDLEMODE   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__IDLE_CORE_SYSCONFIG__IDLEMODE BITFIELD(1, 0)
#define WUGEN_LOCAL_PRCM__IDLE_CORE_SYSCONFIG__IDLEMODE__POS 0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ31   
 *
 * @BRIEF        Interrupt Mask bit #31 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ31         BITFIELD(31, 31)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ31__POS    31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ30   
 *
 * @BRIEF        Interrupt Mask bit #30 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ30         BITFIELD(30, 30)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ30__POS    30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ29   
 *
 * @BRIEF        Interrupt Mask bit #29 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ29         BITFIELD(29, 29)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ29__POS    29

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ28   
 *
 * @BRIEF        Interrupt Mask bit #28 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ28         BITFIELD(28, 28)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ28__POS    28

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ27   
 *
 * @BRIEF        Interrupt Mask bit #27 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ27         BITFIELD(27, 27)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ27__POS    27

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ26   
 *
 * @BRIEF        Interrupt Mask bit #26 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ26         BITFIELD(26, 26)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ26__POS    26

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ25   
 *
 * @BRIEF        Interrupt Mask bit #25 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ25         BITFIELD(25, 25)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ25__POS    25

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ24   
 *
 * @BRIEF        Interrupt Mask bit #24 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ24         BITFIELD(24, 24)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ24__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ23   
 *
 * @BRIEF        Interrupt Mask bit #23 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ23         BITFIELD(23, 23)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ23__POS    23

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ22   
 *
 * @BRIEF        Interrupt Mask bit #22 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ22         BITFIELD(22, 22)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ22__POS    22

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ21   
 *
 * @BRIEF        Interrupt Mask bit #21 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ21         BITFIELD(21, 21)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ21__POS    21

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ20   
 *
 * @BRIEF        Interrupt Mask bit #20 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ20         BITFIELD(20, 20)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ20__POS    20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ19   
 *
 * @BRIEF        Interrupt Mask bit #19 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ19         BITFIELD(19, 19)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ19__POS    19

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ18   
 *
 * @BRIEF        Interrupt Mask bit #18 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ18         BITFIELD(18, 18)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ18__POS    18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ17   
 *
 * @BRIEF        Interrupt Mask bit #17 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ17         BITFIELD(17, 17)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ17__POS    17

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ16   
 *
 * @BRIEF        Interrupt Mask bit #16 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ16         BITFIELD(16, 16)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ16__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ15   
 *
 * @BRIEF        Interrupt Mask bit #15 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ15         BITFIELD(15, 15)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ15__POS    15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ14   
 *
 * @BRIEF        Interrupt Mask bit #14 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ14         BITFIELD(14, 14)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ14__POS    14

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ13   
 *
 * @BRIEF        Interrupt Mask bit #13 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ13         BITFIELD(13, 13)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ13__POS    13

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ12   
 *
 * @BRIEF        Interrupt Mask bit #12 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ12         BITFIELD(12, 12)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ12__POS    12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ11   
 *
 * @BRIEF        Interrupt Mask bit #11 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ11         BITFIELD(11, 11)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ11__POS    11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ10   
 *
 * @BRIEF        Interrupt Mask bit #10 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ10         BITFIELD(10, 10)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ10__POS    10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ9   
 *
 * @BRIEF        Interrupt Mask bit #9 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ9          BITFIELD(9, 9)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ9__POS     9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ8   
 *
 * @BRIEF        Interrupt Mask bit #8 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ8          BITFIELD(8, 8)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ8__POS     8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ7   
 *
 * @BRIEF        Interrupt Mask bit #7 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ7          BITFIELD(7, 7)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ7__POS     7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ6   
 *
 * @BRIEF        Interrupt Mask bit #6 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ6          BITFIELD(6, 6)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ6__POS     6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ5   
 *
 * @BRIEF        Interrupt Mask bit #5 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ5          BITFIELD(5, 5)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ5__POS     5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ4   
 *
 * @BRIEF        Interrupt Mask bit #4 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ4          BITFIELD(4, 4)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ4__POS     4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ3   
 *
 * @BRIEF        Interrupt Mask bit #3 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ3          BITFIELD(3, 3)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ3__POS     3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ2   
 *
 * @BRIEF        Interrupt Mask bit #2 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ2          BITFIELD(2, 2)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ2__POS     2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ1   
 *
 * @BRIEF        Interrupt Mask bit #1 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ1          BITFIELD(1, 1)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ1__POS     1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ0   
 *
 * @BRIEF        Interrupt Mask bit #0 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ0          BITFIELD(0, 0)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT0__MIRQ0__POS     0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ63   
 *
 * @BRIEF        Interrupt Mask bit #63 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ63         BITFIELD(31, 31)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ63__POS    31

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ62   
 *
 * @BRIEF        Interrupt Mask bit #62 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ62         BITFIELD(30, 30)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ62__POS    30

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ61   
 *
 * @BRIEF        Interrupt Mask bit #61 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ61         BITFIELD(29, 29)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ61__POS    29

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ60   
 *
 * @BRIEF        Interrupt Mask bit #60 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ60         BITFIELD(28, 28)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ60__POS    28

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ59   
 *
 * @BRIEF        Interrupt Mask bit #59 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ59         BITFIELD(27, 27)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ59__POS    27

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ58   
 *
 * @BRIEF        Interrupt Mask bit #58 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ58         BITFIELD(26, 26)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ58__POS    26

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ57   
 *
 * @BRIEF        Interrupt Mask bit #57 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ57         BITFIELD(25, 25)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ57__POS    25

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ56   
 *
 * @BRIEF        Interrupt Mask bit #56 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ56         BITFIELD(24, 24)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ56__POS    24

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ55   
 *
 * @BRIEF        Interrupt Mask bit #55 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ55         BITFIELD(23, 23)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ55__POS    23

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ54   
 *
 * @BRIEF        Interrupt Mask bit #54 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ54         BITFIELD(22, 22)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ54__POS    22

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ53   
 *
 * @BRIEF        Interrupt Mask bit #53 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ53         BITFIELD(21, 21)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ53__POS    21

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ52   
 *
 * @BRIEF        Interrupt Mask bit #52 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ52         BITFIELD(20, 20)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ52__POS    20

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ51   
 *
 * @BRIEF        Interrupt Mask bit #51 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ51         BITFIELD(19, 19)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ51__POS    19

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ50   
 *
 * @BRIEF        Interrupt Mask bit #50 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ50         BITFIELD(18, 18)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ50__POS    18

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ49   
 *
 * @BRIEF        Interrupt Mask bit #49 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ49         BITFIELD(17, 17)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ49__POS    17

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ48   
 *
 * @BRIEF        Interrupt Mask bit #48 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ48         BITFIELD(16, 16)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ48__POS    16

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ47   
 *
 * @BRIEF        Interrupt Mask bit #47 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ47         BITFIELD(15, 15)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ47__POS    15

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ46   
 *
 * @BRIEF        Interrupt Mask bit #46 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ46         BITFIELD(14, 14)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ46__POS    14

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ45   
 *
 * @BRIEF        Interrupt Mask bit #45 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ45         BITFIELD(13, 13)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ45__POS    13

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ44   
 *
 * @BRIEF        Interrupt Mask bit #44 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ44         BITFIELD(12, 12)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ44__POS    12

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ43   
 *
 * @BRIEF        Interrupt Mask bit #43 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ43         BITFIELD(11, 11)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ43__POS    11

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ42   
 *
 * @BRIEF        Interrupt Mask bit #42 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ42         BITFIELD(10, 10)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ42__POS    10

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ41   
 *
 * @BRIEF        Interrupt Mask bit #41 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ41         BITFIELD(9, 9)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ41__POS    9

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ40   
 *
 * @BRIEF        Interrupt Mask bit #40 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ40         BITFIELD(8, 8)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ40__POS    8

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ39   
 *
 * @BRIEF        Interrupt Mask bit #39 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ39         BITFIELD(7, 7)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ39__POS    7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ38   
 *
 * @BRIEF        Interrupt Mask bit #38 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ38         BITFIELD(6, 6)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ38__POS    6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ37   
 *
 * @BRIEF        Interrupt Mask bit #37 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ37         BITFIELD(5, 5)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ37__POS    5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ36   
 *
 * @BRIEF        Interrupt Mask bit #36 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ36         BITFIELD(4, 4)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ36__POS    4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ35   
 *
 * @BRIEF        Interrupt Mask bit #35 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ35         BITFIELD(3, 3)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ35__POS    3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ34   
 *
 * @BRIEF        Interrupt Mask bit #34 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ34         BITFIELD(2, 2)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ34__POS    2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ33   
 *
 * @BRIEF        Interrupt Mask bit #33 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ33         BITFIELD(1, 1)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ33__POS    1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ32   
 *
 * @BRIEF        Interrupt Mask bit #32 - (RW) 
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ32         BITFIELD(0, 0)
#define WUGEN_LOCAL_PRCM__WUGEN_MEVT1__MIRQ32__POS    0

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT6   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT6   BITFIELD(7, 7)
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT6__POS 7

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT5   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT5   BITFIELD(6, 6)
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT5__POS 6

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT4   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT4   BITFIELD(5, 5)
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT4__POS 5

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT3   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT3   BITFIELD(4, 4)
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT3__POS 4

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT2   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT2   BITFIELD(3, 3)
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT2__POS 3

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT1   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT1   BITFIELD(2, 2)
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT1__POS 2

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT0   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT0   BITFIELD(1, 1)
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT0__POS 1

                                                                             /*-------------------------------------------------------------------------*//**
 * @DEFINITION   WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT7   
 *
 * @BRIEF        Bitfield description is not available - (RW)
 *
    *//*------------------------------------------------------------------------ */
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT7   BITFIELD(0, 0)
#define WUGEN_LOCAL_PRCM__DUCATI_GP_REG__POUSEROUT7__POS 0

    /* 
     * List of register bitfields values for component WUGEN_LOCAL_PRCM
     *
     */

#ifdef __cplusplus
}
#endif
#endif                                                     /* __WUGEN_LOCAL_PRCM_CRED_H 
                                                            */
